package main

import (
	"context"
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sync"

	appservice "github.com/persioflexa/harflex/internal/application"
	"github.com/persioflexa/harflex/internal/secrets"
	"github.com/persioflexa/harflex/internal/storage/sqlite"
	"github.com/wailsapp/wails/v3/pkg/application"
)

// frontend/dist is generated by Vite and intentionally ignored. The tracked
// dist.placeholder keeps clean checkouts buildable while the glob also embeds
// the generated dist directory in packaged builds.
//
//go:embed all:frontend/dist*
var assets embed.FS

func init() {
	application.RegisterEvent[appservice.EventDTO]("harflex:event")
	application.RegisterEvent[appservice.ScheduleChangeDTO]("harflex:schedule")
	application.RegisterEvent[appservice.UpdateStateDTO]("harflex:update")
}

const instanceID = "ai.harflex.desktop"

// resolveDataDir returns the catalog directory and the single-instance lock ID.
// HARFLEX_DATA_DIR lets a development instance run beside the installed app
// without sharing its database, recovery pass or instance lock.
func resolveDataDir(override string, userConfigDir func() (string, error)) (dir, lockID string, err error) {
	if override == "" {
		configDir, err := userConfigDir()
		if err != nil {
			return "", "", fmt.Errorf("resolve application directory: %w", err)
		}
		return filepath.Join(configDir, "Harflex"), instanceID, nil
	}
	dir, err = filepath.Abs(override)
	if err != nil {
		return "", "", fmt.Errorf("resolve HARFLEX_DATA_DIR: %w", err)
	}
	sum := sha256.Sum256([]byte(dir))
	return dir, instanceID + "." + hex.EncodeToString(sum[:4]), nil
}

// executionCacheRootFor keeps the project copies a pipeline's Code phase works on beside an isolated
// catalog. Without an override it returns "" and the service uses <user cache>/Harflex/sdd-executions.
func executionCacheRootFor(override, dataDir string) string {
	if override == "" {
		return ""
	}
	return filepath.Join(dataDir, "sdd-executions")
}

func openCatalog(ctx context.Context, dir string) (*sqlite.Store, error) {
	if err := os.MkdirAll(dir, 0700); err != nil {
		return nil, fmt.Errorf("create application directory: %w", err)
	}
	store, err := sqlite.Open(ctx, filepath.Join(dir, "harflex.db"))
	if err != nil {
		return nil, fmt.Errorf("open application catalog: %w", err)
	}
	return store, nil
}

func desktopOptions(service *appservice.Service, shutdown func()) application.Options {
	return application.Options{
		Name: "Harflex", Description: "Local-first agentic development harness",
		Services: []application.Service{application.NewServiceWithOptions(service, application.ServiceOptions{MarshalError: appservice.MarshalError})},
		SingleInstance: &application.SingleInstanceOptions{
			UniqueID: instanceID, ExitCode: 0,
		},
		Assets:     application.AssetOptions{Handler: application.AssetFileServerFS(assets)},
		Mac:        application.MacOptions{ApplicationShouldTerminateAfterLastWindowClosed: true},
		OnShutdown: shutdown,
	}
}
func windowOptions() application.WebviewWindowOptions {
	return application.WebviewWindowOptions{
		Title: "Harflex", Width: 1440, Height: 900, MinWidth: 320, MinHeight: 640,
		Mac:              application.MacWindow{InvisibleTitleBarHeight: 50, Backdrop: application.MacBackdropTranslucent, TitleBar: application.MacTitleBarHiddenInset},
		BackgroundColour: application.NewRGB(8, 11, 13), URL: "/",
	}
}

func newRecoveredService(ctx context.Context, deps appservice.Dependencies) (*appservice.Service, error) {
	return newRecoveredServiceAfterInstanceLock(ctx, deps, nil)
}

func newRecoveredServiceAfterInstanceLock(ctx context.Context, deps appservice.Dependencies, acquireInstance func(*appservice.Service) error) (*appservice.Service, error) {
	service := appservice.NewService(ctx, deps)
	if acquireInstance != nil {
		if err := acquireInstance(service); err != nil {
			return nil, fmt.Errorf("acquire application instance lock: %w", err)
		}
	}
	if err := service.Recover(ctx); err != nil {
		return nil, fmt.Errorf("recover application sessions: %w", err)
	}
	if err := appservice.RecoverScheduleJobs(service); err != nil {
		return nil, fmt.Errorf("recover application jobs: %w", err)
	}
	return service, nil
}

func run() error {
	appCtx, cancel := context.WithCancel(context.Background())
	defer cancel()
	dataDir, lockID, err := resolveDataDir(os.Getenv("HARFLEX_DATA_DIR"), os.UserConfigDir)
	if err != nil {
		return err
	}
	store, err := openCatalog(appCtx, dataDir)
	if err != nil {
		return err
	}
	var service *appservice.Service
	var app *application.App
	var stopScheduler func()
	var closeOnce sync.Once
	shutdown := func() {
		closeOnce.Do(func() {
			if stopScheduler != nil {
				stopScheduler()
			}
			cancel()
			if service == nil {
				if err := store.Close(); err != nil {
					log.Print("close application catalog failed")
				}
				return
			}
			if err := appservice.Shutdown(service); err != nil {
				log.Print("application shutdown remains uncertain; durable recovery is required")
				return
			}
			if err := store.Close(); err != nil {
				log.Print("close application catalog failed")
			}
		})
	}
	service, err = newRecoveredServiceAfterInstanceLock(appCtx, appservice.Dependencies{
		Store: store, Secrets: secrets.NewKeyring("ai.harflex.desktop"),
		PrivateWorkspaceParent: dataDir, ExecutionCacheRoot: executionCacheRootFor(os.Getenv("HARFLEX_DATA_DIR"), dataDir),
	}, func(lockedService *appservice.Service) error {
		service = lockedService
		options := desktopOptions(service, shutdown)
		options.SingleInstance.UniqueID = lockID
		app = application.New(options)
		return nil
	})
	if err != nil {
		shutdown()
		return err
	}
	scheduler := appservice.StartScheduler(service)
	stopScheduler = scheduler.Stop
	defer shutdown()
	appservice.SetEmitter(service, func(name string, payload any) { app.Event.Emit(name, payload) })
	appservice.SetQuitHandler(service, app.Quit)
	app.Window.NewWithOptions(windowOptions())
	if err := app.Run(); err != nil {
		return fmt.Errorf("run desktop application: %w", err)
	}
	return nil
}
func main() {
	if err := run(); err != nil {
		log.Fatal(err)
	}
}
