// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Model {
    "id": string;
    "displayName": string;
    "backendId": string;
    "source": string;
    "availability": string;
    "loaded"?: boolean | null;
    "ownedBy"?: string;
    "contextLength"?: number;
    "supportedReasoningEfforts"?: string[] | null;
    "defaultReasoningEffort"?: string;
}

export interface Result {
    "backendId": string;
    "source": string;
    "destination": string;
    "profileRevision": string;
    "credentialToken"?: string;
    "searchTerm": string;
    "models": Model[] | null;
    "nextCursor": string;
    "checkedAt": string;
    "status": Status;
    "complete": boolean;
    "accountFiltered": boolean;
    "errorCode"?: string;
}

export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusComplete = "complete",
    StatusEmpty = "empty",
    StatusPartial = "partial",
    StatusInterrupted = "interrupted",
    StatusUnsupported = "unsupported",
    StatusFailed = "failed",
};
