// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agentcore$0 from "../agentcore/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as catalog$0 from "../catalog/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sddworkspace$0 from "../sddworkspace/models.js";

/**
 * APIModelSelectionInput binds an explicit catalog choice to admission. Public
 * session creation continues to use its existing legacy/default behavior.
 */
export interface APIModelSelectionInput {
    "executor": string;
    "backendId": string;
    "profileId": string;
    "modelId": string;
    "catalogRevision": string;
    "source": string;
    "destination": string;
    "checkedAt": string;
    "credentialToken": string;
    "reasoningEffort": string;
    "confirmUnverifiedManual": boolean;
    "confirmUnfiltered": boolean;
    "confirmJitLoad": boolean;
    "maxOutputTokens": number;
}

export interface AgentDTO {
    "id": string;
    "name": string;
    "description": string;
    "instructions": string;
    "backendId": string;
    "allowedTools": string[] | null;
    "createdAt": string;
    "updatedAt": string;
}

export interface AnswerBrainstormQuestionInput {
    "ref": BrainstormRequestInput;
    "questionId": string;
    "answer": string;
}

export interface ApprovalDTO {
    "approvalId": string;
    "toolCallId": string;
    "name": string;
    "risk": string;
    "arguments": json$0.RawMessage;
}

export interface ApprovalInput {
    "sessionId": string;
    "approvalId": string;
    "allow": boolean;
}

export interface ApproveBrainstormSynthesisInput {
    "ref": BrainstormRequestInput;
    "synthesisVersion": number;
}

export interface ApprovePipelineDesignInput {
    "ref": PipelineDesignRefInput;
    "digests": { [_ in string]?: string } | null;
}

export interface AuthoringCodeCopyPreparationDTO {
    "id": string;
    "pipelineId": string;
    "workspaceId": string;
    "requestId": string;
    "pipelineRevision": number;
    "codePreferenceRevision": number;
    "codeSelectionHash": string;
    "codePreference": AuthoringStageModelPreferenceDTO;
    "sourcePath": string;
    "privatePath": string;
    "manifest": sddworkspace$0.Manifest;
    "manifestHash": string;
    "status": string;
    "errorCode"?: string;
    "createdAt": string;
    "updatedAt": string;
}

export interface AuthoringCodeCopyPreparationsDTO {
    "pipelineId": string;
    "attemptCount": number;
    "maxAttemptCount": number;
    "attempts": AuthoringCodeCopyPreparationDTO[] | null;
}

export interface AuthoringCodeDecisionDTO {
    "pipelineId": string;
    "pipelineRevision": number;
    "runId": string;
    "requestId": string;
    "action": string;
    "patchHash": string;
    "baselineHash": string;
    "sourceManifestHash": string;
    "resultManifestHash": string;
    "feedback": string;
    "actor": string;
    "resultPipelineRevision": number;
    "createdAt": string;
}

/**
 * AuthoringCodePreflightDTO contains only local metadata required for a human
 * to review a future private copy and bind the next call to this snapshot.
 */
export interface AuthoringCodePreflightDTO {
    "pipelineId": string;
    "workspaceId": string;
    "pipelineRevision": number;
    "codePreferenceRevision": number;
    "codePreference": AuthoringStageModelPreferenceDTO;
    "sourcePath": string;
    "privateParentPath": string;
    "manifest": sddworkspace$0.Manifest;
    "manifestHash": string;
    "codeSelectionHash": string;
}

export interface AuthoringCodeRunDTO {
    "id": string;
    "pipelineId": string;
    "preparationId": string;
    "preparationRequestId": string;
    "requestId": string;
    "pipelineRevision": number;
    "planStageRevision": number;
    "planArtifactVersion": number;
    "codePreferenceRevision": number;
    "codeSelectionHash": string;
    "manifestHash": string;
    "planSourceHash": string;
    "privatePath": string;
    "preference": AuthoringStageModelPreferenceDTO;
    "limits": AuthoringCodeRunLimitsDTO;
    "sessionId": string;
    "status": string;
    "errorCode"?: string;
    "cancellationPending": boolean;
    "usage": catalog$0.BrainstormUsage | null;
    "baseline": sddworkspace$0.Manifest;
    "result"?: sddworkspace$0.Manifest | null;
    "sourceManifest"?: sddworkspace$0.Manifest | null;
    "sourceDrift": boolean;
    "sourceReadbackStatus": string;
    "changes": sddworkspace$0.Change[] | null;
    "patchHash": string;
    "createdAt": string;
    "updatedAt": string;
}

export interface AuthoringCodeRunLimitsDTO {
    "maxPromptBytes": number;
    "maxOutputTokens": number;
    "maxOutputTokensPerTurn": number;
    "maxTurns": number;
    "maxToolCalls": number;
    "timeoutMillis": number;
}

/**
 * AuthoringCodeRunPatchPageDTO streams the exact persisted canonical patch in
 * bounded UTF-8 slices. Every page repeats all snapshot bindings for readback.
 */
export interface AuthoringCodeRunPatchPageDTO {
    "pipelineId": string;
    "runId": string;
    "baselineHash": string;
    "sourceManifestHash": string;
    "resultManifestHash": string;
    "patchHash": string;
    "sourceReadbackStatus": string;
    "cursor": number;
    "nextCursor": number | null;
    "totalBytes": number;
    "content": string;
}

export interface AuthoringCodeRunsDTO {
    "pipelineId": string;
    "runs": AuthoringCodeRunDTO[] | null;
}

export interface AuthoringModelConsentBindingInput {
    "backendId": string;
    "modelId": string;
    "catalogRevision": string;
    "source": string;
    "destination": string;
}

export interface AuthoringStageActionDTO {
    "requestId": string;
    "action": string;
    "actor": string;
    "artifactVersion": number;
    "feedback": string;
    "reason": string;
    "attemptId": string;
    "resultStageRevision": number;
    "resultPipelineRevision": number;
    "createdAt": string;
}

export interface AuthoringStageArtifactDTO {
    "version": number;
    "content": json$0.RawMessage;
    "contentHash": string;
    "author": string;
    "attemptId": string;
    "sourceSessionId": string;
    "status": string;
    "createdAt": string;
    "updatedAt": string;
}

export interface AuthoringStageAttemptDTO {
    "id": string;
    "requestId": string;
    "artifactVersion": number;
    "status": string;
    "sessionId": string;
    "errorCode": string;
    "cancellationState": string;
    "modelMode": string;
    "effortMode": string;
    "preferenceSource": string;
    "preferenceRevision": number;
    "source": AuthoringStageSourceDTO;
    "selection": BrainstormSelectionDTO;
    "reservedInputTokens": number;
    "reservedOutputTokens": number;
    "usage": catalog$0.BrainstormUsage | null;
    "createdAt": string;
    "updatedAt": string;
}

export interface AuthoringStageDTO {
    "pipelineId": string;
    "stage": string;
    "pipelineRevision": number;
    "discoveryVersion": number;
    "revision": number;
    "state": string;
    "cancellationPending": boolean;
    "cancellationAttemptId": string;
    "artifactVersion": number;
    "attemptCount": number;
    "inputBudgetRemaining": number;
    "outputBudgetRemaining": number;
    "attempts": AuthoringStageAttemptDTO[] | null;
    "artifacts": AuthoringStageArtifactDTO[] | null;
    "actions": AuthoringStageActionDTO[] | null;
    "createdAt": string;
    "updatedAt": string;
}

export interface AuthoringStageDecisionInput {
    "ref": AuthoringStageRefInput;
    "reason": string;
    "attemptId": string;
}

export interface AuthoringStageModelPreferenceDTO {
    "pipelineId": string;
    "stage": string;
    "modelMode": string;
    "effortMode": string;
    "explicitEffort": string;
    "preferenceRevision": number;
    "resolution": string;
    "modelSource": string;
    "effortSource": string;
    "inheritedFrom": string;
    "catalogValidationRequired": boolean;
    "errorCode": string;
    "selection": BrainstormSelectionDTO;
}

export interface AuthoringStageRefInput {
    "pipelineId": string;
    "stage": string;
    "requestId": string;
    "pipelineRevision": number;
    "stageRevision": number;
    "discoveryVersion": number;
    "artifactVersion": number;
}

export interface AuthoringStageSourceDTO {
    "discoveryVersion": number;
    "discoveryHash": string;
    "brainstormRunId": string;
    "synthesisVersion": number;
    "discoveryBypassReason": string;
    "specVersion": number;
    "specHash": string;
    "specBypassReason": string;
    "previousArtifactVersion": number;
    "feedback": string;
}

export interface BackendDTO {
    "id": string;
    "name": string;
    "kind": string;
    "available": boolean;
    "professionalAvailable"?: boolean;
    "capabilities": agentcore$0.Capabilities;
}

export interface BrainstormAttemptDTO {
    "id": string;
    "requestId": string;
    "kind": string;
    "status": string;
    "sessionId": string;
    "errorCode": string;
    "discoveryVersion": number;
    "synthesisVersion": number;
    "selection": BrainstormSelectionDTO;
    "reservedInputTokens": number;
    "reservedOutputTokens": number;
    "usage": catalog$0.BrainstormUsage | null;
    "createdAt": string;
    "updatedAt": string;
}

export interface BrainstormDTO {
    "id": string;
    "pipelineId": string;
    "pipelineRevision": number;
    "discoveryVersion": number;
    "discoveryContent": string;
    "selection": BrainstormSelectionDTO;
    "state": string;
    "revision": number;
    "questionCount": number;
    "currentQuestionId": string;
    "synthesisVersion": number;
    "attemptCount": number;
    "inputBudgetRemaining": number;
    "outputBudgetRemaining": number;
    "activeDurationMillis": number;
    "createdAt": string;
    "updatedAt": string;
    "attempts": BrainstormAttemptDTO[] | null;
    "turns": BrainstormTurnDTO[] | null;
    "syntheses": BrainstormSynthesisDTO[] | null;
    "humanActions": catalog$0.BrainstormHumanAction[] | null;
}

export interface BrainstormRequestInput {
    "runId": string;
    "requestId": string;
    "pipelineRevision": number;
    "runRevision": number;
    "discoveryVersion": number;
}

export interface BrainstormSelectionDTO {
    "executor": string;
    "backendId": string;
    "modelId": string;
    "reasoningEffort": string;
    "supportedReasoningEfforts": string[] | null;
    "catalogRevision": string;
    "source": string;
    "destination": string;
    "status": string;
    "confirmUnfiltered": boolean;
    "confirmJitLoad": boolean;
    "maxOutputTokens": number;
    "contextLength": number;
    "executableVersion": string;
    "workspacePath": string;
    "checkedAt": string;
}

export interface BrainstormSynthesisDTO {
    "version": number;
    "discoveryVersion": number;
    "content": catalog$0.BrainstormSynthesisContent;
    "sourceSessionId": string;
    "status": string;
    "createdAt": string;
}

export interface BrainstormTurnDTO {
    "number": number;
    "questionId": string;
    "question": string;
    "answer": string;
    "sourceSessionId": string;
    "status": string;
    "createdAt": string;
    "updatedAt": string;
}

export interface CLIModelCatalogQuery {
    "workspaceId": string;
    "backendId": string;
}

export interface CancelAuthoringCodeInput {
    "pipelineId": string;
    "attemptId": string;
}

export interface CancelBrainstormAttemptInput {
    "ref": BrainstormRequestInput;
    "attemptId": string;
}

export interface CancelPipelineDesignInput {
    "pipelineId": string;
    "attemptId": string;
}

export interface ChannelImportDTO {
    "channel": LocalChannelDTO;
    "imported": number;
    "failed": number;
}

export interface ChannelMessageDTO {
    "id": string;
    "channelId": string;
    "direction": string;
    "fileName": string;
    "content": string;
    "status": string;
    "errorCode": string;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * ChatProjectDTO is one project of the Casual sidebar with its most recent conversations. Total counts the project's
 * conversations, so the sidebar can offer the rest; pinned ones are always included.
 */
export interface ChatProjectDTO {
    "workspace": WorkspaceSummaryDTO;
    "chats": SessionDTO[] | null;
    "total": number;
}

export interface CreateAuthoringPipelineInput {
    "workspaceId": string;
    "requestId": string;
    "discovery": string;
}

export interface CreateDirectSessionInput {
    "workspaceId": string;
    "backendId": string;
    "agentId": string;
    "reason": string;
    "modelId": string;
    "reasoningEffort": string;
    "catalogRevision": string;
}

export interface CreatePipelineInput {
    "workspaceId": string;
    "title": string;
    "objective": string;
}

export interface CreatePipelineSessionInput {
    "pipelineId": string;
    "backendId": string;
    "role": string;
    "selection"?: APIModelSelectionInput | null;
    "confirmWorkspaceCopy"?: boolean;

    /**
     * ContinuePreviousCopy keeps a Coder fix round in the previous Coder's private copy.
     */
    "continuePreviousCopy"?: boolean;
}

export interface CreateSessionInput {
    "workspaceId": string;
    "backendId": string;
    "agentId": string;
    "mode": string;
    "bypassReason": string;
    "modelId": string;
    "reasoningEffort": string;
    "catalogRevision": string;
}

export interface CredentialProbeDTO {
    "status": string;
    "checked": number;
    "missing": number;
}

export interface DecideAuthoringCodeInput {
    "pipelineId": string;
    "pipelineRevision": number;
    "runId": string;
    "requestId": string;
    "action": string;
    "patchHash": string;
    "baselineHash": string;
    "sourceManifestHash": string;
    "resultManifestHash": string;
    "feedback": string;
}

export interface DecidePipelineExecutionArtifactInput {
    "pipelineId": string;
    "requestId": string;
    "stage": string;
    "artifactVersion": number;
    "artifactDigest": string;
    "decision": string;
    "feedback": string;
    "pipelineRevision": number;
}

export interface DelegateToAgentInput {
    "parentSessionId": string;
    "agentId": string;
    "requestId": string;
    "prompt": string;
}

export interface DelegatedSessionDTO {
    "session": SessionDTO;
    "prompt": string;
    "depth": number;
    "created": boolean;
}

export interface DelegationDTO {
    "id": string;
    "parentSessionId": string;
    "childSessionId": string;
    "agentId": string;
    "taskPrompt": string;
    "promptCount": number;
    "promptLimit": number;
    "timeoutSeconds": number;
    "depth": number;
    "createdAt": string;
    "status": string;
    "result": string;
    "errorCode": string;
}

export interface DeleteWorktreeInput {
    "workspaceId": string;
    "path": string;
    "deleteBranch": boolean;
    "acknowledgeIgnored": boolean;
}

export interface DeleteWorktreeResultDTO {
    "path": string;
    "branch": string;
    "removed": boolean;
    "branchDeleted": boolean;
    "list": WorktreeListDTO;
}

export interface DeriveAuthoringPipelineInput {
    "parentPipelineId": string;
    "requestId": string;
    "expectedRevision": number;
    "discovery": string;
}

export interface EditPipelineDesignDocumentInput {
    "ref": PipelineDesignRefInput;
    "stage": string;
    "content": string;
}

/**
 * EnsureWorkChatsResult is the works with a chat, and how many chats this pass created.
 */
export interface EnsureWorkChatsResult {
    "coordinators": WorkCoordinatorDTO[] | null;
    "created": number;
}

export interface EventDTO {
    "id": string;
    "streamId": string;
    "sequence": number;
    "type": string;
    "data": json$0.RawMessage;
    "createdAt": string;
}

export interface ExportAuditInput {
    "sessionId": string;
    "destination": string;
}

export interface FinishPipelinePRsInput {
    "pipelineId": string;

    /**
     * Outcome is "completed" (the agent reported its pull requests) or "skipped".
     */
    "outcome": string;
    "reason"?: string;
}

export interface FixPipelineFindingsInput {
    "pipelineId": string;
    "findings": string[] | null;
    "improvements": string[] | null;
    "note": string;
    "coder": PipelineRoleChoice;
    "evaluator": PipelineRoleChoice;
}

export interface GenerateAuthoringStageInput {
    "ref": AuthoringStageRefInput;
    "selection": APIModelSelectionInput;
    "feedback": string;
    "confirmUnfiltered": boolean;
    "confirmJitLoad": boolean;
    "consentBinding"?: AuthoringModelConsentBindingInput | null;
}

export interface GenerateBrainstormInput {
    "ref": BrainstormRequestInput;
    "selection": APIModelSelectionInput;
}

export interface GetAuthoringCodeCopyPreparationsInput {
    "pipelineId": string;
}

export interface GetAuthoringCodeRunPatchInput {
    "pipelineId": string;
    "runId": string;
    "cursor": number;
}

export interface GetAuthoringCodeRunsInput {
    "pipelineId": string;
}

export interface GetAuthoringStageInput {
    "pipelineId": string;
    "stage": string;
}

export interface GetAuthoringStageModelPreferenceInput {
    "pipelineId": string;
    "stage": string;
}

export interface GetBrainstormingInput {
    "runId": string;
    "pipelineId": string;
    "discoveryVersion": number;
}

export interface GetPipelineForSessionInput {
    "sessionId": string;
    "workspaceId": string;
}

/**
 * HTTPModelCatalogDraft carries an unsaved, one-shot key. QueryHTTPModelCatalog
 * clears APIKey on return and never caches draft catalog results.
 */
export interface HTTPModelCatalogDraft {
    "providerType": string;
    "baseUrl": string;
    "apiKey": string;
}

export interface HTTPModelCatalogQuery {
    "profileId": string;
    "searchTerm": string;
    "refresh": boolean;
    "draft"?: HTTPModelCatalogDraft | null;
}

export interface ImportKnowledgeInput {
    "workspaceId": string;
    "path": string;
}

export interface ImportSkillInput {
    "workspaceId": string;
    "path": string;
    "enabled": boolean;
}

export interface IndexKnowledgeVectorsInput {
    "workspaceId": string;
    "expectedFingerprint": string;
}

export interface KnowledgeDocumentDTO {
    "id": string;
    "workspaceId": string;
    "path": string;
    "sourceSize": number;
    "sourceModifiedAt": string;
    "indexedAt": string;
    "chunkCount": number;
}

export interface KnowledgeDocumentInput {
    "workspaceId": string;
    "documentId": string;
}

export interface KnowledgeEmbeddingProfileDTO {
    "configured": boolean;
    "kind": string;
    "baseUrl": string;
    "model": string;
    "fingerprint": string;
    "progress": {"total": number, "indexed": number, "dimension": number};
}

export interface KnowledgeHitDTO {
    "documentId": string;
    "path": string;
    "lineStart": number;
    "snippet": string;
    "sourceModifiedAt": string;
    "indexedAt": string;
}

export interface KnowledgeSearchDTO {
    "mode": string;
    "hits": KnowledgeHitDTO[] | null;
}

export interface ListBrainstormingInput {
    "pipelineId": string;
    "workspaceId": string;
    "limit": number;
}

export interface ListChatProjectsInput {
    /**
     * PerProject is how many recent conversations each project brings; zero means the default.
     */
    "perProject": number;
}

export interface ListEventsInput {
    "sessionId": string;
    "afterSequence": number;
    "limit": number;
}

export interface ListLogEventsInput {
    "workspaceId": string;
    "type": string;
    "beforeId": number;
    "limit": number;
}

export interface ListSessionsInput {
    "workspaceId": string;
}

export interface LocalChannelDTO {
    "id": string;
    "workspaceId": string;
    "name": string;
    "folder": string;
    "status": string;
    "lastError": string;
    "createdAt": string;
    "updatedAt": string;
}

export interface LogEntryDTO {
    "cursor": number;
    "id": string;
    "sessionId": string;
    "workspaceId": string;
    "sequence": number;
    "type": string;
    "createdAt": string;
}

export interface MCPServerDTO {
    "id": string;
    "workspaceId": string;
    "name": string;
    "transport": string;
    "command": string;
    "args": string[] | null;
    "url": string;
    "tokenEnvVar": string;
    "authScheme": string;
    "enabled": boolean;
    "tools": MCPToolDTO[] | null;
    "hasCredential": boolean;
    "createdAt": string;
    "updatedAt": string;
}

export interface MCPToolDTO {
    "name": string;
    "agentName": string;
    "description": string;
    "schema": json$0.RawMessage;
}

/**
 * OpenRouterManagementKeyStatus never contains credential bytes. Usable means
 * the stored reference still matches the allowed profile origin and type.
 */
export interface OpenRouterManagementKeyStatus {
    "profileId": string;
    "origin": string;
    "configured": boolean;
    "usable": boolean;
    "updatedAt": string;
}

export interface OpenSessionInput {
    "sessionId": string;
    "workspaceId": string;
}

export interface PipelineArchivedArtifactDTO {
    "stage": string;
    "version": number;
    "content": string;
    "author": string;
    "sourceSessionId": string;
    "contentDigest": string;
    "reason": string;
    "createdAt": string;
}

export interface PipelineArtifactDTO {
    "stage": string;
    "version": number;
    "content": string;
    "author": string;
    "sourceSessionId": string;
    "contentDigest"?: string;
    "reviewStatus"?: string;
    "reviewActor"?: string;
    "reviewFeedback"?: string;
    "reviewedAt"?: string;
    "updatedAt": string;
}

export interface PipelineCodeCopyPreviewDTO {
    "isGit": boolean;
    "fileCount": number;
    "totalBytes": number;
    "excludedPaths": string[] | null;
    "unsafePaths": string[] | null;
}

export interface PipelineDTO {
    "id": string;
    "workspaceId": string;
    "kind": string;
    "preparationExperience"?: string;
    "derivedFromPipelineId": string;
    "discoveryFrozenVersion": number;
    "title": string;
    "objective": string;
    "currentStage": string;
    "stageStatus": { [_ in string]?: string } | null;
    "revision": number;
    "artifacts": { [_ in string]?: PipelineArtifactDTO } | null;
    "archivedArtifacts"?: PipelineArchivedArtifactDTO[] | null;
    "executionReviews"?: PipelineExecutionReviewDTO[] | null;
    "codeAppliedAt"?: string | null;

    /**
     * an isolated Code run's approved patch has not reached the project folder yet
     */
    "codePatchPending"?: boolean;
    "codeReviewRecoveryStatus"?: string;
    "codeReviewRecoveryReason"?: string;
    "createdAt": string;
    "updatedAt": string;
}

export interface PipelineDesignAttemptDTO {
    "id": string;
    "requestId": string;
    "target": string;
    "status": string;
    "phase": string;
    "selections": { [_ in string]?: BrainstormSelectionDTO } | null;
    "sessionIds": { [_ in string]?: string } | null;
    "errorCode": string;
    "createdAt": string;
    "updatedAt": string;
}

export interface PipelineDesignDTO {
    "pipelineId": string;
    "workspaceId": string;
    "pipelineRevision": number;
    "currentPipelineRevision": number;
    "revision": number;
    "state": string;
    "phase": string;
    "activeAttemptId": string;
    "needsDerivation": boolean;
    "documents": { [_ in string]?: PipelineDesignDocumentDTO } | null;
    "versions": { [_ in string]?: PipelineDesignVersionDTO[] | null } | null;
    "messages": catalog$0.PipelineDesignMessage[] | null;
    "attempts": PipelineDesignAttemptDTO[] | null;
    "createdAt": string;
    "updatedAt": string;
}

export interface PipelineDesignDocumentDTO {
    "stage": string;
    "version": number;
    "content": string;
    "contentDigest": string;
    "author": string;
    "sourceSessionId": string;
    "sourceDigest": string;
    "selection"?: BrainstormSelectionDTO | null;
    "stale": boolean;
    "updatedAt": string;
}

export interface PipelineDesignRefInput {
    "pipelineId": string;
    "requestId": string;
    "pipelineRevision": number;
    "designRevision": number;
}

export interface PipelineDesignVersionDTO {
    "stage": string;
    "version": number;
    "content": string;
    "contentDigest": string;
    "author": string;
    "sourceSessionId": string;
    "sourceDigest": string;
    "selection"?: BrainstormSelectionDTO | null;
    "stale": boolean;
    "updatedAt": string;
    "reason": string;
    "restoredFromVersion": number;
    "createdAt": string;
}

export interface PipelineExecutionReviewDTO {
    "stage": string;
    "version": number;
    "content": string;
    "contentDigest": string;
    "sourceSessionId": string;
    "decision": string;
    "actor": string;
    "feedback": string;
    "createdAt": string;
}

export interface PipelineRoleChoice {
    "backendId": string;
    "selection"?: APIModelSelectionInput | null;
}

export interface PipelineSessionDTO {
    "session": SessionDTO;
    "prompt": string;
    "role": string;
}

export interface PipelineStageActivityDTO {
    "pipelineId": string;
    "workspaceId": string;
    "stage": string;
    "status": string;
    "phase": string;
    "sessionId": string;
    "modelId": string;
    "attemptStatus"?: string;
    "errorCode"?: string;
    "updatedAt": string;
}

export interface PreflightAuthoringCodeInput {
    "pipelineId": string;
    "expectedPipelineRevision": number;
    "expectedCodePreferenceRevision": number;
}

export interface PrepareAuthoringCodeInput {
    "pipelineId": string;
    "requestId": string;
    "expectedPipelineRevision": number;
    "expectedCodePreferenceRevision": number;
    "expectedCodeSelectionHash": string;
    "expectedManifestHash": string;
    "confirmCopy": boolean;
}

export interface PreparePipelineDesignInput {
    "ref": PipelineDesignRefInput;
    "message": string;
    "target": string;
    "selections"?: { [_ in string]?: APIModelSelectionInput } | null;
}

export interface PrepareWorktreeSaveInput {
    "workspaceId": string;
    "path": string;
}

/**
 * ProjectMemoryDTO is what the Harflex knows about a project. An empty Status means it was never read nor asked about;
 * "declined" means the person chose not to have it read when asked.
 */
export interface ProjectMemoryDTO {
    "workspaceId": string;
    "status": string;
    "content": string;
    "sources": string[] | null;
    "backendId": string;
    "modelId": string;
    "errorCode"?: string;
    "edited": boolean;
    "updatedAt": string;
}

export interface PromptInput {
    "sessionId": string;
    "text": string;
}

export interface ProviderProfileDTO {
    "id": string;
    "name": string;
    "kind": string;
    "providerType": string;
    "baseUrl": string;
    "model": string;
    "hasCredential": boolean;
    "endpointBlocked": boolean;
    "updatedAt": string;
}

export interface PullRequestDTO {
    "id": string;
    "pipelineId": string;
    "sessionId": string;
    "url": string;
    "title": string;
    "branch": string;
    "state": string;
    "watch": boolean;
    "lastCheckedAt"?: string | null;
    "nextCheckAt"?: string | null;
    "checking": boolean;
    "timeline": PullRequestEventDTO[] | null;
}

export interface PullRequestEventDTO {
    "at": string;
    "kind": string;
    "summary": string;
}

/**
 * QALoopDTO is what the QA screen shows while QA or a fix round runs in the background.
 */
export interface QALoopDTO {
    "pipelineId": string;

    /**
     * qa, fixing, done, waiting, failed
     */
    "phase": string;
    "round": number;
    "message": string;
    "sessionId"?: string;
    "updatedAt": string;
    "running": boolean;
}

export interface ReopenPipelineCodeReviewInput {
    "pipelineId": string;
    "artifactVersion": number;
    "artifactDigest": string;
    "pipelineRevision": number;
}

export interface RepositoryDTO {
    "isRepository": boolean;
    "root": string;
    "branch": string;
    "files": string[] | null;
    "stagedDiff": string;
    "unstagedDiff": string;
    "truncated": boolean;
}

export interface RequestBrainstormRevisionInput {
    "ref": BrainstormRequestInput;
    "synthesisVersion": number;
    "choice": string;
    "feedback": string;
}

export interface ResizeTerminalInput {
    "id": string;
    "cols": number;
    "rows": number;
}

export interface RestorePipelineDesignDocumentInput {
    "ref": PipelineDesignRefInput;
    "stage": string;
    "version": number;
}

export interface ResumePipelineFixesInput {
    "pipelineId": string;
    "coder": PipelineRoleChoice;
    "evaluator": PipelineRoleChoice;
}

export interface ResumeWorkflowRunInput {
    "runId": string;
    "reviewedSessionId": string;
    "choice": string;
}

export interface RetryChannelMessageInput {
    "channelId": string;
    "requestId": string;
}

export interface ReviseAuthoringDiscoveryInput {
    "pipelineId": string;
    "expectedRevision": number;
    "expectedVersion": number;
    "discovery": string;
}

export interface RunResultDTO {
    "status": string;
    "reason"?: string;
    "code"?: string;
    "approval"?: ApprovalDTO | null;
}

export interface SaveAgentInput {
    "id": string;
    "name": string;
    "description": string;
    "instructions": string;
    "backendId": string;
    "allowedTools": string[] | null;
}

export interface SaveAuthoringStageModelPreferenceInput {
    "pipelineId": string;
    "stage": string;
    "expectedRevision": number;
    "modelMode": string;
    "effortMode": string;
    "explicitEffort": string;
    "selection": APIModelSelectionInput;
}

export interface SaveKnowledgeEmbeddingProfileInput {
    "workspaceId": string;
    "kind": string;
    "baseUrl": string;
    "model": string;
}

export interface SaveLocalChannelInput {
    "id": string;
    "workspaceId": string;
    "name": string;
    "folder": string;
}

export interface SaveMCPServerInput {
    "id": string;
    "workspaceId": string;
    "name": string;
    "transport": string;
    "command": string;
    "args": string[] | null;
    "url": string;
    "tokenEnvVar": string;

    /**
     * AuthScheme is "bearer" (also the meaning of "") or "basic", where Token is "user:secret".
     */
    "authScheme": string;
    "token": string;
}

export interface SavePipelineArtifactInput {
    "pipelineId": string;
    "stage": string;
    "content": string;
}

export interface SaveProjectMemoryInput {
    "workspaceId": string;
    "content": string;
}

export interface SaveProviderProfileInput {
    "id": string;
    "name": string;
    "kind": string;
    "providerType": string;
    "baseUrl": string;
    "model": string;
    "apiKey": string;
    "clearCredential": boolean;
}

export interface SaveScheduleInput {
    "id": string;
    "workspaceId": string;
    "name": string;
    "targetKind": string;
    "workflowId": string;
    "backendId": string;
    "prompt": string;
    "frequency": string;
    "timezone": string;
    "localDate": string;
    "localTime": string;
    "missedPolicy": string;
    "enabled": boolean;
    "allowCli": boolean;
    "revision": number;
}

export interface SaveSettingsInput {
    "defaultBackendId": string;
    "defaultModelBackendId": string;
    "defaultModelId": string;
}

export interface SaveSkillInput {
    "id": string;
    "workspaceId": string;
    "name": string;
    "description": string;
    "content": string;
    "enabled": boolean;
}

export interface SaveStageExecutorInput {
    "workspaceId": string;
    "stage": string;
    "backendId": string;

    /**
     * ModelID is empty when the executor's own model is meant (the model of an API profile).
     */
    "modelId": string;
}

export interface SaveWorkflowInput {
    "id": string;
    "workspaceId": string;
    "name": string;
    "steps": WorkflowStepInput[] | null;
}

export interface ScheduleChangeDTO {
    "workspaceId": string;
}

export interface ScheduleDTO {
    "id": string;
    "workspaceId": string;
    "name": string;
    "targetKind": string;
    "workflowId": string;
    "backendId": string;
    "prompt": string;
    "frequency": string;
    "timezone": string;
    "localDate": string;
    "localTime": string;
    "missedPolicy": string;
    "enabled": boolean;
    "allowCli": boolean;
    "nextRunAt": string | null;
    "revision": number;
    "createdAt": string;
    "updatedAt": string;
}

export interface ScheduleJobDTO {
    "id": string;
    "scheduleId": string;
    "workspaceId": string;
    "trigger": string;
    "status": string;
    "errorCode": string;
    "workflowRunId": string;
    "sessionId": string;
    "dueAt": string;
    "createdAt": string;
    "startedAt": string | null;
    "finishedAt": string | null;
}

export interface SearchKnowledgeInput {
    "workspaceId": string;
    "documentId": string;
    "query": string;
    "limit": number;
}

export interface SendChannelMessageInput {
    "channelId": string;
    "requestId": string;
    "content": string;
}

export interface SessionDTO {
    "id": string;
    "workspaceId": string;
    "backendId": string;
    "status": string;
    "createdAt": string;
    "updatedAt": string;
    "resumable": boolean;

    /**
     * Purpose separates user conversations ("chat") from the sessions the SDD creates for
     * itself ("preparation", "code", "evaluation"). Title previews a chat's first user message
     * (filled only by ListSessions, for the most recent chats) and names internal sessions.
     */
    "purpose"?: string;
    "title"?: string;

    /**
     * Pinned keeps the conversation at the top of the Casual sidebar (filled by ListChatProjects).
     */
    "pinned"?: boolean;
}

export interface SessionModelSelectionDTO {
    "sessionId": string;
    "backendId": string;
    "modelId": string;
    "reasoningEffort": string;
    "supportedReasoningEfforts"?: string[] | null;
    "source": string;
    "destination": string;
    "status": string;
    "confirmUnverifiedManual": boolean;
    "confirmUnfiltered": boolean;
    "confirmJitLoad": boolean;
    "maxOutputTokens": number;
    "contextLength": number;
    "checkedAt": string;
}

export interface SetPullRequestWatchInput {
    "id": string;
    "watch": boolean;
}

export interface SetSchedulePausedInput {
    "scheduleId": string;
    "paused": boolean;
    "revision": number;
}

export interface SetSessionPinnedInput {
    "sessionId": string;
    "pinned": boolean;
}

export interface SetWorkspaceArchivedInput {
    "workspaceId": string;
    "archived": boolean;
}

export interface SetWorkspaceProfileInput {
    "workspaceId": string;
    "profile": string;

    /**
     * ConfirmFullAccess must be true to save the full_access profile.
     */
    "confirmFullAccess": boolean;
}

export interface SettingsDTO {
    "defaultBackendId": string;
    "defaultModelBackendId": string;
    "defaultModelId": string;
}

export interface SkillDTO {
    "id": string;
    "workspaceId": string;
    "name": string;
    "description": string;
    "content": string;
    "enabled": boolean;
    "revision": number;
    "createdAt": string;
    "updatedAt": string;
}

export interface SkipBrainstormQuestionsInput {
    "ref": BrainstormRequestInput;
    "reason": string;
}

export interface SkipPipelineStageInput {
    "pipelineId": string;
    "reason": string;
}

/**
 * StageExecutorDTO is the executor a project chose for one phase of its pipelines.
 */
export interface StageExecutorDTO {
    "workspaceId": string;
    "stage": string;
    "backendId": string;
    "modelId": string;
    "updatedAt": string;
}

export interface StartAuthoringCodeInput {
    "pipelineId": string;
    "preparationId": string;
    "preparationRequestId": string;
    "requestId": string;
    "expectedPipelineRevision": number;
    "expectedPlanStageRevision": number;
    "expectedPlanArtifactVersion": number;
    "expectedCodePreferenceRevision": number;
    "expectedCodeSelectionHash": string;
    "expectedManifestHash": string;
}

export interface StartBrainstormingInput {
    "pipelineId": string;
    "requestId": string;
    "pipelineRevision": number;
    "discoveryVersion": number;
    "selection": APIModelSelectionInput;
}

export interface StartPipelineQAInput {
    "pipelineId": string;
    "evaluator": PipelineRoleChoice;
}

export interface StartTerminalInput {
    "workspaceId": string;
    "cols": number;
    "rows": number;
}

export interface StartWorkflowInput {
    "workflowId": string;
    "backendId": string;
}

export interface TerminalDTO {
    "id": string;
    "shell": string;
    "path": string;
}

/**
 * WorkCoordinatorDTO is an SDD work and the chat that coordinates it, as the Casual sidebar lists it.
 */
export interface WorkCoordinatorDTO {
    "sessionId": string;
    "pipelineId": string;
    "title": string;
    "currentStage": string;
    "stageStatus": { [_ in string]?: string } | null;
    "updatedAt": string;
}

export interface WorkflowDTO {
    "id": string;
    "workspaceId": string;
    "name": string;
    "steps": WorkflowStepInput[] | null;
    "revision": number;
    "createdAt": string;
    "updatedAt": string;
}

export interface WorkflowRunDTO {
    "id": string;
    "workflowId": string;
    "workspaceId": string;
    "backendId": string;
    "steps": WorkflowStepInput[] | null;
    "currentStep": number;
    "status": string;
    "lastSessionId": string;
    "createdAt": string;
    "updatedAt": string;
}

export interface WorkflowStepInput {
    "name": string;
    "prompt": string;
}

export interface WorkspaceDTO {
    "id": string;
    "path": string;
    "profile": string;
}

export interface WorkspaceSummaryDTO {
    "id": string;
    "path": string;
    "profile": string;
    "available": boolean;
    "archived": boolean;
}

export interface WorktreeBlockerDTO {
    "code": string;
    "detail": string;
    "count": number;
}

export interface WorktreeDTO {
    "path": string;
    "name": string;
    "branch": string;
    "head": string;
    "isMain": boolean;
    "isCurrent": boolean;
    "detached": boolean;
    "locked": boolean;
    "lockReason": string;
    "missing": boolean;
    "statusKnown": boolean;
    "staged": number;
    "unstaged": number;
    "untracked": number;
    "conflicts": number;
    "changed": number;
    "changedFiles": string[] | null;
    "changesTruncated": boolean;
    "operation": string;
    "ahead": number;
    "behind": number;
    "merged": boolean;
    "ignored": string[] | null;
    "ignoredMore": number;
    "canDelete": boolean;
    "blockers": WorktreeBlockerDTO[] | null;
    "canSaveWithAi": boolean;
    "saveBlockers": WorktreeBlockerDTO[] | null;
}

/**
 * WorktreeGroupDTO is the worktrees of one repository, reached from the projects that live in it. Actions on
 * these worktrees go through WorkspaceID, the project that stands for the repository.
 */
export interface WorktreeGroupDTO {
    "workspaceId": string;
    "name": string;
    "path": string;
    "projects": string[] | null;
    "list": WorktreeListDTO;
    "error"?: string;
}

export interface WorktreeListDTO {
    "isRepository": boolean;
    "root": string;
    "base": string;
    "baseKnown": boolean;
    "currentPath": string;
    "items": WorktreeDTO[] | null;
}

/**
 * WorktreeSavePlanDTO is everything the renderer needs to hand a worktree's pending work to the
 * assistant: the project it runs in (the main checkout), the reason that session records and
 * the instructions. The safety copy already exists when this is returned.
 */
export interface WorktreeSavePlanDTO {
    "workspace": WorkspaceDTO;
    "path": string;
    "branch": string;
    "base": string;
    "snapshotRef": string;
    "snapshotCommit": string;
    "hadPending": boolean;
    "reason": string;
    "prompt": string;
}

export interface WriteTerminalInput {
    "id": string;
    "data": string;
}
