// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as modelcatalog$0 from "../modelcatalog/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AdvancePipeline(id: string): $CancellablePromise<$models.PipelineDTO> {
    return $Call.ByID(2024343123, id);
}

export function AnswerBrainstormQuestion($in: $models.AnswerBrainstormQuestionInput): $CancellablePromise<$models.BrainstormDTO> {
    return $Call.ByID(3307937422, $in);
}

/**
 * ApplyPipelineCode applies only the exact Code snapshot that passed Eval. It
 * is a separate, explicit operation from both Code execution and Eval.
 */
export function ApplyPipelineCode(pipelineID: string): $CancellablePromise<$models.PipelineDTO> {
    return $Call.ByID(1942817068, pipelineID);
}

export function Approve($in: $models.ApprovalInput): $CancellablePromise<$models.RunResultDTO> {
    return $Call.ByID(998145074, $in);
}

export function ApproveAuthoringStage($in: $models.AuthoringStageDecisionInput): $CancellablePromise<$models.AuthoringStageDTO> {
    return $Call.ByID(2418181943, $in);
}

export function ApproveBrainstormSynthesis($in: $models.ApproveBrainstormSynthesisInput): $CancellablePromise<$models.BrainstormDTO> {
    return $Call.ByID(3022361363, $in);
}

export function ApprovePipelineDesign($in: $models.ApprovePipelineDesignInput): $CancellablePromise<$models.PipelineDTO> {
    return $Call.ByID(1345639922, $in);
}

export function Cancel(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2575874739, sessionID);
}

export function CancelAuthoringCode($in: $models.CancelAuthoringCodeInput): $CancellablePromise<$models.AuthoringCodeRunDTO> {
    return $Call.ByID(46627033, $in);
}

export function CancelAuthoringStage($in: $models.AuthoringStageDecisionInput): $CancellablePromise<$models.AuthoringStageDTO> {
    return $Call.ByID(3970748026, $in);
}

export function CancelBrainstormAttempt($in: $models.CancelBrainstormAttemptInput): $CancellablePromise<$models.BrainstormDTO> {
    return $Call.ByID(1455998775, $in);
}

export function CancelPipelineDesign($in: $models.CancelPipelineDesignInput): $CancellablePromise<$models.PipelineDesignDTO> {
    return $Call.ByID(1059020743, $in);
}

export function CancelScheduleJob(jobID: string): $CancellablePromise<$models.ScheduleJobDTO> {
    return $Call.ByID(3310498333, jobID);
}

/**
 * The GUI never automatically repeats a paused step because a tool may have
 * produced effects before a crash. The user must inspect the linked session.
 */
export function CancelWorkflowRun(runID: string): $CancellablePromise<$models.WorkflowRunDTO> {
    return $Call.ByID(2047938139, runID);
}

/**
 * CheckPullRequestNow asks the PRs conversation to look at the pull request now, whatever the watch's schedule.
 */
export function CheckPullRequestNow(prID: string): $CancellablePromise<$models.PullRequestDTO> {
    return $Call.ByID(2822119219, prID);
}

export function ClearOpenRouterManagementKey(profileID: string): $CancellablePromise<void> {
    return $Call.ByID(3728561383, profileID);
}

/**
 * ClearStageExecutor returns a phase to the default of Settings.
 */
export function ClearStageExecutor(workspaceID: string, stage: string): $CancellablePromise<void> {
    return $Call.ByID(3719651577, workspaceID, stage);
}

/**
 * CloseTerminal ends a terminal's shell.
 */
export function CloseTerminal(id: string): $CancellablePromise<void> {
    return $Call.ByID(2218649031, id);
}

export function CompletePipelineCode(pipelineID: string): $CancellablePromise<$models.PipelineDTO> {
    return $Call.ByID(2422352353, pipelineID);
}

export function CompletePipelineEvaluation(pipelineID: string): $CancellablePromise<$models.PipelineDTO> {
    return $Call.ByID(1247206798, pipelineID);
}

export function ConfirmDiscoveryAfterSkip($in: $models.BrainstormRequestInput): $CancellablePromise<$models.BrainstormDTO> {
    return $Call.ByID(2169036532, $in);
}

export function ConnectMCPServer(id: string): $CancellablePromise<$models.MCPServerDTO> {
    return $Call.ByID(9010868, id);
}

export function CreateAuthoringPipeline($in: $models.CreateAuthoringPipelineInput): $CancellablePromise<$models.PipelineDTO> {
    return $Call.ByID(2977356340, $in);
}

export function CreateDirectSession($in: $models.CreateDirectSessionInput): $CancellablePromise<$models.SessionDTO> {
    return $Call.ByID(2334984808, $in);
}

export function CreatePipeline($in: $models.CreatePipelineInput): $CancellablePromise<$models.PipelineDTO> {
    return $Call.ByID(2901807411, $in);
}

export function CreatePipelineSession($in: $models.CreatePipelineSessionInput): $CancellablePromise<$models.PipelineSessionDTO> {
    return $Call.ByID(396093117, $in);
}

export function CreateSession($in: $models.CreateSessionInput): $CancellablePromise<$models.SessionDTO> {
    return $Call.ByID(2623063847, $in);
}

export function DecideAuthoringCode($in: $models.DecideAuthoringCodeInput): $CancellablePromise<$models.AuthoringCodeDecisionDTO> {
    return $Call.ByID(2288461571, $in);
}

export function DecidePipelineExecutionArtifact($in: $models.DecidePipelineExecutionArtifactInput): $CancellablePromise<$models.PipelineDTO> {
    return $Call.ByID(1070123089, $in);
}

/**
 * DeclineProjectMemory records that the person chose not to have the project read now; the project stops asking.
 * A memory it already has is kept.
 */
export function DeclineProjectMemory(workspaceID: string): $CancellablePromise<$models.ProjectMemoryDTO> {
    return $Call.ByID(1785152773, workspaceID);
}

export function DelegateToAgent($in: $models.DelegateToAgentInput): $CancellablePromise<$models.DelegatedSessionDTO> {
    return $Call.ByID(4214068972, $in);
}

/**
 * DeleteWorktree removes one working tree after judging it again; the open project is never removed.
 */
export function DeleteWorktree($in: $models.DeleteWorktreeInput): $CancellablePromise<$models.DeleteWorktreeResultDTO> {
    return $Call.ByID(1171131611, $in);
}

export function DeriveAuthoringPipeline($in: $models.DeriveAuthoringPipelineInput): $CancellablePromise<$models.PipelineDTO> {
    return $Call.ByID(2076163793, $in);
}

export function DisableMCPServer(id: string): $CancellablePromise<$models.MCPServerDTO> {
    return $Call.ByID(882341454, id);
}

export function EditPipelineDesignDocument($in: $models.EditPipelineDesignDocumentInput): $CancellablePromise<$models.PipelineDesignDTO> {
    return $Call.ByID(419015364, $in);
}

export function ExportAudit($in: $models.ExportAuditInput): $CancellablePromise<string> {
    return $Call.ByID(3971937618, $in);
}

export function FinishAndGenerateSynthesis($in: $models.GenerateBrainstormInput): $CancellablePromise<$models.BrainstormDTO> {
    return $Call.ByID(4262024998, $in);
}

/**
 * FinishPipelinePRs ends the last stage of the pipeline. Completing it needs the agent's finished report; skipping
 * is the person's decision and needs nothing else.
 */
export function FinishPipelinePRs($in: $models.FinishPipelinePRsInput): $CancellablePromise<$models.PipelineDTO> {
    return $Call.ByID(3919396427, $in);
}

/**
 * FixPipelineFindings sends the chosen findings and improvements back to Code and runs the fix loop in the background.
 */
export function FixPipelineFindings($in: $models.FixPipelineFindingsInput): $CancellablePromise<$models.QALoopDTO> {
    return $Call.ByID(947039516, $in);
}

export function GenerateAuthoringStage($in: $models.GenerateAuthoringStageInput): $CancellablePromise<$models.AuthoringStageDTO> {
    return $Call.ByID(359350911, $in);
}

export function GenerateBrainstormQuestion($in: $models.GenerateBrainstormInput): $CancellablePromise<$models.BrainstormDTO> {
    return $Call.ByID(3372975339, $in);
}

export function GetAuthoringCodeCopyPreparations($in: $models.GetAuthoringCodeCopyPreparationsInput): $CancellablePromise<$models.AuthoringCodeCopyPreparationsDTO> {
    return $Call.ByID(1223889650, $in);
}

export function GetAuthoringCodeRunPatch($in: $models.GetAuthoringCodeRunPatchInput): $CancellablePromise<$models.AuthoringCodeRunPatchPageDTO> {
    return $Call.ByID(3751442824, $in);
}

export function GetAuthoringCodeRuns($in: $models.GetAuthoringCodeRunsInput): $CancellablePromise<$models.AuthoringCodeRunsDTO> {
    return $Call.ByID(603923555, $in);
}

export function GetAuthoringStage($in: $models.GetAuthoringStageInput): $CancellablePromise<$models.AuthoringStageDTO> {
    return $Call.ByID(3228218918, $in);
}

export function GetAuthoringStageModelPreference($in: $models.GetAuthoringStageModelPreferenceInput): $CancellablePromise<$models.AuthoringStageModelPreferenceDTO> {
    return $Call.ByID(6954646, $in);
}

export function GetBrainstorming($in: $models.GetBrainstormingInput): $CancellablePromise<$models.BrainstormDTO> {
    return $Call.ByID(2425147114, $in);
}

export function GetKnowledgeEmbeddingProfile(workspaceID: string): $CancellablePromise<$models.KnowledgeEmbeddingProfileDTO> {
    return $Call.ByID(3438757943, workspaceID);
}

export function GetOpenRouterManagementKeyStatus(profileID: string): $CancellablePromise<$models.OpenRouterManagementKeyStatus> {
    return $Call.ByID(3767257726, profileID);
}

export function GetParentDelegation(childSessionID: string): $CancellablePromise<$models.DelegationDTO | null> {
    return $Call.ByID(3840663781, childSessionID);
}

export function GetPipeline(id: string): $CancellablePromise<$models.PipelineDTO> {
    return $Call.ByID(1165862041, id);
}

export function GetPipelineForSession($in: $models.GetPipelineForSessionInput): $CancellablePromise<$models.PipelineDTO> {
    return $Call.ByID(1036757176, $in);
}

/**
 * GetPipelineQALoop returns the background QA state of a pipeline; Phase is empty when nothing ran since the app opened.
 */
export function GetPipelineQALoop(pipelineID: string): $CancellablePromise<$models.QALoopDTO> {
    return $Call.ByID(1916111129, pipelineID);
}

/**
 * Stage inspection reads durable ownership and never admits model inference.
 */
export function GetPipelineStageActivity(pipelineID: string, stage: string): $CancellablePromise<$models.PipelineStageActivityDTO> {
    return $Call.ByID(226327616, pipelineID, stage);
}

/**
 * GetProjectMemory returns what the Harflex knows about a project, or an empty status when it was never read.
 */
export function GetProjectMemory(workspaceID: string): $CancellablePromise<$models.ProjectMemoryDTO> {
    return $Call.ByID(624372063, workspaceID);
}

export function GetScheduleJob(jobID: string): $CancellablePromise<$models.ScheduleJobDTO> {
    return $Call.ByID(726306833, jobID);
}

export function GetSessionModelSelection(sessionID: string): $CancellablePromise<$models.SessionModelSelectionDTO> {
    return $Call.ByID(60985192, sessionID);
}

export function GetSettings(): $CancellablePromise<$models.SettingsDTO> {
    return $Call.ByID(1843825010);
}

export function GetWorkflowRun(id: string): $CancellablePromise<$models.WorkflowRunDTO> {
    return $Call.ByID(3316214303, id);
}

export function ImportChannelInbox(channelID: string): $CancellablePromise<$models.ChannelImportDTO> {
    return $Call.ByID(2192839693, channelID);
}

export function ImportKnowledge($in: $models.ImportKnowledgeInput): $CancellablePromise<$models.KnowledgeDocumentDTO> {
    return $Call.ByID(3485674568, $in);
}

export function ImportSkill($in: $models.ImportSkillInput): $CancellablePromise<$models.SkillDTO> {
    return $Call.ByID(1393797681, $in);
}

/**
 * Each explicit call commits at most one small batch. Persisted vectors are the resume checkpoint.
 */
export function IndexKnowledgeVectors($in: $models.IndexKnowledgeVectorsInput): $CancellablePromise<$models.KnowledgeEmbeddingProfileDTO> {
    return $Call.ByID(733315583, $in);
}

export function InspectRepository(workspaceID: string): $CancellablePromise<$models.RepositoryDTO> {
    return $Call.ByID(4268642819, workspaceID);
}

export function ListAgents(): $CancellablePromise<$models.AgentDTO[] | null> {
    return $Call.ByID(3612594675);
}

/**
 * ListAllWorktrees judges the worktrees of every repository among the active projects, one group per repository.
 * Archived projects and folders that moved are left out; a repository that cannot be read says so in its group.
 */
export function ListAllWorktrees(): $CancellablePromise<$models.WorktreeGroupDTO[] | null> {
    return $Call.ByID(3288370346);
}

export function ListBackends(): $CancellablePromise<$models.BackendDTO[] | null> {
    return $Call.ByID(2435670944);
}

export function ListBrainstorming($in: $models.ListBrainstormingInput): $CancellablePromise<$models.BrainstormDTO[] | null> {
    return $Call.ByID(3216560384, $in);
}

export function ListChannelMessages(channelID: string): $CancellablePromise<$models.ChannelMessageDTO[] | null> {
    return $Call.ByID(2075117788, channelID);
}

/**
 * ListChatProjects returns every active project (archived ones are left out) with its recent conversations, most
 * recently opened project first.
 */
export function ListChatProjects($in: $models.ListChatProjectsInput): $CancellablePromise<$models.ChatProjectDTO[] | null> {
    return $Call.ByID(2123786533, $in);
}

export function ListDelegations(parentSessionID: string): $CancellablePromise<$models.DelegationDTO[] | null> {
    return $Call.ByID(4109445552, parentSessionID);
}

export function ListEvents($in: $models.ListEventsInput): $CancellablePromise<$models.EventDTO[] | null> {
    return $Call.ByID(3802611200, $in);
}

export function ListKnowledge(workspaceID: string): $CancellablePromise<$models.KnowledgeDocumentDTO[] | null> {
    return $Call.ByID(87882247, workspaceID);
}

export function ListLocalChannels(workspaceID: string): $CancellablePromise<$models.LocalChannelDTO[] | null> {
    return $Call.ByID(2746197140, workspaceID);
}

export function ListLogEvents($in: $models.ListLogEventsInput): $CancellablePromise<$models.LogEntryDTO[] | null> {
    return $Call.ByID(2452837668, $in);
}

export function ListMCPServers(workspaceID: string): $CancellablePromise<$models.MCPServerDTO[] | null> {
    return $Call.ByID(908095677, workspaceID);
}

/**
 * ListPipelinePullRequests returns the pull requests the PRs conversation opened for a pipeline.
 */
export function ListPipelinePullRequests(pipelineID: string): $CancellablePromise<$models.PullRequestDTO[] | null> {
    return $Call.ByID(1159547374, pipelineID);
}

export function ListPipelines(workspaceID: string): $CancellablePromise<$models.PipelineDTO[] | null> {
    return $Call.ByID(1318066108, workspaceID);
}

export function ListProviderProfiles(): $CancellablePromise<$models.ProviderProfileDTO[] | null> {
    return $Call.ByID(1228489538);
}

export function ListScheduleJobs(workspaceID: string): $CancellablePromise<$models.ScheduleJobDTO[] | null> {
    return $Call.ByID(526981384, workspaceID);
}

export function ListSchedules(workspaceID: string): $CancellablePromise<$models.ScheduleDTO[] | null> {
    return $Call.ByID(3390129121, workspaceID);
}

export function ListSessions($in: $models.ListSessionsInput): $CancellablePromise<$models.SessionDTO[] | null> {
    return $Call.ByID(3011443672, $in);
}

export function ListSkills(workspaceID: string): $CancellablePromise<$models.SkillDTO[] | null> {
    return $Call.ByID(3595274019, workspaceID);
}

/**
 * ListStageExecutors returns the phases of a project that have an executor of their own; the others use the default
 * of Settings.
 */
export function ListStageExecutors(workspaceID: string): $CancellablePromise<$models.StageExecutorDTO[] | null> {
    return $Call.ByID(54221193, workspaceID);
}

export function ListWorkflowRuns(workspaceID: string): $CancellablePromise<$models.WorkflowRunDTO[] | null> {
    return $Call.ByID(4239914286, workspaceID);
}

export function ListWorkflows(workspaceID: string): $CancellablePromise<$models.WorkflowDTO[] | null> {
    return $Call.ByID(3888582605, workspaceID);
}

export function ListWorkspaces(): $CancellablePromise<$models.WorkspaceSummaryDTO[] | null> {
    return $Call.ByID(402061499);
}

/**
 * ListWorktrees judges every working tree of the project's repository and says, for each one,
 * whether deleting it would lose anything.
 */
export function ListWorktrees(workspaceID: string): $CancellablePromise<$models.WorktreeListDTO> {
    return $Call.ByID(1992704597, workspaceID);
}

export function OpenPipelineDesign(pipelineID: string): $CancellablePromise<$models.PipelineDesignDTO> {
    return $Call.ByID(2148245789, pipelineID);
}

export function OpenSession($in: $models.OpenSessionInput): $CancellablePromise<$models.SessionDTO> {
    return $Call.ByID(322307075, $in);
}

export function OpenWorkspace(path: string): $CancellablePromise<$models.WorkspaceDTO> {
    return $Call.ByID(1221526498, path);
}

export function PreflightAuthoringCode($in: $models.PreflightAuthoringCodeInput): $CancellablePromise<$models.AuthoringCodePreflightDTO> {
    return $Call.ByID(513313784, $in);
}

export function PrepareAuthoringCode($in: $models.PrepareAuthoringCodeInput): $CancellablePromise<$models.AuthoringCodeCopyPreparationDTO> {
    return $Call.ByID(1960588880, $in);
}

export function PreparePipelineDesign($in: $models.PreparePipelineDesignInput): $CancellablePromise<$models.PipelineDesignDTO> {
    return $Call.ByID(2822363412, $in);
}

/**
 * PrepareWorktreeSave keeps a copy of everything the worktree holds, then returns what the
 * assistant needs to commit it and merge it into the base branch. Deleting stays a separate,
 * re-checked step, so the assistant's work is verified rather than trusted.
 */
export function PrepareWorktreeSave($in: $models.PrepareWorktreeSaveInput): $CancellablePromise<$models.WorktreeSavePlanDTO> {
    return $Call.ByID(1515961084, $in);
}

export function PreviewPipelineCodeWorkspace(workspaceID: string): $CancellablePromise<$models.PipelineCodeCopyPreviewDTO> {
    return $Call.ByID(1245575517, workspaceID);
}

/**
 * ProbeCredentialStore reads only active credential references. It never returns values.
 */
export function ProbeCredentialStore(workspaceID: string): $CancellablePromise<$models.CredentialProbeDTO> {
    return $Call.ByID(3882790333, workspaceID);
}

/**
 * Prompt blocks for the whole run while events stream through the emitter.
 */
export function Prompt($in: $models.PromptInput): $CancellablePromise<$models.RunResultDTO> {
    return $Call.ByID(1779786931, $in);
}

/**
 * PruneWorktrees forgets entries whose folder no longer exists and returns the refreshed list.
 */
export function PruneWorktrees(workspaceID: string): $CancellablePromise<$models.WorktreeListDTO> {
    return $Call.ByID(3098834591, workspaceID);
}

/**
 * QueryCLIModelCatalog is an explicit, read-only discovery action scoped to a
 * registered workspace. A model list is never treated as execution approval.
 */
export function QueryCLIModelCatalog($in: $models.CLIModelCatalogQuery): $CancellablePromise<modelcatalog$0.Result> {
    return $Call.ByID(3035696099, $in);
}

export function QueryHTTPModelCatalog($in: $models.HTTPModelCatalogQuery): $CancellablePromise<modelcatalog$0.Result> {
    return $Call.ByID(336668775, $in);
}

export function QuestionsSufficient($in: $models.GenerateBrainstormInput): $CancellablePromise<$models.BrainstormDTO> {
    return $Call.ByID(4217471246, $in);
}

/**
 * RefreshProjectMemory has the AI read the project again. The read runs in the background; the answer says it started.
 */
export function RefreshProjectMemory(workspaceID: string): $CancellablePromise<$models.ProjectMemoryDTO> {
    return $Call.ByID(1179087802, workspaceID);
}

export function ReindexKnowledge($in: $models.KnowledgeDocumentInput): $CancellablePromise<$models.KnowledgeDocumentDTO> {
    return $Call.ByID(3981461728, $in);
}

export function RemoveKnowledge($in: $models.KnowledgeDocumentInput): $CancellablePromise<void> {
    return $Call.ByID(2284899163, $in);
}

export function ReopenPipelineCodeReview($in: $models.ReopenPipelineCodeReviewInput): $CancellablePromise<$models.PipelineDTO> {
    return $Call.ByID(2404219947, $in);
}

export function RequestAuthoringStageRevision($in: $models.GenerateAuthoringStageInput): $CancellablePromise<$models.AuthoringStageDTO> {
    return $Call.ByID(1009065678, $in);
}

export function RequestBrainstormRevision($in: $models.RequestBrainstormRevisionInput): $CancellablePromise<$models.BrainstormDTO> {
    return $Call.ByID(4009909438, $in);
}

/**
 * ResizeTerminal follows the panel's size.
 */
export function ResizeTerminal($in: $models.ResizeTerminalInput): $CancellablePromise<void> {
    return $Call.ByID(2767860365, $in);
}

export function RestorePipelineDesignDocument($in: $models.RestorePipelineDesignDocumentInput): $CancellablePromise<$models.PipelineDesignDTO> {
    return $Call.ByID(381545140, $in);
}

export function ResumePausedBrainstorm($in: $models.BrainstormRequestInput): $CancellablePromise<$models.BrainstormDTO> {
    return $Call.ByID(2112512117, $in);
}

/**
 * ResumePipelineFixes picks the fix loop up where it stopped: QA's failures already went back to Code, and the
 * Coder round did not start (the app closed, or the round could not begin).
 */
export function ResumePipelineFixes($in: $models.ResumePipelineFixesInput): $CancellablePromise<$models.QALoopDTO> {
    return $Call.ByID(1062614895, $in);
}

/**
 * ResumeWorkflowRun records the user's recovery choice. Retry only returns
 * the step to ready; a second, separate action is required to execute it.
 */
export function ResumeWorkflowRun($in: $models.ResumeWorkflowRunInput): $CancellablePromise<$models.WorkflowRunDTO> {
    return $Call.ByID(367062740, $in);
}

export function RetryChannelMessage($in: $models.RetryChannelMessageInput): $CancellablePromise<$models.ChannelMessageDTO> {
    return $Call.ByID(3575993999, $in);
}

/**
 * RevealWorkspace opens the project's folder in the system file manager.
 */
export function RevealWorkspace(workspaceID: string): $CancellablePromise<void> {
    return $Call.ByID(2955566917, workspaceID);
}

export function ReviseAuthoringDiscovery($in: $models.ReviseAuthoringDiscoveryInput): $CancellablePromise<$models.PipelineDTO> {
    return $Call.ByID(3908236976, $in);
}

export function RunScheduleNow(scheduleID: string): $CancellablePromise<$models.ScheduleJobDTO> {
    return $Call.ByID(878768545, scheduleID);
}

export function RunWorkflowStep(runID: string): $CancellablePromise<$models.WorkflowRunDTO> {
    return $Call.ByID(894670433, runID);
}

export function SaveAgent($in: $models.SaveAgentInput): $CancellablePromise<$models.AgentDTO> {
    return $Call.ByID(3016929217, $in);
}

export function SaveAuthoringStageModelPreference($in: $models.SaveAuthoringStageModelPreferenceInput): $CancellablePromise<$models.AuthoringStageModelPreferenceDTO> {
    return $Call.ByID(1994367139, $in);
}

export function SaveKnowledgeEmbeddingProfile($in: $models.SaveKnowledgeEmbeddingProfileInput): $CancellablePromise<$models.KnowledgeEmbeddingProfileDTO> {
    return $Call.ByID(3634686722, $in);
}

export function SaveLocalChannel($in: $models.SaveLocalChannelInput): $CancellablePromise<$models.LocalChannelDTO> {
    return $Call.ByID(4055619858, $in);
}

export function SaveMCPServer($in: $models.SaveMCPServerInput): $CancellablePromise<$models.MCPServerDTO> {
    return $Call.ByID(4205699079, $in);
}

export function SaveOpenRouterManagementKey(profileID: string, key: string): $CancellablePromise<$models.OpenRouterManagementKeyStatus> {
    return $Call.ByID(1077395309, profileID, key);
}

export function SavePipelineArtifact($in: $models.SavePipelineArtifactInput): $CancellablePromise<$models.PipelineDTO> {
    return $Call.ByID(2018759164, $in);
}

/**
 * SaveProjectMemory keeps the person's own version of the memory; a later read by the AI replaces it only when asked.
 */
export function SaveProjectMemory($in: $models.SaveProjectMemoryInput): $CancellablePromise<$models.ProjectMemoryDTO> {
    return $Call.ByID(1839687086, $in);
}

export function SaveProviderProfile($in: $models.SaveProviderProfileInput): $CancellablePromise<$models.BackendDTO> {
    return $Call.ByID(3296179174, $in);
}

export function SaveSchedule($in: $models.SaveScheduleInput): $CancellablePromise<$models.ScheduleDTO> {
    return $Call.ByID(2897557613, $in);
}

export function SaveSettings($in: $models.SaveSettingsInput): $CancellablePromise<$models.SettingsDTO> {
    return $Call.ByID(2709999021, $in);
}

export function SaveSkill($in: $models.SaveSkillInput): $CancellablePromise<$models.SkillDTO> {
    return $Call.ByID(3363572221, $in);
}

/**
 * SaveStageExecutor chooses who works on a phase. It keeps identifiers only: the model is checked against the
 * catalog when the phase runs, because a catalog answer expires and a saved choice must not.
 */
export function SaveStageExecutor($in: $models.SaveStageExecutorInput): $CancellablePromise<$models.StageExecutorDTO> {
    return $Call.ByID(2252147175, $in);
}

export function SaveWorkflow($in: $models.SaveWorkflowInput): $CancellablePromise<$models.WorkflowDTO> {
    return $Call.ByID(1702753085, $in);
}

export function SearchKnowledge($in: $models.SearchKnowledgeInput): $CancellablePromise<$models.KnowledgeHitDTO[] | null> {
    return $Call.ByID(1032073071, $in);
}

export function SearchKnowledgeDetailed($in: $models.SearchKnowledgeInput): $CancellablePromise<$models.KnowledgeSearchDTO> {
    return $Call.ByID(541411855, $in);
}

export function SendChannelMessage($in: $models.SendChannelMessageInput): $CancellablePromise<$models.ChannelMessageDTO> {
    return $Call.ByID(1714037605, $in);
}

/**
 * SetPullRequestWatch turns the review watch on or off; turning it on checks right away.
 */
export function SetPullRequestWatch($in: $models.SetPullRequestWatchInput): $CancellablePromise<$models.PullRequestDTO> {
    return $Call.ByID(1236363696, $in);
}

export function SetSchedulePaused($in: $models.SetSchedulePausedInput): $CancellablePromise<$models.ScheduleDTO> {
    return $Call.ByID(34139408, $in);
}

/**
 * SetSessionPinned pins a conversation to the top of the Casual sidebar, or takes the pin off.
 */
export function SetSessionPinned($in: $models.SetSessionPinnedInput): $CancellablePromise<void> {
    return $Call.ByID(541400543, $in);
}

/**
 * SetWorkspaceArchived takes a project off the Projects list or puts it back. Nothing the project owns is deleted.
 */
export function SetWorkspaceArchived($in: $models.SetWorkspaceArchivedInput): $CancellablePromise<$models.WorkspaceSummaryDTO> {
    return $Call.ByID(764968670, $in);
}

export function SetWorkspaceProfile($in: $models.SetWorkspaceProfileInput): $CancellablePromise<$models.WorkspaceDTO> {
    return $Call.ByID(1564453125, $in);
}

export function SkipAuthoringStage($in: $models.AuthoringStageDecisionInput): $CancellablePromise<$models.AuthoringStageDTO> {
    return $Call.ByID(2315752159, $in);
}

export function SkipBrainstormQuestions($in: $models.SkipBrainstormQuestionsInput): $CancellablePromise<$models.BrainstormDTO> {
    return $Call.ByID(3934271656, $in);
}

export function SkipPipelineStage($in: $models.SkipPipelineStageInput): $CancellablePromise<$models.PipelineDTO> {
    return $Call.ByID(1087222610, $in);
}

export function StartAuthoringCode($in: $models.StartAuthoringCodeInput): $CancellablePromise<$models.AuthoringCodeRunDTO> {
    return $Call.ByID(2174999461, $in);
}

export function StartBrainstorming($in: $models.StartBrainstormingInput): $CancellablePromise<$models.BrainstormDTO> {
    return $Call.ByID(765722722, $in);
}

/**
 * StartPipelineQA runs QA in the background: the evaluator session, its run and the recorded evaluation.
 */
export function StartPipelineQA($in: $models.StartPipelineQAInput): $CancellablePromise<$models.QALoopDTO> {
    return $Call.ByID(3941138339, $in);
}

/**
 * StartTerminal opens the person's shell in the project folder, for the terminal panel.
 */
export function StartTerminal($in: $models.StartTerminalInput): $CancellablePromise<$models.TerminalDTO> {
    return $Call.ByID(4053592699, $in);
}

export function StartWorkflow($in: $models.StartWorkflowInput): $CancellablePromise<$models.WorkflowRunDTO> {
    return $Call.ByID(4216349358, $in);
}

/**
 * WriteTerminal types into a terminal.
 */
export function WriteTerminal($in: $models.WriteTerminalInput): $CancellablePromise<void> {
    return $Call.ByID(1504384660, $in);
}
