// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as application$0 from "../../../../persioflexa/harflex/internal/application/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "harflex:event": application$0.EventDTO;
            "harflex:schedule": application$0.ScheduleChangeDTO;
            "harflex:update": application$0.UpdateStateDTO;
        }
    }
}
