// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface BrainstormHumanAction {
    "requestId": string;
    "kind": string;
    "actor": string;
    "synthesisVersion": number;
    "feedback": string;
    "reason": string;
    "choice": string;
    "resultRevision": number;
    "pipelineRevision": number;
    "createdAt": string;
}

export interface BrainstormSynthesisContent {
    "scope": string;
    "decisions": string[] | null;
    "openQuestions": string[] | null;
}

export interface BrainstormUsage {
    "inputTokens": number;
    "outputTokens": number;

    /**
     * Nil means unknown (N/A), never free.
     */
    "costUsd": number | null;
}

export interface PipelineDesignMessage {
    "id": string;
    "role": string;
    "content": string;
    "target": string;
    "attemptId": string;
    "createdAt": string;
}
