import { cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, describe, expect, it, vi } from 'vitest'
import type { Backend, ModelCatalogQuery, ModelCatalogResult } from '../../lib/backend'
import { ProviderDialog, profileID } from './ProviderDialog'

afterEach(cleanup)

const secret = 'sk-test-canary-0042'
const catalogResult: ModelCatalogResult = {
  backendId: 'preview', source: 'openai_models', destination: 'https://api.openai.com:443', profileRevision: 'api:revision',
  searchTerm: '', models: [{ id: 'vendor/model-exact', displayName: 'Modelo exato', backendId: 'preview', source: 'openai_models', availability: 'listed' }],
  nextCursor: '', checkedAt: '2026-09-27T10:00:00Z', status: 'complete', complete: true, accountFiltered: false,
}
const routerProfile = { id: 'router', name: 'Router', kind: 'openai_compatible', providerType: 'openrouter' as const, baseUrl: 'https://openrouter.ai/api/v1', model: 'vendor/model-exact', hasCredential: true, endpointBlocked: false, updatedAt: '2026-09-25T10:00:00Z' }

function backendWith(save: Backend['saveProviderProfile']) {
  return { saveProviderProfile: save } as unknown as Backend
}

describe('ProviderDialog', () => {
  it('stores an OpenRouter catalog key separately and reads back status without exposing bytes', async () => {
    const user = userEvent.setup()
    let configured = false
    const status = () => ({ profileId: 'router', origin: 'https://openrouter.ai:443', configured, usable: configured, updatedAt: '2026-09-27T10:00:00Z' })
    const get = vi.fn(async () => status())
    const saveKey = vi.fn(async (_id: string, _key: string) => { configured = true; return status() })
    const { container } = render(<ProviderDialog backend={{ ...backendWith(vi.fn()), getOpenRouterManagementKeyStatus: get, saveOpenRouterManagementKey: saveKey } as Backend} initial={routerProfile} onSaved={() => undefined} onClose={() => undefined} />)
    expect(await screen.findByText(/Sem chave de gerenciamento/)).toBeInTheDocument()
    const input = screen.getByLabelText('Chave de gerenciamento do catálogo')
    await user.type(input, 'management-canary')
    await user.click(screen.getByRole('button', { name: 'Salvar chave do catálogo' }))
    expect(saveKey).toHaveBeenCalledWith('router', 'management-canary')
    expect(input).toHaveValue('')
    expect(await screen.findByText(/Chave configurada para esta origem/)).toBeInTheDocument()
    expect(get).toHaveBeenCalledTimes(2)
    expect(container.innerHTML).not.toContain('management-canary')
  })

  it('requires explicit confirmation to remove an OpenRouter catalog key and preserves general-list guidance', async () => {
    const user = userEvent.setup()
    let configured = true
    const status = () => ({ profileId: 'router', origin: 'https://openrouter.ai:443', configured, usable: configured, updatedAt: '2026-09-27T10:00:00Z' })
    const clear = vi.fn(async () => { configured = false })
    render(<ProviderDialog backend={{ ...backendWith(vi.fn()), getOpenRouterManagementKeyStatus: async () => status(), clearOpenRouterManagementKey: clear } as Backend} initial={routerProfile} onSaved={() => undefined} onClose={() => undefined} />)
    expect(await screen.findByText(/Chave configurada para esta origem/)).toBeInTheDocument()
    const draft = screen.getByLabelText('Chave de gerenciamento do catálogo')
    await user.type(draft, 'replacement-canary')
    await user.click(screen.getByRole('button', { name: 'Remover chave do catálogo' }))
    expect(clear).not.toHaveBeenCalled()
    expect(screen.getByText(/histórico permanece/)).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Confirmar remoção' }))
    expect(clear).toHaveBeenCalledWith('router')
    expect(await screen.findByText(/Sem chave de gerenciamento/)).toBeInTheDocument()
    expect(draft).toHaveValue('')
    expect(screen.getByRole('button', { name: 'Consultar modelos' })).toBeEnabled()
  })

  it('does not save a management key for an unsaved origin and clears its draft when destination changes', async () => {
    const user = userEvent.setup()
    const saveKey = vi.fn()
    render(<ProviderDialog backend={{ ...backendWith(vi.fn()), getOpenRouterManagementKeyStatus: async () => ({ profileId: 'router', origin: 'https://openrouter.ai:443', configured: true, usable: true, updatedAt: '2026-09-27T10:00:00Z' }), saveOpenRouterManagementKey: saveKey } as Backend} initial={routerProfile} onSaved={() => undefined} onClose={() => undefined} />)
    const input = await screen.findByLabelText('Chave de gerenciamento do catálogo')
    await user.type(input, 'management-canary')
    fireEvent.change(screen.getByLabelText('URL base'), { target: { value: 'https://other.example/api/v1' } })
    expect(input).toHaveValue('')
    expect(screen.getByText(/salve o novo destino.*rotacione/i)).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Salvar chave do catálogo' })).not.toBeInTheDocument()
    expect(saveKey).not.toHaveBeenCalled()
  })
  it('dismisses a pending removal decision when a replacement management key is saved', async () => {
    const user = userEvent.setup()
    const status = { profileId: 'router', origin: 'https://openrouter.ai:443', configured: true, usable: true, updatedAt: '2026-09-27T10:00:00Z' }
    const clear = vi.fn()
    const saveKey = vi.fn(async () => status)
    render(<ProviderDialog backend={{ ...backendWith(vi.fn()), getOpenRouterManagementKeyStatus: async () => status, saveOpenRouterManagementKey: saveKey, clearOpenRouterManagementKey: clear } as Backend} initial={routerProfile} onSaved={() => undefined} onClose={() => undefined} />)
    await screen.findByText(/Chave configurada para esta origem/)
    await user.click(screen.getByRole('button', { name: 'Remover chave do catálogo' }))
    expect(screen.getByRole('button', { name: 'Confirmar remoção' })).toBeInTheDocument()
    await user.type(screen.getByLabelText('Chave de gerenciamento do catálogo'), 'replacement-canary')
    await user.click(screen.getByRole('button', { name: 'Salvar chave do catálogo' }))
    expect(saveKey).toHaveBeenCalledWith('router', 'replacement-canary')
    expect(screen.queryByRole('button', { name: 'Confirmar remoção' })).not.toBeInTheDocument()
    expect(clear).not.toHaveBeenCalled()
  })
  it('blocks account catalog discovery when a saved management key is unusable', async () => {
    const query = vi.fn()
    render(<ProviderDialog backend={{ ...backendWith(vi.fn()), queryHTTPModelCatalog: query, getOpenRouterManagementKeyStatus: async () => ({ profileId: 'router', origin: 'https://old.example:443', configured: true, usable: false, updatedAt: '2026-09-27T10:00:00Z' }) } as Backend} initial={routerProfile} onSaved={() => undefined} onClose={() => undefined} />)
    expect(await screen.findByText(/Chave vinculada a outra origem/)).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Consultar modelos' })).toBeDisabled()
    expect(query).not.toHaveBeenCalled()
  })
  it('requires status readback after an uncertain management-key save before another mutation', async () => {
    const user = userEvent.setup()
    let configured = false
    const status = () => ({ profileId: 'router', origin: 'https://openrouter.ai:443', configured, usable: configured, updatedAt: '2026-09-27T10:00:00Z' })
    const get = vi.fn(async () => status())
    const saveKey = vi.fn(async () => { configured = true; throw new Error('response lost after publication') })
    render(<ProviderDialog backend={{ ...backendWith(vi.fn()), getOpenRouterManagementKeyStatus: get, saveOpenRouterManagementKey: saveKey } as Backend} initial={routerProfile} onSaved={() => undefined} onClose={() => undefined} />)
    await screen.findByText(/Sem chave de gerenciamento/)
    await user.type(screen.getByLabelText('Chave de gerenciamento do catálogo'), 'management-canary')
    await user.click(screen.getByRole('button', { name: 'Salvar chave do catálogo' }))
    expect(await screen.findByText(/resultado.*não foi confirmado/i)).toBeInTheDocument()
    expect(screen.getByLabelText('Chave de gerenciamento do catálogo')).toBeDisabled()
    expect(screen.getByRole('button', { name: 'Consultar modelos' })).toBeDisabled()
    await user.click(screen.getByRole('button', { name: 'Atualizar estado' }))
    expect(await screen.findByText(/Chave configurada para esta origem/)).toBeInTheDocument()
    expect(screen.getByLabelText('Chave de gerenciamento do catálogo')).toBeEnabled()
    expect(get).toHaveBeenCalledTimes(2)
  })
  it('removes a previously filtered model list before clearing the active key', async () => {
    const user = userEvent.setup()
    let finish!: () => void
    let configured = true
    const clear = vi.fn(() => new Promise<void>(resolve => { finish = () => { configured = false; resolve() } }))
    const status = () => ({ profileId: 'router', origin: 'https://openrouter.ai:443', configured, usable: configured, updatedAt: '2026-09-27T10:00:00Z' })
    render(<ProviderDialog backend={{ ...backendWith(vi.fn()), getOpenRouterManagementKeyStatus: async () => status(), clearOpenRouterManagementKey: clear, queryHTTPModelCatalog: async () => ({ ...catalogResult, accountFiltered: true }) } as Backend} initial={routerProfile} onSaved={() => undefined} onClose={() => undefined} />)
    await screen.findByText(/Chave configurada para esta origem/)
    await user.click(screen.getByRole('button', { name: 'Consultar modelos' }))
    expect(await screen.findByTestId('picker-provider-model')).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Remover chave do catálogo' }))
    await user.click(screen.getByRole('button', { name: 'Confirmar remoção' }))
    expect(clear).toHaveBeenCalledWith('router')
    expect(screen.queryByTestId('picker-provider-model')).not.toBeInTheDocument()
    finish()
    expect(await screen.findByText(/Sem chave de gerenciamento/)).toBeInTheDocument()
  })
  it('queries a new provider only on request and selects the exact discovered model without saving', async () => {
    const user = userEvent.setup()
    const query = vi.fn(async () => catalogResult)
    const save = vi.fn()
    const { container } = render(<ProviderDialog backend={{ ...backendWith(save), queryHTTPModelCatalog: query } as Backend} onSaved={() => undefined} onClose={() => undefined} />)
    expect(query).not.toHaveBeenCalled()
    await user.type(screen.getByLabelText('Nome'), 'OpenAI')
    await user.click(within(screen.getByTestId('picker-provider-type')).getByRole('button'))
    await user.click(screen.getByRole('option', { name: 'OpenAI' }))
    fireEvent.change(screen.getByLabelText('URL base'), { target: { value: 'https://api.openai.com/v1' } })
    const key = screen.getByLabelText('Chave de API')
    await user.type(key, secret)
    await user.click(screen.getByRole('button', { name: 'Consultar modelos' }))
    expect(query).toHaveBeenCalledWith({ profileId: 'openai', searchTerm: '', refresh: true, draft: { providerType: 'openai', baseUrl: 'https://api.openai.com/v1', apiKey: secret } }, expect.any(AbortSignal))
    const modelPicker = await screen.findByTestId('picker-provider-model')
    await user.click(within(modelPicker).getByRole('button'))
    await user.click(screen.getByRole('option', { name: 'Modelo exato' }))
    expect(screen.getByLabelText('Modelo')).toHaveValue('vendor/model-exact')
    expect(key).toHaveValue(secret)
    expect(container.innerHTML).not.toContain(secret)
    expect(save).not.toHaveBeenCalled()
  })

  it('keeps a manual model when discovery is unsupported and labels it unverified', async () => {
    const user = userEvent.setup()
    const query = vi.fn(async () => ({ ...catalogResult, status: 'unsupported' as const, complete: false, models: [], errorCode: 'catalog_unsupported' }))
    render(<ProviderDialog backend={{ ...backendWith(vi.fn()), queryHTTPModelCatalog: query } as Backend} onSaved={() => undefined} onClose={() => undefined} />)
    await user.type(screen.getByLabelText('Nome'), 'Genérico')
    fireEvent.change(screen.getByLabelText('URL base'), { target: { value: 'http://127.0.0.1:1234/v1' } })
    await user.type(screen.getByLabelText('Modelo'), 'manual/exact')
    await user.click(screen.getByRole('button', { name: 'Consultar modelos' }))
    expect(await screen.findByText(/Este provedor não oferece lista de modelos/)).toBeInTheDocument()
    expect(screen.getByText(/ID atual informado manualmente · não verificado/)).toBeInTheDocument()
    expect(screen.getByLabelText('Modelo')).toHaveValue('manual/exact')
  })

  it('discards a late catalog response after the destination changes', async () => {
    const user = userEvent.setup()
    let resolve!: (result: ModelCatalogResult) => void
    const query = vi.fn((_query: ModelCatalogQuery, _signal?: AbortSignal) => new Promise<ModelCatalogResult>(done => { resolve = done }))
    render(<ProviderDialog backend={{ ...backendWith(vi.fn()), queryHTTPModelCatalog: query } as Backend} onSaved={() => undefined} onClose={() => undefined} />)
    fireEvent.change(screen.getByLabelText('URL base'), { target: { value: 'http://127.0.0.1:1234/v1' } })
    await user.click(screen.getByRole('button', { name: 'Consultar modelos' }))
    const signal = query.mock.calls[0][1] as AbortSignal
    fireEvent.change(screen.getByLabelText('URL base'), { target: { value: 'http://127.0.0.1:11434/v1' } })
    expect(signal.aborted).toBe(true)
    resolve(catalogResult)
    expect(screen.queryByTestId('picker-provider-model')).not.toBeInTheDocument()
  })

  it('cancels a pending catalog query without treating it as an empty catalog', async () => {
    const user = userEvent.setup()
    let resolve!: (result: ModelCatalogResult) => void
    const query = vi.fn((_query: ModelCatalogQuery, _signal?: AbortSignal) => new Promise<ModelCatalogResult>(done => { resolve = done }))
    render(<ProviderDialog backend={{ ...backendWith(vi.fn()), queryHTTPModelCatalog: query } as Backend} onSaved={() => undefined} onClose={() => undefined} />)
    fireEvent.change(screen.getByLabelText('URL base'), { target: { value: 'http://127.0.0.1:1234/v1' } })
    await user.click(screen.getByRole('button', { name: 'Consultar modelos' }))
    const signal = query.mock.calls[0][1] as AbortSignal
    await user.click(screen.getByRole('button', { name: 'Cancelar consulta' }))
    expect(signal.aborted).toBe(true)
    expect(screen.getByText(/Consulta interrompida/)).toBeInTheDocument()
    resolve(catalogResult)
    expect(screen.queryByTestId('picker-provider-model')).not.toBeInTheDocument()
    expect(screen.queryByText(/nenhum modelo listado/i)).not.toBeInTheDocument()
  })

  it('labels an OpenRouter general list as not account-filtered', async () => {
    const user = userEvent.setup()
    const query = vi.fn(async () => ({ ...catalogResult, source: 'openrouter_general_unfiltered', accountFiltered: false }))
    render(<ProviderDialog backend={{ ...backendWith(vi.fn()), queryHTTPModelCatalog: query } as Backend} onSaved={() => undefined} onClose={() => undefined} />)
    await user.click(within(screen.getByTestId('picker-provider-type')).getByRole('button'))
    await user.click(screen.getByRole('option', { name: 'OpenRouter' }))
    fireEvent.change(screen.getByLabelText('URL base'), { target: { value: 'https://openrouter.ai/api/v1' } })
    await user.type(screen.getByLabelText('Chave de API'), secret)
    await user.click(screen.getByRole('button', { name: 'Consultar modelos' }))
    expect(await screen.findByText(/Catálogo geral, não filtrado pelas preferências da conta/)).toBeInTheDocument()
  })

  it('uses the saved profile only for an unchanged destination and requires a new token to preview an edited URL', async () => {
    const user = userEvent.setup()
    const query = vi.fn(async () => catalogResult)
    const initial = { id: 'remote', name: 'Remote', kind: 'openai_compatible', providerType: 'openai' as const, baseUrl: 'https://api.example/v1', model: 'old', hasCredential: true, endpointBlocked: false, updatedAt: '2026-09-25T10:00:00Z' }
    render(<ProviderDialog backend={{ ...backendWith(vi.fn()), queryHTTPModelCatalog: query } as Backend} initial={initial} onSaved={() => undefined} onClose={() => undefined} />)
    await user.click(screen.getByRole('button', { name: 'Consultar modelos' }))
    expect(query).toHaveBeenCalledWith({ profileId: 'remote', searchTerm: '', refresh: true }, expect.any(AbortSignal))
    fireEvent.change(screen.getByLabelText('URL base'), { target: { value: 'https://api.example/other-v1' } })
    await user.click(screen.getByRole('button', { name: 'Consultar modelos' }))
    expect(query).toHaveBeenCalledTimes(1)
    expect(screen.getByText(/novo token para consultar o destino editado/i)).toBeInTheDocument()
    await user.type(screen.getByLabelText('Chave de API'), secret)
    await user.click(screen.getByRole('button', { name: 'Consultar modelos' }))
    expect(query).toHaveBeenLastCalledWith({ profileId: 'remote', searchTerm: '', refresh: true, draft: { providerType: 'openai', baseUrl: 'https://api.example/other-v1', apiKey: secret } }, expect.any(AbortSignal))
  })

  it('lists a keyless LM Studio model as installed but not loaded', async () => {
    const user = userEvent.setup()
    const query = vi.fn(async () => ({ ...catalogResult, source: 'lm_studio_native', destination: 'http://127.0.0.1:1234', models: [{ id: 'local/model', displayName: 'Modelo local', backendId: 'preview', source: 'lm_studio_native', availability: 'listed', loaded: false }] }))
    render(<ProviderDialog backend={{ ...backendWith(vi.fn()), queryHTTPModelCatalog: query } as Backend} onSaved={() => undefined} onClose={() => undefined} />)
    await user.click(within(screen.getByTestId('picker-provider-type')).getByRole('button'))
    await user.click(screen.getByRole('option', { name: 'LM Studio local' }))
    fireEvent.change(screen.getByLabelText('URL base'), { target: { value: 'http://127.0.0.1:1234/v1' } })
    await user.click(screen.getByRole('button', { name: 'Consultar modelos' }))
    expect(query).toHaveBeenCalledWith({ profileId: 'provider-local', searchTerm: '', refresh: true, draft: { providerType: 'lm_studio', baseUrl: 'http://127.0.0.1:1234/v1', apiKey: '' } }, expect.any(AbortSignal))
    await user.click(within(await screen.findByTestId('picker-provider-model')).getByRole('button', { name: /Abrir opções/ }))
    await user.click(screen.getByRole('option', { name: 'Modelo local' }))
    expect(screen.getByText(/instalado, mas não carregado/i)).toBeInTheDocument()
  })
  it.each([
    ['generic', 'API compatível', 'https://seu-provedor.example/v1'],
    ['openai', 'OpenAI', 'https://api.openai.com/v1'],
    ['openrouter', 'OpenRouter', 'https://openrouter.ai/api/v1'],
    ['lm_studio', 'LM Studio local', 'http://127.0.0.1:1234/v1'],
    ['ollama', 'Ollama local', 'http://127.0.0.1:11434/v1'],
  ] as const)('labels %s as %s and suggests %s', async (type, label, placeholder) => {
    const user = userEvent.setup()
    render(<ProviderDialog backend={backendWith(vi.fn())} onSaved={() => undefined} onClose={() => undefined} />)
    const picker = screen.getByTestId('picker-provider-type')
    const trigger = within(picker).getByRole('button')
    await user.click(trigger)
    const option = screen.getByRole('option', { name: label })
    expect(option).toBeInTheDocument()
    await user.click(option)
    expect(trigger).toHaveTextContent(label)
    await user.click(trigger)
    expect(screen.getByRole('option', { name: label })).toHaveAttribute('aria-selected', 'true')
    await user.keyboard('{Escape}')
    expect(screen.getByLabelText('URL base')).toHaveAttribute('placeholder', placeholder)
  })

  it('changes the URL suggestion without rewriting a saved URL', async () => {
    const user = userEvent.setup()
    render(<ProviderDialog backend={backendWith(vi.fn())} initial={{ id: 'custom', name: 'Custom', kind: 'openai_compatible', providerType: 'generic', baseUrl: 'https://custom.example/v1', model: 'old', hasCredential: true, endpointBlocked: false, updatedAt: '2026-09-25T10:00:00Z' }} onSaved={() => undefined} onClose={() => undefined} />)
    const baseURL = screen.getByLabelText('URL base')
    await user.click(within(screen.getByTestId('picker-provider-type')).getByRole('button'))
    await user.click(screen.getByRole('option', { name: 'OpenRouter' }))
    expect(baseURL).toHaveValue('https://custom.example/v1')
    expect(baseURL).toHaveAttribute('placeholder', 'https://openrouter.ai/api/v1')
  })

  it.each([
    ['lm_studio', 'http://127.0.0.1:1234/v1'],
    ['ollama', 'http://127.0.0.1:11434/v1'],
  ] as const)('guides a new %s profile from empty URL through remote and loopback', async (type, loopbackURL) => {
    const user = userEvent.setup()
    const save = vi.fn()
    render(<ProviderDialog backend={backendWith(save)} onSaved={() => undefined} onClose={() => undefined} />)
    const typeLabel = type === 'lm_studio' ? 'LM Studio local' : 'Ollama local'
    await user.click(within(screen.getByTestId('picker-provider-type')).getByRole('button'))
    await user.click(screen.getByRole('option', { name: typeLabel }))
    const baseURL = screen.getByLabelText('URL base')
    expect(baseURL).toHaveValue('')
    expect(screen.getByLabelText('Token opcional')).not.toBeRequired()
    expect(baseURL).toBeRequired()
    fireEvent.change(baseURL, { target: { value: 'https://remote.example/v1' } })
    expect(screen.getByText(/IP literal de loopback/)).toBeInTheDocument()
    expect(screen.queryByLabelText('Chave de API')).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Salvar provedor' })).toBeDisabled()
    await user.click(screen.getByRole('button', { name: 'Salvar provedor' }))
    expect(save).not.toHaveBeenCalled()
    fireEvent.change(baseURL, { target: { value: loopbackURL } })
    expect(screen.queryByText(/IP literal de loopback/)).not.toBeInTheDocument()
    const optionalKey = screen.getByLabelText('Token opcional')
    expect(optionalKey).not.toBeRequired()
    expect(screen.getByRole('button', { name: 'Salvar provedor' })).toBeEnabled()
    await user.type(optionalKey, secret)
    fireEvent.change(baseURL, { target: { value: 'https://remote.example/v1' } })
    expect(optionalKey).toHaveValue('')
    expect(screen.getByRole('button', { name: 'Salvar provedor' })).toBeDisabled()
    expect(save).not.toHaveBeenCalled()
  })

  it('clears a newly entered key when the destination origin changes', async () => {
    const user = userEvent.setup()
    const save = vi.fn()
    render(<ProviderDialog backend={backendWith(save)} onSaved={() => undefined} onClose={() => undefined} />)
    await user.type(screen.getByLabelText('Nome'), 'Remote')
    fireEvent.change(screen.getByLabelText('URL base'), { target: { value: 'https://a.example/v1' } })
    await user.type(screen.getByLabelText('Modelo'), 'qwen')
    const key = screen.getByLabelText('Chave de API')
    await user.type(key, secret)
    fireEvent.change(screen.getByLabelText('URL base'), { target: { value: 'https://b.example/v1' } })
    expect(key).toHaveValue('')
    await user.click(screen.getByRole('button', { name: 'Salvar provedor' }))
    expect(save).not.toHaveBeenCalled()
  })

  it('clears a newly entered key when the provider type changes', async () => {
    const user = userEvent.setup()
    const save = vi.fn()
    render(<ProviderDialog backend={backendWith(save)} onSaved={() => undefined} onClose={() => undefined} />)
    await user.type(screen.getByLabelText('Nome'), 'Remote')
    fireEvent.change(screen.getByLabelText('URL base'), { target: { value: 'https://a.example/v1' } })
    await user.type(screen.getByLabelText('Modelo'), 'qwen')
    const key = screen.getByLabelText('Chave de API')
    await user.type(key, secret)
    await user.click(within(screen.getByTestId('picker-provider-type')).getByRole('button'))
    await user.click(screen.getByRole('option', { name: 'OpenRouter' }))
    expect(key).toHaveValue('')
    await user.click(screen.getByRole('button', { name: 'Salvar provedor' }))
    expect(save).not.toHaveBeenCalled()
  })

  it('does not suggest credential reuse after switching a keyed remote profile to a local-only type', async () => {
    const user = userEvent.setup()
    render(<ProviderDialog backend={backendWith(vi.fn())} initial={{ id: 'remote', name: 'Remote', kind: 'openai_compatible', providerType: 'generic', baseUrl: 'https://remote.example/v1', model: 'old', hasCredential: true, endpointBlocked: false, updatedAt: '2026-09-25T10:00:00Z' }} onSaved={() => undefined} onClose={() => undefined} />)
    await user.click(within(screen.getByTestId('picker-provider-type')).getByRole('button'))
    await user.click(screen.getByRole('option', { name: 'LM Studio local' }))
    expect(screen.getByText(/IP literal de loopback/)).toBeInTheDocument()
    expect(screen.queryByText(/reutilizar a credencial atual/)).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Salvar provedor' })).toBeDisabled()
  })

  it('saves a new LM Studio loopback profile without a token', async () => {
    const user = userEvent.setup()
    const save = vi.fn(async (input: { id: string; name: string }) => ({ id: input.id, name: input.name, kind: 'api' as const, available: true }))
    render(<ProviderDialog backend={backendWith(save)} onSaved={() => undefined} onClose={() => undefined} />)
    await user.type(screen.getByLabelText('Nome'), 'LM Studio local')
    await user.click(within(screen.getByTestId('picker-provider-type')).getByRole('button'))
    await user.click(screen.getByRole('option', { name: 'LM Studio local' }))
    await user.type(screen.getByLabelText('URL base'), 'http://127.0.0.1:1234/v1')
    await user.type(screen.getByLabelText('Modelo'), 'qwen')
    expect(screen.getByLabelText('Token opcional')).not.toBeRequired()
    await user.click(screen.getByRole('button', { name: 'Salvar provedor' }))
    expect(save).toHaveBeenCalledWith({ id: 'lm-studio-local', name: 'LM Studio local', providerType: 'lm_studio', baseUrl: 'http://127.0.0.1:1234/v1', model: 'qwen', apiKey: '', clearCredential: false })
  })

  it.each(['http://127.4.5.6:1234/v1', 'http://[::1]:1234/v1'])('treats literal loopback %s as optional-token local setup', async baseUrl => {
    const user = userEvent.setup()
    render(<ProviderDialog backend={backendWith(vi.fn())} onSaved={() => undefined} onClose={() => undefined} />)
    await user.click(within(screen.getByTestId('picker-provider-type')).getByRole('button'))
    await user.click(screen.getByRole('option', { name: 'Ollama local' }))
    fireEvent.change(screen.getByLabelText('URL base'), { target: { value: baseUrl } })
    expect(screen.getByLabelText('Token opcional')).not.toBeRequired()
  })

  it('requires a key for a new OpenRouter profile and clears it after submission', async () => {
    const user = userEvent.setup()
    const save = vi.fn(async (input: { id: string; name: string }) => ({ id: input.id, name: input.name, kind: 'api' as const, available: true }))
    render(<ProviderDialog backend={backendWith(save)} onSaved={() => undefined} onClose={() => undefined} />)
    await user.type(screen.getByLabelText('Nome'), 'OpenRouter')
    await user.click(within(screen.getByTestId('picker-provider-type')).getByRole('button'))
    await user.click(screen.getByRole('option', { name: 'OpenRouter' }))
    await user.type(screen.getByLabelText('URL base'), 'https://openrouter.ai/api/v1')
    await user.type(screen.getByLabelText('Modelo'), 'openai/gpt-5')
    const key = screen.getByLabelText('Chave de API')
    expect(key).toBeRequired()
    await user.click(screen.getByRole('button', { name: 'Salvar provedor' }))
    expect(save).not.toHaveBeenCalled()
    await user.type(key, secret)
    await user.click(screen.getByRole('button', { name: 'Salvar provedor' }))
    expect(save).toHaveBeenCalledWith({ id: 'openrouter', name: 'OpenRouter', providerType: 'openrouter', baseUrl: 'https://openrouter.ai/api/v1', model: 'openai/gpt-5', apiKey: secret, clearCredential: false })
    expect(key).toHaveValue('')
  })

  it('reuses a keyed HTTPS credential on the same canonical origin', async () => {
    const user = userEvent.setup()
    const save = vi.fn(async (input: { id: string; name: string }) => ({ id: input.id, name: input.name, kind: 'api' as const, available: true }))
    render(<ProviderDialog backend={backendWith(save)} initial={{ id: 'remote', name: 'Remote', kind: 'openai_compatible', providerType: 'generic', baseUrl: 'https://remote.example/v1', model: 'old', hasCredential: true, endpointBlocked: false, updatedAt: '2026-09-25T10:00:00Z' }} onSaved={() => undefined} onClose={() => undefined} />)
    await user.clear(screen.getByLabelText('URL base'))
    await user.type(screen.getByLabelText('URL base'), 'https://REMOTE.example:443/models')
    expect(screen.getByText(/credencial atual.*destino/i)).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Salvar provedor' }))
    expect(save).toHaveBeenCalledWith({ id: 'remote', name: 'Remote', providerType: 'generic', baseUrl: 'https://REMOTE.example:443/models', model: 'old', apiKey: '', clearCredential: false })
  })

  it.each(['i.example', 'i\u0307.example'])('requires a new token when Unicode host İ.example changes to %s', async host => {
    const user = userEvent.setup()
    const save = vi.fn()
    render(<ProviderDialog backend={backendWith(save)} initial={{ id: 'remote', name: 'Remote', kind: 'openai_compatible', providerType: 'generic', baseUrl: 'https://İ.example/v1', model: 'old', hasCredential: true, endpointBlocked: false, updatedAt: '2026-09-25T10:00:00Z' }} onSaved={() => undefined} onClose={() => undefined} />)
    await user.clear(screen.getByLabelText('URL base'))
    await user.type(screen.getByLabelText('URL base'), `https://${host}/models`)
    expect(screen.getByLabelText('Novo token')).toBeRequired()
    await user.click(screen.getByRole('button', { name: 'Salvar provedor' }))
    expect(save).not.toHaveBeenCalled()
  })

  it('requires a fresh token when moving a keyed remote profile to a local origin', async () => {
    const user = userEvent.setup()
    const save = vi.fn(async (input: { id: string; name: string }) => ({ id: input.id, name: input.name, kind: 'api' as const, available: true }))
    render(<ProviderDialog backend={backendWith(save)} initial={{ id: 'remote', name: 'Remote', kind: 'openai_compatible', providerType: 'generic', baseUrl: 'https://remote.example/v1', model: 'old', hasCredential: true, endpointBlocked: false, updatedAt: '2026-09-25T10:00:00Z' }} onSaved={() => undefined} onClose={() => undefined} />)
    await user.clear(screen.getByLabelText('URL base'))
    await user.type(screen.getByLabelText('URL base'), 'http://127.0.0.1:1234/v1')
    expect(screen.getByText(/novo token ou remova o token ativo/i)).toBeInTheDocument()
    const key = screen.getByLabelText('Novo token')
    expect(key).toBeRequired()
    await user.click(screen.getByRole('button', { name: 'Salvar provedor' }))
    expect(save).not.toHaveBeenCalled()
    await user.type(key, secret)
    await user.click(screen.getByRole('button', { name: 'Salvar provedor' }))
    expect(save).toHaveBeenCalledWith({ id: 'remote', name: 'Remote', providerType: 'generic', baseUrl: 'http://127.0.0.1:1234/v1', model: 'old', apiKey: secret, clearCredential: false })
  })

  it('clears the active token for a new loopback origin and explains history', async () => {
    const user = userEvent.setup()
    const save = vi.fn(async (input: { id: string; name: string }) => ({ id: input.id, name: input.name, kind: 'api' as const, available: true }))
    render(<ProviderDialog backend={backendWith(save)} initial={{ id: 'remote', name: 'Remote', kind: 'openai_compatible', providerType: 'generic', baseUrl: 'https://remote.example/v1', model: 'old', hasCredential: true, endpointBlocked: false, updatedAt: '2026-09-25T10:00:00Z' }} onSaved={() => undefined} onClose={() => undefined} />)
    await user.clear(screen.getByLabelText('URL base'))
    await user.type(screen.getByLabelText('URL base'), 'http://127.0.0.1:1234/v1')
    const key = screen.getByLabelText('Novo token')
    await user.type(key, secret)
    await user.click(screen.getByLabelText('Remover token ativo'))
    expect(key).toBeDisabled()
    expect(key).toHaveValue('')
    expect(screen.getByText(/histórico.*permanece/i)).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Salvar provedor' }))
    expect(save).toHaveBeenCalledWith({ id: 'remote', name: 'Remote', providerType: 'generic', baseUrl: 'http://127.0.0.1:1234/v1', model: 'old', apiKey: '', clearCredential: true })
  })

  it('warns about a legacy remote HTTP endpoint while retaining its URL', () => {
    render(<ProviderDialog backend={backendWith(vi.fn())} initial={{ id: 'legacy', name: 'Legado', kind: 'openai_compatible', providerType: 'generic', baseUrl: 'http://remote.example/v1', model: 'old', hasCredential: true, endpointBlocked: true, updatedAt: '2026-09-25T10:00:00Z' }} onSaved={() => undefined} onClose={() => undefined} />)
    expect(screen.getByLabelText('URL base')).toHaveValue('http://remote.example/v1')
    expect(screen.getByText(/HTTPS/)).toBeInTheDocument()
    fireEvent.change(screen.getByLabelText('URL base'), { target: { value: 'http://remote.example/models' } })
    expect(screen.getByText(/HTTPS necessário/)).toBeInTheDocument()
    fireEvent.change(screen.getByLabelText('URL base'), { target: { value: 'https://remote.example/models' } })
    expect(screen.queryByText(/HTTPS necessário/)).not.toBeInTheDocument()
  })

  it('edits an existing provider without requiring or exposing its saved key', async () => {
    const user = userEvent.setup()
    const save = vi.fn(async (input: { id: string; name: string }) => ({ id: input.id, name: input.name, kind: 'api' as const, available: true }))
    render(<ProviderDialog backend={backendWith(save)} initial={{ id: 'local', name: 'Local', kind: 'openai_compatible', providerType: 'generic', baseUrl: 'http://127.0.0.1:1234/v1', model: 'modelo-antigo', hasCredential: true, endpointBlocked: false, updatedAt: '2026-09-25T10:00:00Z' }} onSaved={() => undefined} onClose={() => undefined} />)
    expect(screen.getByRole('dialog', { name: 'Editar provedor' })).toBeInTheDocument()
    expect(screen.getByLabelText('Token opcional')).toHaveValue('')
    await user.clear(screen.getByLabelText('Modelo'))
    await user.type(screen.getByLabelText('Modelo'), 'modelo-novo')
    await user.click(screen.getByRole('button', { name: 'Salvar provedor' }))
    expect(save).toHaveBeenCalledWith({ id: 'local', name: 'Local', providerType: 'generic', baseUrl: 'http://127.0.0.1:1234/v1', model: 'modelo-novo', apiKey: '', clearCredential: false })
  })

  it('sends the key straight to the backend, clears it and shows only name and model', async () => {
    const user = userEvent.setup()
    const save = vi.fn(async (input: { id: string; name: string }) => ({ id: input.id, name: input.name, kind: 'api' as const, available: true }))
    const onSaved = vi.fn()
    const { container } = render(<ProviderDialog backend={backendWith(save)} onSaved={onSaved} onClose={() => undefined} />)
    expect(screen.getByRole('dialog', { name: 'Configurar provedor' })).toBeInTheDocument()
    expect(screen.getByText(/Mensagens e resultados de ferramentas seguem para a URL base escolhida/)).toBeInTheDocument()
    expect(screen.getByLabelText('Nome')).toHaveFocus()
    await user.type(screen.getByLabelText('Nome'), 'OpenRouter Pessoal')
    await user.click(within(screen.getByTestId('picker-provider-type')).getByRole('button'))
    await user.click(screen.getByRole('option', { name: 'OpenRouter' }))
    expect(within(screen.getByTestId('picker-provider-type')).getByRole('button')).toHaveTextContent('OpenRouter')
    await user.type(screen.getByLabelText('URL base'), 'https://openrouter.ai/api/v1')
    await user.type(screen.getByLabelText('Modelo'), 'openai/gpt-5')
    const key = screen.getByLabelText('Chave de API')
    expect(key).toHaveAttribute('type', 'password')
    expect(key).toHaveAttribute('autocomplete', 'off')
    await user.type(key, secret)
    await user.click(screen.getByRole('button', { name: 'Salvar provedor' }))

    expect(save).toHaveBeenCalledWith({ id: 'openrouter-pessoal', name: 'OpenRouter Pessoal', providerType: 'openrouter', baseUrl: 'https://openrouter.ai/api/v1', model: 'openai/gpt-5', apiKey: secret, clearCredential: false })
    expect(await screen.findByRole('status')).toHaveTextContent('Salvo: OpenRouter Pessoal · openai/gpt-5')
    expect(key).toHaveValue('')
    expect(container.innerHTML).not.toContain(secret)
    expect(JSON.stringify({ ...localStorage })).not.toContain(secret)
    expect(onSaved).toHaveBeenCalledWith({ id: 'openrouter-pessoal', name: 'OpenRouter Pessoal', kind: 'api', available: true })
  })

  it('clears the key and reports a stable message when saving fails', async () => {
    const user = userEvent.setup()
    const save = vi.fn(async () => { throw Object.assign(new Error('save provider: operation failed'), { cause: { code: 'invalid_input' } }) })
    render(<ProviderDialog backend={backendWith(save)} onSaved={() => undefined} onClose={() => undefined} />)
    await user.type(screen.getByLabelText('Nome'), 'Local')
    await user.click(within(screen.getByTestId('picker-provider-type')).getByRole('button'))
    await user.click(screen.getByRole('option', { name: 'LM Studio local' }))
    expect(screen.getByLabelText('Token opcional')).toBeInTheDocument()
    await user.type(screen.getByLabelText('URL base'), 'http://127.0.0.1:1234/v1')
    await user.type(screen.getByLabelText('Modelo'), 'qwen')
    await user.type(screen.getByLabelText('Token opcional'), secret)
    await user.click(screen.getByRole('button', { name: 'Salvar provedor' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('Os dados informados não são válidos.')
    expect(screen.getByLabelText('Token opcional')).toHaveValue('')
  })

  it('closes with Escape', async () => {
    const user = userEvent.setup()
    const onClose = vi.fn()
    render(<ProviderDialog backend={backendWith(vi.fn())} onSaved={() => undefined} onClose={onClose} />)
    await user.keyboard('{Escape}')
    expect(onClose).toHaveBeenCalled()
  })

  it('isolates background focus, stops Escape and restores focus when unmounted', async () => {
    const user = userEvent.setup()
    const trigger = document.createElement('button')
    trigger.textContent = 'Open provider'
    document.body.append(trigger)
    trigger.focus()
    const backgroundKeydown = vi.fn()
    document.addEventListener('keydown', backgroundKeydown)
    const { unmount } = render(<ProviderDialog backend={backendWith(vi.fn())} onSaved={() => undefined} onClose={() => undefined} />)
    expect(trigger.inert).toBe(true)
    await user.keyboard('{Escape}')
    expect(backgroundKeydown).not.toHaveBeenCalled()
    unmount()
    expect(trigger.inert).toBe(false)
    expect(trigger).toHaveFocus()
    document.removeEventListener('keydown', backgroundKeydown)
    trigger.remove()
  })

  it('derives catalog-safe profile IDs that never collide with CLI backends', () => {
    expect(profileID('Ollama Local')).toBe('ollama-local')
    expect(profileID('Configuração')).toBe('configuracao')
    expect(profileID('codex')).toBe('provider-codex')
    expect(profileID('!!!')).toBe('provider-local')
  })
})
