import type { AuthoringStage, Pipeline } from '../lib/backend'

export const stageDate = '2026-09-28T12:00:00Z'
export const stagePipeline: Pipeline = { id: 'pipeline-1', workspaceId: 'workspace-1', kind: 'ai_authoring', derivedFromPipelineId: '', discoveryFrozenVersion: 1, title: 'Pagamento auditável', objective: 'Decisão humana', currentStage: 'spec', stageStatus: { discovery: 'completed', spec: 'waiting_user', plan: 'pending', code: 'pending', eval: 'pending' }, revision: 5, artifacts: { discovery: { stage: 'discovery', version: 1, content: 'Registrar decisões sem executar pagamentos.', author: 'user', sourceSessionId: '', updatedAt: stageDate } }, createdAt: stageDate, updatedAt: stageDate }
export const stageSelection = { backendId: 'api-1', modelId: 'modelo-original', reasoningEffort: '', catalogRevision: 'rev-1', source: 'openai_models', destination: 'https://api.example.test:443', status: 'listed', confirmUnfiltered: false, confirmJitLoad: false, maxOutputTokens: 4096, contextLength: 128000, checkedAt: stageDate }
export const stageReadback: AuthoringStage = {
  pipelineId: 'pipeline-1', stage: 'spec', pipelineRevision: 5, discoveryVersion: 1, revision: 2, state: 'waiting_user', cancellationPending: false, cancellationAttemptId: '', artifactVersion: 1, attemptCount: 1, inputBudgetRemaining: 100000, outputBudgetRemaining: 20000, createdAt: stageDate, updatedAt: stageDate,
  attempts: [{ id: 'attempt-1', requestId: 'request-valid-0001', artifactVersion: 1, status: 'completed', sessionId: 'session-original', errorCode: '', cancellationState: '', source: { discoveryVersion: 1, discoveryHash: 'discovery-hash', brainstormRunId: 'brainstorm-1', synthesisVersion: 1, discoveryBypassReason: '', specVersion: 0, specHash: '', specBypassReason: '', previousArtifactVersion: 0, feedback: '' }, selection: stageSelection, reservedInputTokens: 500, reservedOutputTokens: 4096, usage: null, createdAt: stageDate, updatedAt: stageDate }],
  artifacts: [{ version: 1, content: { summary: 'Pagamento auditável', requirements: ['Registrar decisão humana'], nonGoals: ['Executar pagamento'], acceptanceCriteria: [{ id: 'AC-1', criterion: 'Decisão persistida' }] }, contentHash: 'content-hash', author: 'ai', attemptId: 'attempt-1', sourceSessionId: 'session-original', status: 'waiting_user', createdAt: stageDate, updatedAt: stageDate }], actions: [],
}
