package application

import (
	"bytes"
	"slices"
	"strings"
	"unicode/utf8"

	"github.com/persioflexa/harflex/internal/id"
)

type toolAlias struct {
	public string
	done   bool
}

// The journal owns this registry under its mutex. Actual IDs never cross the
// journal/DTO boundary; historical public IDs remain valid correlation keys.
type publicAliases struct {
	tools           map[string]toolAlias
	actualTools     map[string]string
	approvals       map[string]string
	actualApprovals map[string]string
	activeApprovals map[string]bool
}

func newPublicAliases() *publicAliases {
	return &publicAliases{tools: map[string]toolAlias{}, actualTools: map[string]string{}, approvals: map[string]string{}, actualApprovals: map[string]string{}, activeApprovals: map[string]bool{}}
}

func (a *publicAliases) close() {
	clear(a.tools)
	clear(a.actualTools)
	clear(a.approvals)
	clear(a.actualApprovals)
	clear(a.activeApprovals)
}

func (a *publicAliases) tool(actual string, fresh bool, patterns [][]byte) string {
	if actual == "" {
		return ""
	}
	if current, ok := a.tools[actual]; ok && !fresh {
		return current.public
	}
	public := newPublicAlias("tool-", patterns)
	a.tools[actual] = toolAlias{public: public}
	a.actualTools[public] = actual
	return public
}

func (a *publicAliases) approval(actual string, requested bool, patterns [][]byte) string {
	if actual == "" {
		return ""
	}
	if public := a.approvals[actual]; public != "" {
		if !requested {
			return public
		}
		a.activeApprovals[public] = false
	}
	public := newPublicAlias("approval-", patterns)
	a.approvals[actual] = public
	a.actualApprovals[public] = actual
	a.activeApprovals[public] = requested
	return public
}

func (a *publicAliases) transform(typ string, value any, patterns [][]byte) {
	object, ok := value.(map[string]any)
	if !ok {
		return
	}
	if typ == "message.assistant" {
		if calls, ok := object["toolCalls"].([]any); ok {
			for _, raw := range calls {
				if call, ok := raw.(map[string]any); ok {
					if actual, ok := call["id"].(string); ok {
						call["id"] = a.tool(actual, true, patterns)
					}
				}
			}
		}
	}
	if strings.HasPrefix(typ, "tool.") || strings.HasPrefix(typ, "approval.") || strings.HasPrefix(typ, "message.") {
		if actual, ok := object["toolCallId"].(string); ok {
			fresh := (typ == "tool.called" || typ == "tool.updated") && a.tools[actual].done
			object["toolCallId"] = a.tool(actual, fresh, patterns)
			switch typ {
			case "tool.completed", "tool.failed", "tool.skipped", "tool.denied":
				current := a.tools[actual]
				current.done = true
				a.tools[actual] = current
			}
		}
	}
	if strings.HasPrefix(typ, "approval.") {
		if actual, ok := object["approvalId"].(string); ok {
			public := a.approval(actual, typ == "approval.requested", patterns)
			object["approvalId"] = public
			if typ == "approval.approved" || typ == "approval.denied" {
				a.activeApprovals[public] = false
			}
		}
	}
	switch typ {
	case "run.completed", "run.failed", "run.cancelled", "run.interrupted":
		for public := range a.activeApprovals {
			a.activeApprovals[public] = false
		}
	}
}

func containsCredential(value string, patterns [][]byte) bool {
	for _, pattern := range patterns {
		if len(pattern) > 0 && bytes.Contains([]byte(value), pattern) {
			return true
		}
	}
	return false
}

func newPublicAlias(prefix string, patterns [][]byte) string {
	if containsCredential(prefix, patterns) {
		prefix = ""
	}
	for range 32 {
		candidate := prefix + id.New()
		if !containsCredential(candidate, patterns) {
			return candidate
		}
	}
	// Very short credentials can exclude most ASCII tokens. Encode random bytes
	// with two absent Unicode runes instead of retrying without a bound.
	runes := make([]rune, 0, 2)
	for candidate := rune(0xE000); candidate <= utf8.MaxRune && len(runes) < 2; candidate++ {
		present := false
		for _, pattern := range patterns {
			if bytes.Contains(pattern, []byte(string(candidate))) {
				present = true
				break
			}
		}
		if !present {
			runes = append(runes, candidate)
		}
	}
	var value strings.Builder
	for _, character := range []byte(id.New()) {
		for shift := 7; shift >= 0; shift-- {
			value.WriteRune(runes[(character>>shift)&1])
		}
	}
	return value.String()
}

// Live operational aliases have already been generated by this session. Other
// strings, including model-provided tool names, are content unless they match
// a bounded app-owned enum. Audit export intentionally does not use this policy.
func redactLiveEventValue(value any, typ string, patterns [][]byte, aliases *publicAliases) any {
	object, ok := value.(map[string]any)
	if !ok {
		return redactAuditValue(value, patterns)
	}
	for key, item := range object {
		text, _ := item.(string)
		if key == "toolCallId" && aliases.actualTools[text] != "" {
			continue
		}
		if key == "approvalId" && aliases.actualApprovals[text] != "" {
			continue
		}
		if safeLiveEnum(typ, key, text) {
			continue
		}
		if key == "toolCalls" && typ == "message.assistant" {
			if calls, ok := item.([]any); ok {
				for index, raw := range calls {
					if call, ok := raw.(map[string]any); ok {
						for field, value := range call {
							public, _ := value.(string)
							if field != "id" || aliases.actualTools[public] == "" {
								call[field] = redactAuditValue(value, patterns)
							}
						}
					} else {
						calls[index] = redactAuditValue(raw, patterns)
					}
				}
				continue
			}
		}
		object[key] = redactAuditValue(item, patterns)
	}
	return object
}

func safeLiveEnum(typ, key, value string) bool {
	switch key {
	case "stream":
		return typ == "tool.updated" && slices.Contains([]string{"stdout", "stderr", "system"}, value)
	case "role":
		return slices.Contains([]string{"message.user", "message.assistant", "message.tool"}, typ) && slices.Contains([]string{"user", "assistant", "tool", "system"}, value)
	case "risk":
		return typ == "approval.requested" && slices.Contains([]string{"read_only", "write", "shell", "network", "destructive"}, value)
	case "reason", "errorCode":
		if !slices.Contains([]string{"tool.failed", "tool.denied", "tool.skipped", "run.completed", "run.failed", "run.cancelled", "run.interrupted"}, typ) {
			return false
		}
		return slices.Contains([]string{"", "approval_denied", "tool_failed", "execution_failed", "unknown_tool", "policy_denied", "cancelled", "turn_limit", "skipped_after_failure", "invalid_tool_result", "app_restart",
			// Failures a tool reports so the model can adjust.
			"not_found", "invalid_arguments", "not_a_file", "not_a_directory", "no_match", "ambiguous_match", "binary_file", "range_required", "permission_denied", "exit_status", "timeout", "mcp_error"}, value)
	}
	return false
}
