// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Change describes one sorted difference between two manifests.
 */
export interface Change {
    "path": string;
    "kind": ChangeKind;
}

/**
 * ChangeKind is one manifest-level difference. File content, Git-relevant mode,
 * entry type, and symlink text are separate so mode-only and target-only changes
 * remain visible without dereferencing links.
 */
export enum ChangeKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ChangeAdded = "added",
    ChangeDeleted = "deleted",
    ChangeContent = "content",
    ChangeMode = "mode",
    ChangeType = "type",
    ChangeTarget = "target",
};

/**
 * Entry records only Git-relevant mode information: files normalize to
 * 100644/100755, directories to 040000, and symlinks to 120000. Private-copy
 * permissions therefore do not hide executable-bit changes.
 */
export interface Entry {
    "path": string;
    "type": EntryType;
    "mode": number;
    "size": number;
    "sha256": string;
    "target"?: string;
}

/**
 * EntryType describes the kind of filesystem node represented in a manifest.
 */
export enum EntryType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    EntryFile = "file",
    EntryDirectory = "directory",
    EntrySymlink = "symlink",
};

/**
 * Exclusion records a path deliberately omitted from the snapshot. Reasons are
 * intentionally narrow and do not claim to identify every secret in a project.
 */
export interface Exclusion {
    "path": string;
    "reason": string;
}

/**
 * Manifest is a deterministic, bounded description of one project tree.
 */
export interface Manifest {
    "version": number;
    "entries": Entry[] | null;
    "excluded": Exclusion[] | null;

    /**
     * FileCount counts included regular files and symlinks, not directories.
     */
    "fileCount": number;

    /**
     * TotalBytes includes file contents and textual symlink targets.
     */
    "totalBytes": number;
    "hash": string;
}
