import { expect, test } from '@playwright/test'
import { undersizedTargets } from './targets'

for (const width of [320, 768, 900, 1024, 1440]) {
  test(`Casual chat history stays usable at ${width}px`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: 900 })
    await page.addInitScript(() => localStorage.setItem('harflex:view-mode', 'casual'))
    await page.goto('/e2e/fixture.html?scenario=casual-history')
    const modeSwitch = page.getByRole('group', { name: 'Modo de uso' })
    await expect(modeSwitch.getByRole('button', { name: 'Casual' })).toHaveAttribute('aria-pressed', 'true')
    await expect(modeSwitch.getByRole('button', { name: 'Professional' })).toHaveAttribute('aria-pressed', 'false')
    await page.getByLabel('Caminho da pasta').fill('/Users/dev/todo-app')
    await page.getByRole('button', { name: 'Abrir projeto' }).click()

    if (width < 768) {
      const historyToggle = page.getByRole('button', { name: 'Abrir histórico de chats' })
      await historyToggle.click()
      await expect(page.getByRole('dialog', { name: 'Histórico de conversas' })).toBeVisible()
      const closeHistory = page.getByRole('button', { name: 'Fechar histórico' })
      const modeSwitch = page.getByRole('button', { name: 'Mudar para Professional' })
      await expect(closeHistory).toBeFocused()
      await page.keyboard.press('Shift+Tab')
      await expect(modeSwitch).toBeFocused()
      await page.keyboard.press('Tab')
      await expect(closeHistory).toBeFocused()
      await page.keyboard.press('Escape')
      await expect(historyToggle).toBeFocused()
      await historyToggle.click()
      await expect(closeHistory).toBeFocused()
      await page.screenshot({ path: testInfo.outputPath('casual-history-drawer-320.png'), fullPage: true })
    }
    const search = page.getByRole('textbox', { name: 'Buscar conversas' })
    await search.fill('lista TODO')
    const chat = page.getByRole('button', { name: /Criar uma lista TODO em TypeScript/ })
    await expect(chat).toBeVisible()
    await chat.click()
    await expect(page.getByText('Vou organizar a tarefa em uma lista.')).toBeVisible()
    await expect(page.getByLabel('Mensagem')).toBeEnabled()
    await expect(page.getByRole('button', { name: 'Atividade', exact: true })).toHaveAttribute('aria-expanded', 'false')
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
    await page.screenshot({ path: testInfo.outputPath(`casual-chat-${width}.png`), fullPage: true })

    if (width < 768) await page.getByRole('button', { name: 'Abrir histórico de chats' }).click()
    const tools = page.getByRole('navigation', { name: 'Ferramentas' })
    await page.getByText('Ferramentas', { exact: true }).click()
    await expect(tools.getByRole('button')).toHaveCount(17)
    await tools.getByRole('button', { name: 'Pipelines' }).click()
    await expect(page.getByRole('heading', { name: 'Pipelines SDD' })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)

    expect(await undersizedTargets(page)).toEqual([])
  })
}

test('a non-resumable Codex chat carries its request into a new Casual chat and runs only after review', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.addInitScript(() => localStorage.setItem('harflex:view-mode', 'casual'))
  await page.goto('/e2e/fixture.html?scenario=casual-cli-recovery')
  await page.getByLabel('Caminho da pasta').fill('/Users/dev/todo-app')
  await page.getByRole('button', { name: 'Abrir projeto' }).click()
  const failedChat = page.getByRole('button', { name: /Corrigir o bloqueio do fluxo Code/ })
  await failedChat.click()
  await expect(failedChat).toHaveAttribute('aria-current', 'true')
  await expect(page.getByRole('list', { name: 'Conversa' }).getByText('Corrigir o bloqueio do fluxo Code', { exact: true })).toBeVisible()
  await expect(page.getByText(/Somente leitura: esta execução foi encerrada/)).toBeVisible()
  // The closed run is not locked away: the box stays, and what is typed goes to a new conversation.
  await expect(page.getByLabel('Mensagem')).toBeEnabled()
  await page.getByRole('button', { name: 'Continuar em novo chat' }).click()
  const initial = page.getByLabel('Mensagem inicial')
  await expect(initial).toHaveValue('Corrigir o bloqueio do fluxo Code')
  await expect(page.getByRole('button', { name: 'Iniciar chat' })).toBeDisabled()
  await page.getByRole('button', { name: 'Consultar modelos' }).click()
  const model = page.getByRole('combobox', { name: 'Modelo da sessão' })
  await model.fill('Modelo Codex de teste')
  await page.getByRole('option', { name: 'Modelo Codex de teste' }).click()
  const effort = page.getByTestId('picker-session-effort').getByRole('button')
  await effort.click()
  await page.getByRole('option', { name: 'medium' }).click()
  await expect(page.getByRole('button', { name: 'Iniciar chat' })).toBeEnabled()
  await page.getByRole('button', { name: 'Iniciar chat' }).click()
  const approval = page.getByRole('group', { name: 'Aprovação necessária' })
  await expect(approval).toBeVisible()
  await approval.getByRole('button', { name: 'Aprovar' }).click()
  await expect(page.getByText('Concluído', { exact: true })).toBeVisible()
})

test('a closed Codex chat takes the next message into a new conversation that carries it', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.addInitScript(() => localStorage.setItem('harflex:view-mode', 'casual'))
  await page.goto('/e2e/fixture.html?scenario=casual-cli-continuation')
  await page.getByLabel('Caminho da pasta').fill('/Users/dev/todo-app')
  await page.getByRole('button', { name: 'Abrir projeto' }).click()
  await page.getByRole('button', { name: /Corrigir o bloqueio do fluxo Code/ }).click()
  await expect(page.getByText(/Somente leitura: esta execução foi encerrada/)).toBeVisible()
  const box = page.getByLabel('Mensagem')
  await expect(box).toBeEnabled()
  await expect(box).toHaveAttribute('placeholder', /Continue de onde parou/)
  await box.fill('Tente de novo, agora sem o bloqueio')
  await box.press('Enter')

  // What opened is a new conversation: it shows what was written and keeps the old one folded under it.
  const approval = page.getByRole('group', { name: 'Aprovação necessária' })
  await expect(approval).toBeVisible()
  const log = page.getByRole('list', { name: 'Conversa' })
  await expect(log.getByText('Tente de novo, agora sem o bloqueio', { exact: true })).toBeVisible()
  await expect(log.getByText('Primeiro pedido nela:')).toBeHidden()
  await log.getByText('Contexto levado da conversa anterior').click()
  await expect(log.getByText('Primeiro pedido nela:')).toBeVisible()
  await expect(log.getByText('Parei antes de mexer no fluxo.', { exact: false }).first()).toBeVisible()
  // The old chat stays in the sidebar as it was; the open conversation is the new one, not read-only.
  await expect(page.getByText(/Somente leitura: esta execução foi encerrada/)).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(1440)
  await approval.getByRole('button', { name: 'Aprovar' }).click()
  await expect(page.getByText('Concluído', { exact: true })).toBeVisible()
  await expect(box).toBeEnabled()
  await expect(box).toHaveValue('')
})

test('the Casual sidebar keeps a read-only Codex request when opening a new chat', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.addInitScript(() => localStorage.setItem('harflex:view-mode', 'casual'))
  await page.goto('/e2e/fixture.html?scenario=casual-cli-recovery')
  await page.getByLabel('Caminho da pasta').fill('/Users/dev/todo-app')
  await page.getByRole('button', { name: 'Abrir projeto' }).click()
  const failedChat = page.getByRole('button', { name: /Corrigir o bloqueio do fluxo Code/ })
  await failedChat.click()
  await expect(failedChat).toHaveAttribute('aria-current', 'true')
  await expect(page.getByRole('list', { name: 'Conversa' }).getByText('Corrigir o bloqueio do fluxo Code', { exact: true })).toBeVisible()
  await expect(page.getByText(/Somente leitura: esta execução foi encerrada/)).toBeVisible()
  await page.getByRole('button', { name: 'Novo chat', exact: true }).click()
  await expect(page.getByLabel('Mensagem inicial')).toHaveValue('Corrigir o bloqueio do fluxo Code')
  await expect(page.getByRole('button', { name: 'Iniciar chat' })).toBeDisabled()
})

test('keeps the recovery request safe while a Codex chat history is replaying', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.addInitScript(() => localStorage.setItem('harflex:view-mode', 'casual'))
  await page.goto('/e2e/fixture.html?scenario=casual-cli-recovery-replay')
  await page.getByLabel('Caminho da pasta').fill('/Users/dev/todo-app')
  await page.getByRole('button', { name: 'Abrir projeto' }).click()
  await page.getByRole('button', { name: /Recuperar o pedido durante a abertura do histórico/ }).click()

  const continueButton = page.getByRole('button', { name: 'Continuar em novo chat' })
  await expect(page.getByText('Carregando conversa… escolha outro chat para cancelar esta abertura.', { exact: true })).toBeVisible()
  await expect(continueButton).toBeDisabled()
  await page.evaluate(() => (window as unknown as { harflexSynthetic?: { releaseReplay(): void } }).harflexSynthetic?.releaseReplay())
  await expect(page.getByRole('list', { name: 'Conversa' }).getByText('Recuperar o pedido durante a abertura do histórico', { exact: true })).toBeVisible()
  await expect(continueButton).toBeEnabled()
  await continueButton.click()
  await expect(page.getByLabel('Mensagem inicial')).toHaveValue('Recuperar o pedido durante a abertura do histórico')
  await expect(page.getByRole('button', { name: 'Iniciar chat' })).toBeDisabled()
})

test('switching Casual and Professional keeps the same active conversation', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.addInitScript(() => localStorage.setItem('harflex:view-mode', 'casual'))
  await page.goto('/e2e/fixture.html?scenario=casual-history')
  await page.getByLabel('Caminho da pasta').fill('/Users/dev/todo-app')
  await page.getByRole('button', { name: 'Abrir projeto' }).click()
  await page.getByRole('button', { name: /Criar uma lista TODO em TypeScript/ }).click()

  const modeSwitch = page.getByRole('group', { name: 'Modo de uso' })
  await expect(modeSwitch.getByRole('button', { name: 'Casual' })).toHaveAttribute('aria-pressed', 'true')
  await modeSwitch.getByRole('button', { name: 'Professional' }).click()
  await expect(page.getByRole('navigation', { name: 'SDD Pipeline' })).toBeVisible()
  await expect(page.getByLabel('Mensagem')).toBeEnabled()
  await expect(page.getByText('Vou organizar a tarefa em uma lista.')).toBeVisible()
  await expect(modeSwitch.getByRole('button', { name: 'Professional' })).toHaveAttribute('aria-pressed', 'true')
  await modeSwitch.getByRole('button', { name: 'Casual' }).click()
  await expect(page.getByRole('button', { name: /Criar uma lista TODO em TypeScript/ })).toHaveAttribute('aria-current', 'true')
  await expect(page.getByLabel('Mensagem')).toBeEnabled()
  await expect(modeSwitch.getByRole('button', { name: 'Casual' })).toHaveAttribute('aria-pressed', 'true')
})

for (const width of [320, 1440]) {
  test(`live work feedback names the active action and respects reduced motion at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.addInitScript(() => localStorage.setItem('harflex:view-mode', 'casual'))
    await page.goto('/e2e/fixture.html?scenario=activity-live')
    await page.getByLabel('Caminho da pasta').fill('/Users/dev/todo-app')
    await page.getByRole('button', { name: 'Abrir projeto' }).click()

    if (width < 768) {
      await page.getByRole('button', { name: 'Abrir histórico de chats' }).click()
      await expect(page.getByRole('dialog', { name: 'Histórico de conversas' })).toBeVisible()
    }
    await page.getByRole('button', { name: /Implementar um arquivo de teste/ }).click()
    const runStatus = page.locator('.run-status')
    await expect(runStatus).toContainText('Escrevendo arquivo')
    await expect(runStatus).toContainText('src/todo.js')
    await expect(runStatus).toHaveAttribute('aria-live', 'polite')
    await expect(runStatus).toHaveAttribute('aria-atomic', 'true')
    expect(await runStatus.locator('.run-status-motion i').first().evaluate(node => getComputedStyle(node).animationName)).toBe('activity-dots')

    await page.getByRole('button', { name: 'Atividade', exact: true }).click()
    const activity = page.getByLabel('Atividade do trabalho')
    await expect(activity.getByText('Em execução · ações atualizadas ao vivo')).toBeVisible()
    await expect(activity.locator('.visually-hidden')).toHaveText('Nova atividade: Ferramenta iniciada · write')
    await expect(activity.getByText('write', { exact: true })).toBeVisible()
    await expect(activity.getByText('external.session.bound')).toHaveCount(0)
    expect(await activity.locator('.activity-live svg').evaluate(node => getComputedStyle(node).animationName)).toBe('activity-pulse')
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)

    await page.emulateMedia({ reducedMotion: 'reduce' })
    expect(await runStatus.locator('.run-status-motion i').first().evaluate(node => getComputedStyle(node).animationName)).toBe('none')
    expect(await activity.locator('.activity-live svg').evaluate(node => getComputedStyle(node).animationName)).toBe('none')
    await expect(runStatus).toContainText('Escrevendo arquivo')
    await expect(activity.getByText('Em execução · ações atualizadas ao vivo')).toBeVisible()
  })
}
