import { expect, test } from './locale'

for (const width of [320, 768, 900, 1440]) {
  test(`local channel persists deliberate file exchange at ${width}px`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/e2e/fixture.html?scenario=channels')
    await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/api-faturas')
    await page.getByRole('button', { name: 'Abrir projeto' }).click()
    if (width < 768) await page.getByRole('button', { name: 'Abrir navegação' }).click()
    await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Canais' }).click()
    await expect(page.getByRole('heading', { name: 'Canais locais' })).toBeVisible()
    await page.getByLabel('Nome do canal').fill('Equipe')
    await page.getByLabel('Pasta no projeto').fill('channels/equipe')
    await page.getByRole('button', { name: 'Configurar canal' }).click()
    await expect(page.getByText('Nenhuma mensagem no histórico')).toBeVisible()
    await page.getByRole('button', { name: 'Importar inbox' }).click()
    await expect(page.getByText('Pedido local de revisão.')).toBeVisible()
    await page.getByLabel('Resposta').fill('Revisão concluída.')
    await page.getByRole('button', { name: 'Enviar resposta' }).click()
    await expect(page.getByText('Revisão concluída.')).toBeVisible()
    await expect(page.getByText('Enviado')).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
    await page.screenshot({ path: info.outputPath(`channels-${width}.png`), fullPage: true })
    await page.reload()
    await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/api-faturas')
    await page.getByRole('button', { name: 'Abrir projeto' }).click()
    if (width < 768) await page.getByRole('button', { name: 'Abrir navegação' }).click()
    await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Canais' }).click()
    await expect(page.getByText('Revisão concluída.')).toBeVisible()
    await expect(page.getByText('Pedido local de revisão.')).toBeVisible()
  })
}

test('uncertain send keeps its request across channel switching and manual retry', async ({ page }) => {
  await page.setViewportSize({ width: 900, height: 900 })
  await page.goto('/e2e/fixture.html?scenario=channels-uncertain')
  await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/api-faturas')
  await page.getByRole('button', { name: 'Abrir projeto' }).click()
  await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Canais' }).click()
  await page.getByLabel('Nome do canal').fill('Equipe')
  await page.getByLabel('Pasta no projeto').fill('channels/equipe')
  await page.getByRole('button', { name: 'Configurar canal' }).click()
  await page.getByLabel('Nome do canal').fill('Outro')
  await page.getByLabel('Pasta no projeto').fill('channels/outro')
  await page.getByRole('button', { name: 'Configurar canal' }).click()
  await page.getByRole('button', { name: /Equipe/ }).click()
  await page.getByLabel('Resposta').fill('Resposta única.')
  await page.getByRole('button', { name: 'Enviar resposta' }).click()
  await expect(page.getByRole('alert').last()).toBeVisible()
  await page.getByRole('button', { name: /Outro/ }).click()
  await expect(page.getByLabel('Resposta')).toHaveValue('')
  await page.getByLabel('Resposta').fill('Rascunho de outro canal')
  await page.getByRole('button', { name: /Equipe/ }).click()
  await expect(page.getByLabel('Resposta')).toHaveValue('Resposta única.')
  await page.getByRole('button', { name: 'Enviar resposta' }).click()
  await expect(page.getByText('Resposta única.')).toBeVisible()
  await expect(page.getByLabel('Resposta')).toHaveValue('')
  const attempts = await page.evaluate(() => JSON.parse(sessionStorage.getItem('harflex:synthetic-channels-uncertain:attempts') ?? '[]') as string[])
  expect(attempts).toHaveLength(2)
  expect(attempts[0]).toBe(attempts[1])
  expect(attempts[0]).toMatch(/^[a-f0-9]{32}$/)
  await page.getByRole('button', { name: /Outro/ }).click()
  await expect(page.getByLabel('Resposta')).toHaveValue('Rascunho de outro canal')
})
