import { expect, test, type Page } from './locale'

async function settleScroll(page: Page) {
  await page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))))
}

for (const width of [320, 768, 900, 1024, 1440]) {
  test(`Ion picker preserves geometry and dialog focus at ${width}px`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/e2e/fixture.html?scenario=settings')
    await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/api-faturas')
    await page.getByRole('button', { name: 'Abrir projeto' }).click()
    if (width < 768) await page.getByRole('button', { name: 'Abrir navegação' }).click()
    await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Configurações' }).click()
    const opener = page.getByRole('button', { name: 'Adicionar provedor' })
    await opener.click()
    const dialog = page.getByRole('dialog', { name: 'Configurar provedor' })
    const trigger = page.getByTestId('picker-provider-type').getByRole('button')
    await expect(trigger).toHaveAccessibleName(/Tipo de provedor/)
    await trigger.scrollIntoViewIfNeeded()
    await settleScroll(page)
    expect((await trigger.boundingBox())?.height).toBe(48)
    await trigger.click()
    const list = page.getByRole('listbox')
    await expect(list).toBeVisible()
    expect((await page.getByRole('option', { name: 'LM Studio local' }).boundingBox())?.height ?? 0).toBeGreaterThanOrEqual(44)
    const popover = page.locator('[data-ion-picker-popover]')
    const bounds = await popover.boundingBox()
    expect(bounds).not.toBeNull()
    expect(bounds!.x).toBeGreaterThanOrEqual(0)
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(width)
    expect(bounds!.y).toBeGreaterThanOrEqual(0)
    expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(900)
    await page.keyboard.press('End')
    await expect(page.getByRole('option', { name: 'Ollama local' })).toHaveAttribute('data-focused', 'true')
    await page.keyboard.press('Home')
    await expect(page.getByRole('option', { name: 'API compatível' })).toHaveAttribute('data-focused', 'true')
    await page.screenshot({ path: info.outputPath(`ion-picker-list-${width}.png`) })
    await page.keyboard.press('Escape')
    await expect(list).not.toBeVisible()
    await expect(dialog).toBeVisible()
    await expect(trigger).toBeFocused()
    await page.keyboard.press('Tab')
    await expect(dialog.getByLabel('URL base')).toBeFocused()
    await page.keyboard.press('Shift+Tab')
    await expect(trigger).toBeFocused()
    await trigger.click()
    await page.keyboard.press('End')
    await page.keyboard.press('Enter')
    await expect(trigger).toContainText('Ollama local')
    await trigger.click()
    await page.getByRole('option', { name: 'LM Studio local' }).click()
    await expect(trigger).toContainText('LM Studio local')
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
    await page.screenshot({ path: info.outputPath(`ion-picker-selected-${width}.png`), fullPage: true })
    await page.keyboard.press('Escape')
    await expect(dialog).not.toBeVisible()
    await expect(opener).toBeFocused()
  })
}

test('long timezone search retains only chosen value at 320px and reduced motion', async ({ page }, info) => {
  await page.setViewportSize({ width: 320, height: 720 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/e2e/fixture.html?scenario=schedules')
  await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/api-faturas')
  await page.getByRole('button', { name: 'Abrir projeto' }).click()
  await page.getByRole('button', { name: 'Abrir navegação' }).click()
  await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Agendamentos' }).click()
  const search = page.getByTestId('picker-schedule-timezone').getByRole('combobox')
  await search.scrollIntoViewIfNeeded()
  await settleScroll(page)
  await search.fill('')
  await expect(page.getByRole('listbox')).toBeVisible()
  expect(await page.getByRole('option').count()).toBeGreaterThan(10)
  await page.screenshot({ path: info.outputPath('ion-picker-timezone-list-320.png') })
  await search.fill('timezone-not-found')
  await expect(page.getByText('Nenhuma opção encontrada.')).toBeVisible()
  await search.fill('America/Sao_Paulo')
  await expect(page.getByRole('option', { name: 'America/Sao_Paulo', exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath('ion-picker-timezone-filter-320.png') })
  await page.getByRole('option', { name: 'America/Sao_Paulo', exact: true }).click()
  await expect(search).toHaveValue('America/Sao_Paulo')
  await search.focus()
  await page.keyboard.press('ArrowDown')
  const popover = page.locator('[data-ion-picker-popover]')
  await expect(popover).toBeVisible()
  expect(await popover.evaluate(element => getComputedStyle(element).transitionDuration)).toBe('0s')
  await page.keyboard.press('Escape')
  await expect(popover).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320)
})

for (const width of [320, 768, 900, 1024, 1440]) {
  test(`long document option wraps and remains selectable at ${width}px`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/e2e/ion-picker.html')
    const picker = page.getByTestId('picker-browser-document')
    const search = picker.getByRole('combobox')
    await search.fill('plataforma')
    const longName = 'docs/plataforma/fluxos-e-integracoes/decisoes-de-discovery-e-revisao-de-implementacao.md'
    const option = page.getByRole('option', { name: longName })
    await expect(option).toBeVisible()
    await expect(option.locator('span')).toHaveAttribute('title', longName)
    const box = await option.boundingBox()
    expect(box).not.toBeNull()
    expect(box!.x).toBeGreaterThanOrEqual(0)
    expect(box!.x + box!.width).toBeLessThanOrEqual(width)
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
    await page.screenshot({ path: info.outputPath(`ion-picker-long-document-${width}.png`) })
    await page.keyboard.press('ArrowDown')
    await page.keyboard.press('Enter')
    await expect(search).toHaveValue(longName)
    await expect(page.getByTestId('selected-value')).toHaveText('long-document')
  })
}

for (const width of [320, 1024]) {
  test(`searchable picker has one visible keyboard focus ring at ${width}px`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/e2e/ion-picker.html')
    const picker = page.getByTestId('picker-browser-document')
    const search = picker.getByRole('combobox')
    await search.fill('plataforma')
    await expect(page.getByRole('option', { name: /docs\/plataforma\/fluxos-e-integracoes/ })).toBeVisible()
    const focus = await picker.evaluate(element => {
      const input = element.querySelector<HTMLInputElement>('.ion-picker-input')!
      const group = element.querySelector<HTMLElement>('.ion-picker-group')!
      return {
        inputOutlineWidth: getComputedStyle(input).outlineWidth,
        groupOutlineWidth: getComputedStyle(group).outlineWidth,
        groupOutlineStyle: getComputedStyle(group).outlineStyle,
        groupOutlineColor: getComputedStyle(group).outlineColor,
      }
    })
    expect(focus.groupOutlineStyle).toBe('solid')
    expect(focus.groupOutlineWidth).toBe('2px')
    expect(focus.groupOutlineColor).toBe('rgb(92, 242, 166)')
    expect(focus.inputOutlineWidth).toBe('0px')
    await page.screenshot({ path: info.outputPath(`ion-picker-single-focus-${width}.png`) })
  })
}

test('ComboBox mantém valor vazio e texto coerentes no Chromium', async ({ page }) => {
  await page.goto('/e2e/ion-picker.html')
  const input = page.getByRole('combobox', { name: 'Documento' })
  const selected = page.getByTestId('selected-value')
  await expect(input).toHaveValue('Código')

  await page.getByTestId('picker-browser-document').locator('.ion-picker-chevron').click()
  await page.getByRole('option', { name: 'Todos os documentos' }).click()
  await expect(selected).toHaveText('vazio')
  await expect(input).toHaveValue('Todos os documentos')
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await page.getByTestId('picker-browser-document').locator('.ion-picker-chevron').click()
  await expect(page.getByRole('option', { name: 'Arquitetura' })).toBeVisible()
  await page.keyboard.press('Escape')

  await input.fill('arq')
  await expect(selected).toHaveText('vazio')
  await expect(page.getByRole('option', { name: 'Arquitetura' })).toBeVisible()
  await page.getByRole('option', { name: 'Arquitetura' }).click()
  await expect(selected).toHaveText('a')
  await expect(input).toHaveValue('Arquitetura')

  await input.fill('')
  await expect(selected).toHaveText('vazio')
  await expect(input).toHaveValue('')
  await input.blur()
  await expect(input).not.toHaveValue('Arquitetura')
})

test('workflow obrigatório só permite enviar uma opção selecionada', async ({ page }) => {
  await page.goto('/e2e/ion-picker.html')
  const form = page.getByTestId('required-form')
  const input = form.getByRole('combobox', { name: 'Workflow' })
  const selected = page.getByTestId('workflow-value')
  const submissions = page.getByTestId('workflow-submissions')
  await expect(input).toHaveValue('Workflow B')

  await form.getByRole('button', { name: 'Reset workflow' }).click()
  await expect(selected).toHaveText('vazio')
  await expect(input).toHaveValue('')
  await expect(page.getByRole('listbox')).toHaveCount(0)
  expect(await form.evaluate(element => (element as HTMLFormElement).checkValidity())).toBe(false)
  await form.getByRole('button', { name: 'Salvar workflow' }).click()
  await expect(submissions).toHaveText('0')

  await input.fill('inexistente')
  expect(await form.evaluate(element => (element as HTMLFormElement).checkValidity())).toBe(false)
  await form.evaluate(element => (element as HTMLFormElement).requestSubmit())
  await expect(submissions).toHaveText('0')
  await page.keyboard.press('Escape')

  await input.fill('Workflow')
  await page.getByRole('option', { name: 'Workflow B' }).click()
  await expect(selected).toHaveText('b')
  expect(await form.evaluate(element => (element as HTMLFormElement).checkValidity())).toBe(true)
  await form.getByRole('button', { name: 'Salvar workflow' }).click()
  await expect(submissions).toHaveText('1')

  await form.locator('.ion-picker-chevron').click()
  await page.getByRole('option', { name: 'Escolha workflow' }).click()
  await expect(selected).toHaveText('vazio')
  await expect(input).toHaveValue('')
  expect(await form.evaluate(element => (element as HTMLFormElement).checkValidity())).toBe(false)
  await page.keyboard.press('Escape')
  await form.getByRole('button', { name: 'Salvar workflow' }).click()
  await expect(submissions).toHaveText('1')
})
