import { expect, test } from './locale'

for (const width of [320, 768, 900, 1024, 1440]) {
  test(`local knowledge import, search and provenance work at ${width}px`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/e2e/fixture.html?scenario=knowledge')
    await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/api-faturas')
    await page.getByRole('button', { name: 'Abrir projeto' }).click()
    if (width < 768) await page.getByRole('button', { name: 'Abrir navegação' }).click()
    await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Conhecimento' }).click()
    await expect(page.getByRole('heading', { name: 'Conhecimento local' })).toBeVisible()
    await expect(page.getByText('Nenhum documento indexado')).toBeVisible()
    await page.getByLabel('Arquivo do projeto').fill('docs/arquitetura.md')
    await page.getByRole('button', { name: 'Indexar arquivo' }).click()
    await expect(page.getByRole('listitem', { name: 'Documento docs/arquitetura.md' })).toBeVisible()
    const documentPicker = page.getByTestId('picker-knowledge-document')
    // Settle the browser's scroll before opening: React Aria closes a menu on ancestor scroll.
    await documentPicker.getByRole('button').scrollIntoViewIfNeeded()
    await page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))))
    await documentPicker.getByRole('button').click()
    await expect(documentPicker.getByRole('combobox')).toHaveAttribute('aria-expanded', 'true')
    await page.screenshot({ path: info.outputPath(`knowledge-document-picker-${width}.png`) })
    await page.getByRole('option', { name: 'docs/arquitetura.md' }).click()
    await expect(documentPicker.getByRole('combobox')).toHaveValue('docs/arquitetura.md')
    await documentPicker.getByRole('combobox').fill('arq')
    await expect(page.getByRole('option', { name: 'docs/arquitetura.md' })).toBeVisible()
    await page.getByRole('option', { name: 'docs/arquitetura.md' }).click()
    await page.getByLabel('Buscar no conhecimento').fill('proveniência')
    await page.getByRole('button', { name: 'Buscar', exact: true }).click()
    await expect(page.getByRole('listitem', { name: 'Resultado em docs/arquitetura.md linha 4' })).toContainText('proveniência')
    await expect(page.getByText(/Fonte modificada/).last()).toBeVisible()
    await page.getByTestId('picker-knowledge-server').getByRole('button').click()
    await page.getByRole('option', { name: 'LM Studio' }).click()
    await page.getByLabel('Modelo de embeddings').fill('local-embed')
    await expect(page.getByText('http://127.0.0.1:1234/v1/embeddings')).toBeVisible()
    await page.getByRole('button', { name: 'Salvar perfil local' }).click()
    await expect(page.getByText('0 de 1 trechos com vetores')).toBeVisible()
    await page.getByRole('button', { name: 'Indexar próximo lote' }).click()
    await expect(page.getByText('1 de 1 trechos com vetores')).toBeVisible()
    await page.getByRole('button', { name: 'Buscar', exact: true }).click()
    await expect(page.getByText('Busca híbrida')).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
    await page.screenshot({ path: info.outputPath(`knowledge-${width}.png`), fullPage: true })
    await page.getByRole('button', { name: 'Reindexar docs/arquitetura.md' }).click()
    await expect(page.getByRole('status').last()).toContainText('relido da origem')
    await page.reload()
    await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/api-faturas')
    await page.getByRole('button', { name: 'Abrir projeto' }).click()
    if (width < 768) await page.getByRole('button', { name: 'Abrir navegação' }).click()
    await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Conhecimento' }).click()
    await expect(page.getByRole('listitem', { name: 'Documento docs/arquitetura.md' })).toBeVisible()
    await expect(page.getByText('1 de 1 trechos com vetores')).toBeVisible()
    await page.getByRole('button', { name: 'Remover docs/arquitetura.md do índice' }).click()
    await expect(page.getByText('Nenhum documento indexado')).toBeVisible()
  })
}
