import { expect, test } from './locale'
import { checkboxSentence, stretchedChecks } from './targets'

for (const width of [320, 768, 900, 1024, 1440]) {
  test(`Coder session opens from the Code phase at ${width}px`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/e2e/fixture.html?scenario=pipeline-code')
    await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/api-faturas')
    await page.getByRole('button', { name: 'Abrir projeto' }).click()
    if (width < 768) await page.getByRole('button', { name: 'Abrir navegação' }).click()
    await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Pipelines' }).click()
    await expect(page.getByRole('navigation', { name: 'SDD Pipeline' }).locator('[aria-current="step"]')).toContainText('Code')
    await expect(page.getByRole('combobox', { name: 'Modelo da fase Code' })).toHaveValue('Modelo API')
    const executeCoder = page.getByRole('button', { name: 'Executar Coder' })
    await executeCoder.scrollIntoViewIfNeeded()
    await expect(executeCoder).toBeInViewport()
    if (width >= 1440) {
      const location = await executeCoder.boundingBox()
      expect(location && location.y + location.height).toBeLessThan(900)
    }
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
    await page.screenshot({ path: info.outputPath(`code-${width}.png`), fullPage: true })
    await executeCoder.click()
    await expect(page.getByLabel('Mensagem')).toBeVisible()
    if (width < 768) await page.getByRole('button', { name: 'Abrir navegação' }).click()
    await expect(page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Conversas' })).toHaveAttribute('aria-current', 'page')
    if (width < 768) await page.keyboard.press('Escape')
    await expect(page.getByRole('group', { name: 'Aprovação necessária' })).toBeVisible()
    await page.getByRole('tab', { name: 'Artefatos' }).click()
    await page.getByRole('group', { name: 'Tipo de artefato' }).getByRole('button', { name: 'SPEC', exact: true }).click()
    await expect(page.getByText('Critério: CSV correto')).toBeVisible()
  })
}

// The confirmation box once inherited the text-field sizing (full row, 44px tall), which squeezed its
// sentence into a column one letter wide and pushed the action buttons thousands of pixels down.
for (const width of [320, 768, 1440]) {
  test(`the copy confirmation keeps a small box and a readable sentence at ${width}px`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/e2e/fixture.html?scenario=pipeline-code-cli')
    await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/api-faturas')
    await page.getByRole('button', { name: 'Abrir projeto' }).click()
    if (width < 768) await page.getByRole('button', { name: 'Abrir navegação' }).click()
    await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Pipelines' }).click()
    await page.getByTestId('picker-pipeline-backend').getByRole('button').click()
    await page.getByRole('option', { name: 'Local API' }).click()
    const confirm = page.getByRole('checkbox', { name: /Confirmo copiar estes arquivos/i })
    await confirm.scrollIntoViewIfNeeded()
    const box = await confirm.boundingBox()
    expect(box!.width).toBeLessThanOrEqual(24)
    expect(box!.height).toBeLessThanOrEqual(24)
    const sentence = await checkboxSentence(page, /Confirmo copiar estes arquivos/i)
    expect(sentence.width).toBeGreaterThanOrEqual(150)
    expect(sentence.lines).toBeLessThanOrEqual(4)
    expect(await stretchedChecks(page)).toEqual([])
    // Both actions stay a short scroll away rather than below a wall of letters: the button sits within a screen of the box, wherever the page happens to start.
    const action = await page.getByRole('button', { name: 'Executar Coder' }).boundingBox()
    expect(action!.y - box!.y).toBeLessThan(400)
    await page.getByRole('button', { name: 'Executar Coder' }).scrollIntoViewIfNeeded()
    await expect(page.getByRole('button', { name: 'Executar Coder' })).toBeInViewport()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
    await page.screenshot({ path: info.outputPath(`copy-confirmation-${width}.png`) })
  })
}

test('requires an API override and copy confirmation before Code in a non-Git folder', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/e2e/fixture.html?scenario=pipeline-code-cli')
  await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/api-faturas')
  await page.getByRole('button', { name: 'Abrir projeto' }).click()
  await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Pipelines' }).click()

  await expect(page.getByText(/Codex CLI pode ler arquivos fora do projeto/i)).toBeVisible()
  const backendPicker = page.getByTestId('picker-pipeline-backend')
  await backendPicker.getByRole('button').click()
  await expect(page.getByRole('option', { name: 'Codex CLI · indisponível no SDD' })).toHaveAttribute('aria-disabled', 'true')
  await page.getByRole('option', { name: 'Local API' }).click()
  await expect(page.getByText(/4 arquivos · 0.0 MB/)).toBeVisible()
  await expect(page.getByRole('checkbox', { name: /Confirmo copiar estes arquivos/i })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Executar Coder' })).toBeDisabled()
  await page.getByRole('checkbox', { name: /Confirmo copiar estes arquivos/i }).check()
  await expect(page.getByRole('button', { name: 'Executar Coder' })).toBeEnabled()
  await page.getByRole('button', { name: 'Executar Coder' }).click()
  await expect(page.getByLabel('Mensagem')).toBeVisible()
})

for (const stage of ['code', 'eval'] as const) {
  test(`shows provider recovery instead of empty ${stage} selectors when Codex is the only executor`, async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 })
    await page.goto(`/e2e/fixture.html?scenario=pipeline-code-no-api&stage=${stage}`)
    await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/api-faturas')
    await page.getByRole('button', { name: 'Abrir projeto' }).click()
    await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Pipelines' }).click()

    const recovery = page.getByRole('alert').filter({ hasText: 'Code e QA precisam de um provedor API' })
    await expect(recovery).toContainText('O Codex CLI pode ler arquivos fora do projeto')
    await expect(page.getByRole('combobox', { name: 'Executor da fase' })).toHaveCount(0)
    await expect(page.getByRole('combobox', { name: `Modelo da fase ${stage === 'code' ? 'Code' : 'QA'}` })).toHaveCount(0)
    await expect(page.getByRole('button', { name: stage === 'code' ? 'Executar Coder' : 'Executar Evaluator' })).toHaveCount(0)
    await page.getByRole('button', { name: 'Configurar provedor API' }).click()
    await expect(page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Configurações' })).toHaveAttribute('aria-current', 'page')
  })
}

test('recovers a terminal legacy pipeline through fresh Code and Eval decisions', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/e2e/fixture.html?scenario=pipeline-code-legacy')
  await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/api-faturas')
  await page.getByRole('button', { name: 'Abrir projeto' }).click()
  await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Pipelines' }).click()

  const recovery = page.getByRole('region', { name: 'Recuperar revisão de Code' })
  await expect(recovery).toBeVisible()
  await expect(recovery).toContainText('SHA-256')
  await expect(page.getByRole('button', { name: 'Aplicar patch aprovado' })).toHaveCount(0)
  await recovery.getByRole('button', { name: 'Reabrir revisão de Code' }).click()
  await expect(page.getByRole('region', { name: 'Revisão de Code' })).toBeVisible()
  await expect(page.getByText('Este QA pertence a uma versão anterior de Code e não libera aplicação.')).toBeVisible()
  await page.getByRole('button', { name: 'Aprovar Code e iniciar QA' }).click()
  await expect(page.locator('.pipeline-phase-list .phase-active')).toContainText('QA')
  await expect(page.getByRole('button', { name: 'Executar Evaluator' })).toBeEnabled()
})

for (const width of [320, 768, 900, 1024, 1440]) {
  test(`completes Code and Eval through explicit controls at ${width}px`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/e2e/fixture.html?scenario=pipeline-code')
    await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/api-faturas')
    await page.getByRole('button', { name: 'Abrir projeto' }).click()
    const openPipelines = async () => {
      if (width < 768) await page.getByRole('button', { name: 'Abrir navegação' }).click()
      await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Pipelines' }).click()
    }
    const openConversations = async () => {
      if (width < 768) await page.getByRole('button', { name: 'Abrir navegação' }).click()
      await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Conversas' }).click()
    }
    await openPipelines()
    const executeCoder = page.getByRole('button', { name: 'Executar Coder' })
    await executeCoder.scrollIntoViewIfNeeded()
    await expect(executeCoder).toBeInViewport()
    await executeCoder.click()

    // The top bar follows the run instead of saying "Em andamento" from start to finish.
    const bar = page.getByRole('navigation', { name: 'SDD Pipeline' })
    const codeStage = bar.getByRole('listitem').filter({ hasText: 'Code' })
    const approval = page.getByRole('group', { name: 'Aprovação necessária' })
    await expect(approval).toBeVisible()
    await expect(codeStage).toContainText('Aguardando autorização')
    await approval.getByRole('button', { name: 'Aprovar' }).click()
    await expect(page.getByRole('status').filter({ hasText: 'Concluído' })).toBeVisible()
    await expect(codeStage).toContainText('Executado · verificar')
    await expect(codeStage).not.toContainText('Em andamento')
    if (width === 1440) await page.screenshot({ path: info.outputPath('pipeline-bar-code-executed.png') })
    await openPipelines()
    await page.getByRole('button', { name: 'Verificar código' }).click()

    await expect(page.getByRole('status').filter({ hasText: 'Code salvo para revisão' })).toContainText('Code salvo para revisão. Aprove a versão para liberar o QA.')
    // Verifying the Code closed the Coder's conversation. Going back to it finds that out, so the box carries on in a
    // new chat instead of failing at the first message.
    await openConversations()
    await expect(page.getByText(/Somente leitura: esta execução foi encerrada/)).toBeVisible()
    await expect(page.getByLabel('Mensagem')).toBeEnabled()
    await openPipelines()
    await expect(codeStage).toContainText('Aguardando decisão')
    await expect(page.locator('.pipeline-phase-list .phase-waiting_user')).toContainText('Aguardando decisão')
    await page.getByRole('button', { name: 'Aprovar Code e iniciar QA' }).click()
    await expect(page.locator('.pipeline-phase-list .phase-active')).toContainText('QA')
    await expect(page.getByRole('combobox', { name: 'Modelo da fase QA' })).toHaveValue('Modelo API')
    const executeEvaluator = page.getByRole('button', { name: 'Executar Evaluator' })
    await executeEvaluator.scrollIntoViewIfNeeded()
    await expect(executeEvaluator).toBeInViewport()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
    if (width >= 1440) {
      const location = await executeEvaluator.boundingBox()
      expect(location && location.y + location.height).toBeLessThan(900)
    }

    await executeEvaluator.click()
    await expect(page.getByText(/"passed":true/)).toBeVisible()
    await expect(page.getByRole('group', { name: 'Aprovação necessária' })).toHaveCount(0)
    await expect(bar.getByRole('listitem').filter({ hasText: 'QA' })).toContainText('Executado · registrar')
    await openPipelines()
    await page.getByRole('button', { name: 'Registrar avaliação' }).click()

    await expect(page.getByText('Resultado do QA salvo. Revise as evidências e decida o próximo passo.', { exact: true })).toBeVisible()
    await expect(page.getByText('Resultado: critérios atendidos')).toBeVisible()
    await expect(page.getByRole('button', { name: 'Aprovar QA e seguir para os PRs' })).toBeEnabled()
    await page.getByRole('button', { name: 'Aprovar QA e seguir para os PRs' }).click()
    // QA is done, but the pipeline is not: the last stage is handing the work to the agent as pull requests.
    await expect(page.locator('.pipeline-phase-list .phase-completed')).toHaveCount(5)
    await expect(page.locator('.pipeline-phase-list .phase-active')).toContainText('PRs')
    await expect(bar.getByRole('listitem').filter({ hasText: 'PRs' })).toContainText('Em andamento')
    const applyPatch = page.getByRole('button', { name: 'Aplicar patch aprovado' })
    await expect(applyPatch).toBeDisabled()
    expect(await stretchedChecks(page)).toEqual([])
    const prs = page.getByRole('region', { name: 'Abrir pull requests' })
    await expect(prs).toContainText('Aplique o patch aprovado ao projeto')
    await expect(prs.getByRole('button', { name: 'Abrir PRs com a IA' })).toBeDisabled()
    await page.getByRole('checkbox', { name: /Confirmo aplicar ao projeto original/i }).check()
    await applyPatch.click()
    await expect(page.getByText('Patch aplicado à pasta original e conferido após a gravação.', { exact: true })).toBeVisible()
    await expect(page.getByText(/Aplicado e conferido em/)).toBeVisible()
    if (width === 1440) await page.screenshot({ path: info.outputPath('professional-pipeline-applied.png'), fullPage: true })

    // The agent opens the pull requests in a conversation of its own; the bar follows it like it followed Code and QA.
    await expect(prs).toContainText('Servidor MCP conectado: GitHub')
    await expect(prs).toContainText('Hoje a IA pede a sua aprovação')
    await expect(prs).toContainText('o configurado no perfil')
    await expect(prs.getByRole('combobox', { name: /Modelo da fase/ })).toHaveCount(0)
    await expect(prs.getByTestId('picker-permission-profile').getByRole('button')).toHaveText(/Perguntar/)
    const openPullRequests = prs.getByRole('button', { name: 'Abrir PRs com a IA' })
    await expect(openPullRequests).toBeEnabled()
    await openPullRequests.click()
    await expect(page.getByText('https://github.com/acme/api-faturas/pull/12')).toBeVisible()
    await expect(page.getByRole('status').filter({ hasText: 'Concluído' })).toBeVisible()
    await expect(bar.getByRole('listitem').filter({ hasText: 'PRs' })).toContainText('Executado · concluir')
    if (width === 1440) await page.screenshot({ path: info.outputPath('pipeline-bar-prs-executed.png') })
    await openPipelines()
    const panel = page.getByRole('region', { name: 'Abrir pull requests' })
    await expect(panel).toContainText('A IA terminou. Leia o relatório na conversa e conclua a etapa.')
    await panel.getByRole('button', { name: 'Concluir PRs' }).click()
    await expect(page.getByRole('status').filter({ hasText: 'PRs concluídos' })).toBeVisible()
    await expect(page.locator('.pipeline-phase-list .phase-completed')).toHaveCount(6)
    const outcome = page.getByRole('region', { name: 'Pull requests abertos' })
    await expect(outcome).toContainText('https://github.com/acme/api-faturas/pull/12')
    await expect(bar.getByRole('listitem').filter({ hasText: 'PRs' })).toContainText('Concluído')
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
    if (width === 1440) await page.screenshot({ path: info.outputPath('pipeline-prs-completed.png'), fullPage: true })

    // A message typed and not sent in the open conversation is not thrown away by opening another one.
    await openConversations()
    await page.getByLabel('Mensagem').fill('rascunho que não deve se perder')
    await openPipelines()
    await outcome.getByRole('button', { name: 'Continuar a conversa dos PRs' }).click()
    await expect(outcome.getByRole('alert')).toContainText('Envie ou descarte o rascunho da conversa aberta antes de abrir outra.')
    await openConversations()
    await expect(page.getByLabel('Mensagem')).toHaveValue('rascunho que não deve se perder')
    await page.getByLabel('Mensagem').fill('')
    await openPipelines()

    // Finishing the stage does not close the work: a review comes back with fixes, and they go to the same agent.
    await expect(outcome.getByRole('button', { name: 'Continuar a conversa dos PRs' })).toBeVisible()
    await outcome.getByRole('button', { name: 'Corrigir os comentários da revisão' }).click()
    const message = page.getByLabel('Mensagem')
    await expect(message).toHaveValue(/Leia os comentários de revisão dos pull requests que você abriu/)
    await expect(message).toBeEnabled()
    await expect(page.getByText('https://github.com/acme/api-faturas/pull/12')).toBeVisible()
    await expect(page.getByRole('button', { name: 'Enviar' })).toBeEnabled()
  })
}

test('says what the Code needs when it is verified before its last run ended well', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.goto('/e2e/fixture.html?scenario=pipeline-code')
  await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/api-faturas')
  await page.getByRole('button', { name: 'Abrir projeto' }).click()
  await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Pipelines' }).click()
  await page.getByRole('button', { name: 'Verificar código' }).click()
  await expect(page.getByText(/O Code ainda não tem uma execução concluída com mudanças nos arquivos/)).toBeVisible()
  await expect(page.getByText('Salve a evidência exigida antes de avançar.')).toHaveCount(0)
})

test('the pull request stage can be skipped without opening anything', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.goto('/e2e/fixture.html?scenario=pipeline-code&stage=eval')
  await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/api-faturas')
  await page.getByRole('button', { name: 'Abrir projeto' }).click()
  await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Pipelines' }).click()
  await page.getByRole('button', { name: 'Executar Evaluator' }).click()
  await expect(page.getByText(/"passed":true/)).toBeVisible()
  await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Pipelines' }).click()
  await page.getByRole('button', { name: 'Registrar avaliação' }).click()
  await page.getByRole('button', { name: 'Aprovar QA e seguir para os PRs' }).click()
  const prs = page.getByRole('region', { name: 'Abrir pull requests' })
  await prs.getByRole('button', { name: 'Pular os PRs' }).click()
  await prs.getByLabel('Motivo (opcional)').fill('Vou abrir o PR pelo site')
  await prs.getByRole('button', { name: 'Confirmar pulo' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Etapa de PRs pulada' })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Pull requests' })).toContainText('Etapa pulada')
  await expect(page.getByRole('navigation', { name: 'SDD Pipeline' }).getByRole('listitem').filter({ hasText: 'PRs' })).toContainText('Pulada')
})
