import { expect, test } from '@playwright/test'

const providerName = 'API de testes financeiros com identificação extensa'
const modelName = 'Modelo de teste com descrição longa para validar truncamento responsivo'

test('shows a recovery path instead of empty provider selectors when Codex is the only default', async ({ page }, info) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/e2e/fixture.html?scenario=sdd-authoring-no-api')
  await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/api-faturas')
  await page.getByRole('button', { name: 'Abrir projeto' }).click()
  await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Pipelines' }).click()
  await page.getByLabel('Discovery', { exact: true }).fill('Criar um TODO sem rede e persistir no navegador.')
  await page.getByRole('button', { name: 'Criar pipeline' }).click()

  const recovery = page.getByRole('alert').filter({ hasText: 'Este pipeline precisa de um executor disponível' })
  await expect(recovery).toContainText('Este pipeline precisa de um executor disponível')
  await expect(recovery).toContainText('Codex CLI está configurado para Conversas')
  await expect(page.getByRole('combobox', { name: 'Provedor desta etapa' })).toHaveCount(0)
  await expect(page.getByRole('combobox', { name: 'Modelo' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Concluir Discovery e iniciar brainstorming' })).toHaveCount(0)
  await page.screenshot({ path: info.outputPath('professional-no-api-recovery.png'), fullPage: true })
  await page.getByRole('button', { name: 'Configurar provedor API' }).click()
  await expect(page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Configurações' })).toHaveAttribute('aria-current', 'page')
})

test('Discovery through SPEC revision and Plan remains explicit and readable across widths', async ({ page }, info) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/e2e/fixture.html?scenario=sdd-authoring')
  await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/api-faturas')
  await page.getByRole('button', { name: 'Abrir projeto' }).click()
  await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Pipelines' }).click()
  await page.getByLabel('Discovery', { exact: true }).fill('Precisamos exportar faturas em CSV com filtros.')
  await page.getByRole('button', { name: 'Criar pipeline' }).click()
  await expect(page.getByText('Escrito por você')).toBeVisible()
  await page.getByTestId('picker-brainstorm-provider').locator('button').click()
  await page.getByRole('option', { name: 'API de teste' }).click()
  await page.getByTestId('picker-brainstorm-model').locator('button').click()
  await page.getByRole('option', { name: 'Modelo de teste' }).click()
  await page.getByRole('button', { name: 'Concluir Discovery e iniciar brainstorming' }).click()
  await expect(page.getByRole('button', { name: 'Gerar pergunta' })).toBeVisible()
  await expect(page.getByText('Quem usa a exportação?')).toHaveCount(0)
  await page.getByRole('button', { name: 'Gerar pergunta' }).click()
  await expect(page.getByText('Quem usa a exportação?')).toBeVisible()
  await page.getByLabel('Sua resposta').fill('Equipe financeira')
  await page.getByRole('button', { name: 'Confirmar resposta' }).click()
  await page.getByRole('button', { name: 'Perguntas suficientes' }).click()
  await expect(page.getByText('Exportar faturas em CSV', { exact: true })).toBeVisible()
  for (const width of [320, 768, 900, 1024, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    await expect(page.getByRole('button', { name: 'Aprovar esta síntese' })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
    await page.screenshot({ path: info.outputPath(`brainstorm-${width}.png`), fullPage: true })
  }
  await page.getByRole('button', { name: 'Aprovar esta síntese' }).click()
  await expect(page.getByRole('heading', { name: 'Modelo e esforço desta fase' })).toBeVisible()
  await expect(page.getByText('Destino seguro da API')).toBeVisible()
  await expect(page.getByText('Permissões desta fase')).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'SDD Pipeline' }).locator('[aria-current="step"]')).toContainText('SPEC')
  const modelMode = page.getByTestId('picker-authoring-stage-model-spec').locator('button')
  await modelMode.focus()
  await expect(modelMode).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('option', { name: 'Escolher para esta fase' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(modelMode).toBeFocused()
  await page.keyboard.press('Enter')
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Enter')
  await expect(modelMode).toContainText('Escolher para esta fase')
  await page.getByTestId('picker-authoring-stage-provider-spec').locator('button').click()
  await page.getByRole('option', { name: providerName }).click()
  const catalogQueriesBeforeSelection = Number(await page.evaluate(() => sessionStorage.getItem('harflex:synthetic-authoring-catalog-queries') ?? '0'))
  await page.getByRole('button', { name: 'Consultar modelos' }).click()
  await page.getByTestId('picker-authoring-stage-override-model-spec').locator('button').click()
  await page.getByRole('option', { name: modelName }).click()
  await page.getByTestId('picker-authoring-stage-effort-spec').locator('button').click()
  await page.getByRole('option', { name: 'high' }).click()
  await page.getByRole('button', { name: 'Salvar preferência' }).click()
  await expect(page.getByRole('button', { name: 'Gerar SPEC' })).toBeEnabled()
  const providerControl = page.getByTestId('picker-authoring-stage-provider-spec').locator('input')
  const modelControl = page.getByTestId('picker-authoring-stage-override-model-spec').locator('input')
  expect(Number(await page.evaluate(() => sessionStorage.getItem('harflex:synthetic-authoring-catalog-queries') ?? '0'))).toBe(catalogQueriesBeforeSelection + 1)
  for (const width of [320, 768, 900, 1024, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    await expect(page.getByRole('heading', { name: 'Modelo e esforço desta fase' })).toBeVisible()
    if (width === 320 || width === 1024) {
      await expect(providerControl).toHaveAttribute('title', providerName)
      await expect(modelControl).toHaveAttribute('title', modelName)
    }
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
    await page.screenshot({ path: info.outputPath(`spec-controls-${width}.png`), fullPage: true })
  }
  const catalogQueriesBeforeReload = Number(await page.evaluate(() => sessionStorage.getItem('harflex:synthetic-authoring-catalog-queries') ?? '0'))
  await page.reload()
  await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/api-faturas')
  await page.getByRole('button', { name: 'Abrir projeto' }).click()
  await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Pipelines' }).click()
  await expect(page.getByRole('heading', { name: 'Modelo e esforço desta fase' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Salvar artefato' })).toHaveCount(0)
  await expect(page.getByRole('article')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Gerar SPEC' })).toBeDisabled()
  expect(Number(await page.evaluate(() => sessionStorage.getItem('harflex:synthetic-authoring-catalog-queries') ?? '0'))).toBe(catalogQueriesBeforeReload)
  await page.getByRole('button', { name: 'Consultar modelos' }).click()
  await page.getByRole('button', { name: 'Gerar SPEC' }).click()
  await expect(page.getByRole('heading', { name: 'Critérios de aceite' })).toBeVisible()
  await page.getByLabel('Feedback para revisão').fill('Especificar o formato de datas no CSV.')
  await page.getByRole('button', { name: 'Pedir revisão e gerar' }).click()
  await expect(page.getByRole('article', { name: 'Documento SPEC versão 2' })).toBeVisible()
  await page.emulateMedia({ reducedMotion: 'reduce' })
  for (const width of [320, 768, 900, 1024, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    await expect(page.getByRole('button', { name: 'Aprovar SPEC' })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
    const sizes = await page.locator('.authoring-stage button:visible, .authoring-stage summary:visible').evaluateAll(elements => elements.map(element => element.getBoundingClientRect().height))
    expect(sizes.every(height => height >= 44)).toBe(true)
    expect(await page.locator('.authoring-stage-model-preferences button').first().evaluate(element => getComputedStyle(element).transitionDuration)).toBe('0s')
    await page.screenshot({ path: info.outputPath(`spec-${width}.png`), fullPage: true })
  }
  const approve = page.getByRole('button', { name: 'Aprovar SPEC' })
  await approve.focus()
  await expect(approve).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'Modelo e esforço desta fase' })).toBeVisible()
  const planCatalogQueriesBefore = Number(await page.evaluate(() => sessionStorage.getItem('harflex:synthetic-authoring-catalog-queries') ?? '0'))
  await expect(page.getByRole('button', { name: 'Gerar Plan' })).toBeEnabled()
  expect(Number(await page.evaluate(() => sessionStorage.getItem('harflex:synthetic-authoring-catalog-queries') ?? '0'))).toBe(planCatalogQueriesBefore)
  await page.getByRole('button', { name: 'Gerar Plan' }).click()
  await expect(page.getByRole('heading', { name: 'Tarefas' })).toBeVisible()
  await expect(page.getByText('T1 · Implementar exportação')).toBeVisible()
  await expect(page.getByTestId('picker-authoring-stage-effort-plan').locator('button')).toContainText('Automático')
  await expect(page.getByText(new RegExp(`Modelo herdado de Configurações: ${providerName} · Modelo configurado com nome extenso para validar largura`))).toBeVisible()
  await expect(page.getByText(/A validação do catálogo acontecerá no servidor ao gerar/)).toBeVisible()
  await expect(page.getByText(/modelo padrão sem snapshot de catálogo/)).toHaveCount(0)
  for (const width of [320, 768, 900, 1024, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    await expect(page.getByRole('button', { name: 'Aprovar Plan' })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
    const sizes = await page.locator('.authoring-stage button:visible, .authoring-stage summary:visible').evaluateAll(elements => elements.map(element => element.getBoundingClientRect().height))
    expect(sizes.every(height => height >= 44)).toBe(true)
    await page.screenshot({ path: info.outputPath(`plan-${width}.png`), fullPage: true })
  }
  await page.getByRole('button', { name: 'Aprovar Plan' }).click()
  await expect(page.getByText(/Use os controles do pipeline abaixo para executar Code e QA/)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Executar Coder' })).toBeEnabled()
  await page.evaluate(() => {
    const pipeline = JSON.parse(sessionStorage.getItem('harflex:synthetic-authoring-pipeline')!)
    const key = `harflex:synthetic-stage:${pipeline.id}:spec`
    const spec = JSON.parse(sessionStorage.getItem(key)!)
    sessionStorage.setItem(key, JSON.stringify({ ...spec, state: 'cancellation_pending', cancellationPending: true, cancellationAttemptId: spec.attempts[0].id }))
    sessionStorage.setItem('harflex:synthetic-authoring-pipeline', JSON.stringify({ ...pipeline, currentStage: 'spec' }))
  })
  await page.reload()
  await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/api-faturas')
  await page.getByRole('button', { name: 'Abrir projeto' }).click()
  await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Pipelines' }).click()
  await page.getByRole('button', { name: 'Ver Discovery', exact: true }).click()
  await expect(page.getByText(/runner anterior ainda pode consumir recursos/)).toBeVisible()
  await page.getByRole('button', { name: 'Criar nova versão derivada' }).click()
  await expect(page.getByRole('button', { name: 'Criar pipeline derivado' })).toBeDisabled()
  await page.getByRole('checkbox', { name: /Entendo que derivar/ }).check()
  await page.getByRole('button', { name: 'Ver SPEC', exact: true }).click()
  await page.getByRole('button', { name: 'Ver Discovery', exact: true }).click()
  await page.getByRole('button', { name: 'Criar nova versão derivada' }).click()
  await expect(page.getByRole('checkbox', { name: /Entendo que derivar/ })).not.toBeChecked()
  await expect(page.getByRole('button', { name: 'Criar pipeline derivado' })).toBeDisabled()
  await page.getByRole('checkbox', { name: /Entendo que derivar/ }).check()
  await page.getByRole('button', { name: 'Criar pipeline derivado' }).click()
  await expect(page.getByRole('button', { name: 'Concluir Discovery e iniciar brainstorming' })).toBeVisible()
  await expect(page.getByText(/runner anterior ainda pode consumir recursos/)).toHaveCount(0)
  expect(await page.evaluate(() => JSON.parse(sessionStorage.getItem('harflex:synthetic-stage:authoring-1:spec')!).attemptCount)).toBe(2)
})
