import { expect, test } from './locale'

// Synthetic restart exercises the UI facade and persisted journal, not native CLI execution.
for (const width of [320, 1440]) for (const readOnly of [false, true]) {
  test(`reopens interrupted history and exports audit ${width}px readOnly=${readOnly}`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto(`/e2e/fixture.html?scenario=${readOnly ? 'foundation-readonly' : 'foundation'}`)
    await expect(page.getByText('Ferramentas de arquivo ficam nesta pasta. Shell e agentes CLI podem acessar recursos permitidos pela sua conta; revise cada aprovação.')).toBeVisible()
    await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/recovery')
    await page.getByRole('button', { name: 'Abrir projeto' }).click()
    await page.getByLabel('Motivo para pular SDD nesta sessão').fill('Teste de conversa livre')
    await page.getByRole('button', { name: 'Iniciar sessão livre' }).click()
    await page.getByLabel('Mensagem').fill('Trabalho antes do reinício')
    await page.getByRole('button', { name: 'Enviar' }).click()
    await expect(page.getByRole('status')).toContainText('Gerando resposta do agente')
    await page.evaluate(() => window.harflexSynthetic!.releaseStreaming())
    await expect(page.getByRole('group', { name: 'Aprovação necessária' })).toBeVisible()
    await page.reload()
    await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/recovery')
    await page.getByRole('button', { name: 'Abrir projeto' }).click()
    const list = page.getByRole('list', { name: 'Sessões recentes' })
    await expect(list).toContainText(readOnly ? 'Somente leitura' : 'Retomável')
    await expect(page.getByLabel('Mensagem')).toHaveCount(0)
    await list.getByRole('button', { name: 'Abrir histórico' }).click()
    await expect(page.getByRole('list', { name: 'Conversa' }).getByText('Trabalho antes do reinício', { exact: true })).toBeVisible()
    await expect(page.getByText('Resposta CLI preservada.', { exact: true })).toBeVisible()
    await expect(page.getByText('RAW_ONLY', { exact: true })).toHaveCount(0)
    await expect(page.getByRole('status')).toContainText('Interrompido')
    await expect(page.getByRole('group', { name: 'Aprovação necessária' })).toHaveCount(0)
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
    await page.screenshot({ path: info.outputPath(`recovery-${width}-${readOnly}.png`), fullPage: true })
    // A conversation that cannot be resumed keeps its message box: what is typed continues in a new one.
    if (readOnly) await expect(page.getByLabel('Mensagem')).toBeEnabled()
    else {
      await page.getByLabel('Mensagem').fill('Continue depois do reinício')
      await expect(page.getByRole('button', { name: 'Enviar' })).toBeEnabled()
      await page.getByRole('button', { name: 'Enviar' }).click()
      await expect(page.getByRole('status')).toContainText('Gerando resposta do agente')
      await page.evaluate(() => window.harflexSynthetic!.releaseStreaming())
      await expect(page.getByRole('group', { name: 'Aprovação necessária' })).toBeVisible()
      await page.getByRole('button', { name: 'Negar', exact: true }).click()
      await expect(page.getByRole('status')).toContainText('Falhou')
    }
    await page.getByRole('tab', { name: 'Artefatos' }).click()
    const trigger = page.getByRole('button', { name: 'Exportar auditoria' })
    await trigger.click()
    const dialog = page.getByRole('dialog', { name: 'Exportar auditoria' })
    const input = dialog.getByLabel('Caminho de destino')
    await expect(input).toBeFocused()
    await expect(input).toHaveValue('')
    expect(await page.locator('#root').evaluate(element => (element as HTMLElement).inert)).toBe(true)
    await expect(dialog).toContainText('arquivo JSONL')
    await expect(input).toHaveAttribute('placeholder', /\.jsonl/)
    await input.fill('/synthetic/audit.jsonl')
    const last = dialog.getByRole('button', { name: 'Exportar', exact: true })
    const first = dialog.getByRole('button', { name: 'Fechar', exact: true }).first()
    await last.focus()
    await page.keyboard.press('Tab')
    await expect(first).toBeFocused()
    await page.keyboard.press('Shift+Tab')
    await expect(last).toBeFocused()
    await last.click()
    await expect(dialog.getByRole('status')).toContainText('Auditoria JSONL exportada: /synthetic/audit.jsonl')
    expect(await page.evaluate(() => JSON.parse(sessionStorage.getItem('harflex:synthetic-foundation-journal:audit')!).destination)).toBe('/synthetic/audit.jsonl')
    await page.screenshot({ path: info.outputPath(`audit-${width}-${readOnly}.png`), fullPage: true })
    await page.keyboard.press('Escape')
    await expect(trigger).toBeFocused()
    expect(await page.locator('#root').evaluate(element => (element as HTMLElement).inert)).toBe(false)
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
  })
}

test('reopening history after an initial replay failure restores the connected composer', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 900 })
  await page.goto('/e2e/fixture.html?scenario=foundation-replay-recovery')
  await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/recovery')
  await page.getByRole('button', { name: 'Abrir projeto' }).click()
  await page.getByLabel('Motivo para pular SDD nesta sessão').fill('Teste de conversa livre')
  await page.getByRole('button', { name: 'Iniciar sessão livre' }).click()
  await page.getByLabel('Mensagem').fill('Trabalho antes do reinício')
  await page.getByRole('button', { name: 'Enviar' }).click()
  await page.evaluate(() => window.harflexSynthetic!.releaseStreaming())
  await expect(page.getByRole('group', { name: 'Aprovação necessária' })).toBeVisible()
  await page.reload()
  await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/recovery')
  await page.getByRole('button', { name: 'Abrir projeto' }).click()
  await page.getByRole('button', { name: 'Abrir histórico' }).click()
  await expect(page.getByRole('button', { name: 'Atualizar eventos' })).toBeVisible()
  await expect(page.getByText('Atualização dos eventos pendente')).toBeVisible()
  await page.getByRole('button', { name: 'Sessões do projeto' }).click()
  await page.getByRole('button', { name: 'Abrir histórico' }).click()
  await expect(page.getByText('Backend local conectado')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Atualizar eventos' })).toHaveCount(0)
  await expect(page.getByRole('status')).toContainText('Interrompido')
  await page.getByLabel('Mensagem').fill('Continue')
  await expect(page.getByRole('button', { name: 'Enviar' })).toBeEnabled()
})
