import { expect, test } from '@playwright/test'

for (const width of [320, 768, 900, 1024, 1440]) {
  test(`schedule, pause, manual job and reload at ${width}px`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/e2e/fixture.html?scenario=schedules')
    await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/api-faturas')
    await page.getByRole('button', { name: 'Abrir projeto' }).click()
    if (width < 768) await page.getByRole('button', { name: 'Abrir navegação' }).click()
    await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Agendamentos' }).click()
    await expect(page.getByText('Os agendamentos executam somente com o aplicativo aberto.')).toBeVisible()
    await page.getByLabel('Nome do agendamento').fill('Revisão diária')
    await page.getByTestId('picker-schedule-target-kind').getByRole('button').click()
    await page.getByRole('option', { name: 'Prompt', exact: true }).click()
    await page.getByRole('textbox', { name: 'Prompt', exact: true }).fill('Revise a documentação local')
    await page.getByTestId('picker-schedule-timezone').scrollIntoViewIfNeeded()
    await page.getByTestId('picker-schedule-timezone').getByRole('button').click()
    await expect(page.getByRole('listbox')).toBeVisible()
    await expect(page.getByTestId('picker-schedule-timezone').getByRole('combobox')).toBeFocused()
    await page.getByTestId('picker-schedule-timezone').getByRole('combobox').fill('America/Sao_Paulo')
    await expect(page.getByRole('listbox')).toBeVisible()
    await page.getByRole('option', { name: 'America/Sao_Paulo', exact: true }).click()
    await page.getByLabel('Horário local').fill('09:30')
    await page.getByRole('button', { name: 'Salvar agendamento' }).click()
    await expect(page.getByRole('button', { name: 'Pausar Revisão diária' })).toBeVisible()
    await page.getByRole('button', { name: 'Pausar Revisão diária' }).click()
    await expect(page.getByText('Pausado', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Executar agora Revisão diária' }).click()
    await expect(page.getByText('Concluído', { exact: true })).toBeVisible()
    await page.reload()
    await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/api-faturas')
    await page.getByRole('button', { name: 'Abrir projeto' }).click()
    if (width < 768) await page.getByRole('button', { name: 'Abrir navegação' }).click()
    await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Agendamentos' }).click()
    await expect(page.getByRole('button', { name: 'Retomar Revisão diária' })).toBeVisible()
    await expect(page.getByText('Concluído', { exact: true })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
    await page.screenshot({ path: info.outputPath(`schedules-${width}.png`), fullPage: true })
  })
}

test('one-time workflow schedule requires explicit CLI consent', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 720 })
  await page.goto('/e2e/fixture.html?scenario=schedules')
  await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/api-faturas')
  await page.getByRole('button', { name: 'Abrir projeto' }).click()
  await page.getByRole('button', { name: 'Abrir navegação' }).click()
  await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Agendamentos' }).click()
  await page.getByLabel('Nome do agendamento').fill('Documentar amanhã')
  await page.getByTestId('picker-schedule-target-kind').getByRole('button').click()
  await page.getByRole('option', { name: 'Workflow', exact: true }).click()
  const workflow = page.getByTestId('picker-schedule-workflow').getByRole('combobox')
  await workflow.click()
  await workflow.pressSequentially('Revisar e documentar')
  await page.getByRole('option', { name: 'Revisar e documentar', exact: true }).click()
  await page.getByTestId('picker-schedule-backend').getByRole('button').click()
  await page.getByRole('option', { name: 'Codex CLI', exact: true }).click()
  await page.getByTestId('picker-schedule-frequency').getByRole('button').click()
  await page.getByRole('option', { name: 'Uma vez', exact: true }).click()
  await page.getByLabel('Data local').fill('2026-09-27')
  await expect(page.getByText('o CLI executa com a autoridade do próprio processo', { exact: false })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Salvar agendamento' })).toBeDisabled()
  await page.getByRole('checkbox', { name: /Entendo que o CLI executa/ }).check()
  await page.getByRole('button', { name: 'Salvar agendamento' }).click()
  await expect(page.getByRole('button', { name: 'Editar Documentar amanhã' })).toBeVisible()
  await page.getByRole('button', { name: 'Editar Documentar amanhã' }).click()
  await expect(page.getByTestId('picker-schedule-workflow').getByRole('combobox')).toHaveValue('Revisar e documentar')
  await expect(page.getByTestId('picker-schedule-frequency').getByRole('button')).toContainText('Uma vez')
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(320)
})

test('session open failure is shown instead of leaving an unhandled rejection', async ({ page }) => {
  await page.goto('/e2e/fixture.html?scenario=schedules&openError=1')
  await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/api-faturas')
  await page.getByRole('button', { name: 'Abrir projeto' }).click()
  await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Agendamentos' }).click()
  await page.getByLabel('Nome do agendamento').fill('Revisão')
  await page.getByRole('textbox', { name: 'Prompt', exact: true }).fill('Revise')
  await page.getByRole('button', { name: 'Salvar agendamento' }).click()
  await page.getByRole('button', { name: 'Executar agora Revisão' }).click()
  await expect(page.getByRole('button', { name: 'Abrir sessão' })).toBeVisible()
  await page.getByRole('button', { name: 'Abrir sessão' }).click()
  await expect(page.getByRole('alert')).toContainText('A sessão não existe mais')
})

test('accepted cancellation stays pending until the job ends', async ({ page }) => {
  await page.goto('/e2e/fixture.html?scenario=schedules&cancelPending=1')
  await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/api-faturas')
  await page.getByRole('button', { name: 'Abrir projeto' }).click()
  await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Agendamentos' }).click()
  await page.getByLabel('Nome do agendamento').fill('Revisão')
  await page.getByRole('textbox', { name: 'Prompt', exact: true }).fill('Revise')
  await page.getByRole('button', { name: 'Salvar agendamento' }).click()
  await page.getByRole('button', { name: 'Executar agora Revisão' }).click()
  await page.getByRole('button', { name: 'Cancelar job' }).click()
  await expect(page.getByText('Cancelamento solicitado', { exact: true })).toBeVisible()
  await expect(page.getByRole('status')).toContainText('aguardando confirmação')
  await expect(page.getByText('Job cancelado.')).toHaveCount(0)
})
