import { expect, test } from './locale'

for (const width of [320, 768, 900, 1024, 1440]) {
  test(`provider settings work at ${width}px`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/e2e/fixture.html?scenario=settings')
    await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/api-faturas')
    await page.getByRole('button', { name: 'Abrir projeto' }).click()
    if (width < 768) await page.getByRole('button', { name: 'Abrir navegação' }).click()
    await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Configurações' }).click()
    await expect(page.getByRole('heading', { name: 'Configurações do Harflex' })).toBeVisible()
    await expect(page.getByText('modelo-local')).toBeVisible()
    await page.getByTestId('picker-settings-default-backend').getByRole('button').click()
    await page.getByRole('option', { name: 'Local' }).click()
    await page.getByRole('button', { name: 'Salvar preferências' }).click()
    await expect(page.getByRole('status')).toContainText('Preferências salvas')
    await page.getByRole('button', { name: 'Editar Local' }).click()
    const editor = page.getByRole('dialog', { name: 'Editar provedor' })
    const type = page.getByTestId('picker-provider-type')
    await expect(type.getByRole('button')).toBeVisible()
    await expect(editor.getByLabel('Token opcional')).toHaveValue('')
    await expect(editor.getByLabel('Token opcional')).toHaveAttribute('type', 'password')
    await type.getByRole('button').click()
    await expect(page.getByRole('listbox')).toBeVisible()
    await page.screenshot({ path: info.outputPath(`settings-provider-picker-${width}.png`) })
    await page.keyboard.press('Escape')
    await expect(editor).toBeVisible()
    await type.getByRole('button').focus()
    await page.keyboard.press('Tab')
    await expect(editor.getByLabel('URL base')).toBeFocused()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
    await page.screenshot({ path: info.outputPath(`settings-dialog-${width}.png`) })
    await editor.getByRole('textbox', { name: 'Modelo', exact: true }).fill('modelo-novo')
    await editor.getByRole('button', { name: 'Salvar provedor' }).click()
    await expect(page.getByText('modelo-novo', { exact: true })).toBeVisible()
    await expect(page.getByRole('radio', { name: /Sandbox/ })).toBeDisabled()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
    await page.screenshot({ path: info.outputPath(`settings-${width}.png`), fullPage: true })
    await page.getByRole('button', { name: 'Adicionar provedor' }).click()
    const newEditor = page.getByRole('dialog', { name: 'Configurar provedor' })
    await page.getByTestId('picker-provider-type').getByRole('button').click()
    await page.getByRole('option', { name: 'LM Studio local' }).click()
    await expect(page.getByTestId('picker-provider-type').getByRole('button')).toContainText('LM Studio local')
    await expect(newEditor.getByLabel('URL base')).toHaveValue('')
    await expect(newEditor.getByLabel('URL base')).toHaveAttribute('placeholder', 'http://127.0.0.1:1234/v1')
    await expect(newEditor.getByLabel('Token opcional')).toHaveJSProperty('required', false)
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
    await page.screenshot({ path: info.outputPath(`settings-lm-studio-${width}.png`) })
    await newEditor.getByLabel('URL base').fill('https://remote.example/v1')
    await expect(newEditor.getByRole('alert')).toContainText('IP literal de loopback')
    await expect(newEditor.getByLabel('Chave de API')).toHaveCount(0)
    await expect(newEditor.getByRole('button', { name: 'Salvar provedor' })).toBeDisabled()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
    await page.screenshot({ path: info.outputPath(`settings-local-blocked-${width}.png`) })
    await newEditor.getByLabel('URL base').fill('http://127.0.0.1:1234/v1')
    await expect(newEditor.getByRole('alert')).toHaveCount(0)
    await expect(newEditor.getByLabel('Token opcional')).toHaveJSProperty('required', false)
    await newEditor.getByLabel('Nome').fill('Studio de teste')
    const query = newEditor.getByRole('button', { name: 'Consultar modelos' })
    await query.scrollIntoViewIfNeeded()
    await page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))))
    await query.click()
    const modelPicker = page.getByTestId('picker-provider-model')
    await expect(modelPicker).toBeVisible()
    const modelTrigger = modelPicker.getByRole('button', { name: /Abrir opções/ })
    await modelTrigger.scrollIntoViewIfNeeded()
    await page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))))
    await modelTrigger.click()
    await expect(page.getByRole('option', { name: 'Qwen local' })).toBeVisible()
    await page.screenshot({ path: info.outputPath(`settings-model-catalog-${width}.png`) })
    await page.getByRole('option', { name: 'Qwen local' }).click()
    await expect(newEditor.getByRole('textbox', { name: 'Modelo', exact: true })).toHaveValue('local/qwen')
    await expect(newEditor.getByText(/instalado, mas não carregado/)).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
    await newEditor.getByRole('button', { name: 'Salvar provedor' }).click()
    await expect(page.getByRole('dialog', { name: 'Configurar provedor' })).not.toBeVisible()
    await expect(page.getByRole('button', { name: 'Editar Studio de teste' })).toBeVisible()
  })
}

for (const width of [320, 768, 900, 1024, 1440]) {
  test(`OpenRouter catalog key stays separate at ${width}px`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/e2e/fixture.html?scenario=settings')
    await page.getByLabel('Caminho da pasta').fill('/synthetic/workspace/api-faturas')
    await page.getByRole('button', { name: 'Abrir projeto' }).click()
    if (width < 768) await page.getByRole('button', { name: 'Abrir navegação' }).click()
    await page.getByRole('navigation', { name: 'Navegação principal' }).getByRole('button', { name: 'Configurações' }).click()
    await page.getByRole('button', { name: 'Editar Router' }).click()
    const editor = page.getByRole('dialog', { name: 'Editar provedor' })
    await expect(editor.getByText(/Sem chave de gerenciamento/)).toBeVisible()
    const managementKey = editor.getByLabel('Chave de gerenciamento do catálogo')
    await managementKey.fill('management-canary')
    await expect(editor.getByRole('button', { name: 'Consultar modelos' })).toBeDisabled()
    await editor.getByRole('button', { name: 'Salvar chave do catálogo' }).click()
    await expect(managementKey).toHaveValue('')
    await expect(editor.getByText(/Chave configurada para esta origem/)).toBeVisible()
    const query = editor.getByRole('button', { name: 'Consultar modelos' })
    await query.scrollIntoViewIfNeeded()
    await page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))))
    await query.click()
    await expect(editor.getByText('Catálogo filtrado pelas preferências da conta.')).toBeVisible()
    await page.screenshot({ path: info.outputPath(`settings-router-account-${width}.png`) })
    await editor.getByRole('button', { name: 'Remover chave do catálogo' }).click()
    await expect(editor.getByText(/histórico permanece/)).toBeVisible()
    await page.screenshot({ path: info.outputPath(`settings-router-confirm-${width}.png`) })
    await editor.getByRole('button', { name: 'Confirmar remoção' }).click()
    await expect(editor.getByText(/Sem chave de gerenciamento/)).toBeVisible()
    await query.click()
    await expect(editor.getByText('Catálogo geral, não filtrado pelas preferências da conta.')).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
    await page.screenshot({ path: info.outputPath(`settings-router-general-${width}.png`) })
  })
}
